In [1]:
import camelot

path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"
tables = camelot.read_pdf(path, pages='all')
tables

DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.

In [61]:
!pip install PyPDF2==2.12.1

Collecting PyPDF2==2.12.1
  Obtaining dependency information for PyPDF2==2.12.1 from https://files.pythonhosted.org/packages/2e/40/4f997b7cf72d89bb5aafd57b01dfa0be4e9560c8e5b993fde3986b3904f9/pypdf2-2.12.1-py3-none-any.whl.metadata
  Using cached pypdf2-2.12.1-py3-none-any.whl.metadata (6.6 kB)
Using cached pypdf2-2.12.1-py3-none-any.whl (222 kB)
Installing collected packages: PyPDF2
  Attempting uninstall: PyPDF2
    Found existing installation: PyPDF2 3.0.1
    Uninstalling PyPDF2-3.0.1:
      Successfully uninstalled PyPDF2-3.0.1
Successfully installed PyPDF2-2.12.1

In [62]:
import camelot

path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"
tables = camelot.read_pdf(path, pages='all')
tables

DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.

In [ ]:
import camelot
import PyPDF2

print(camelot.__version__)
print(PyPDF2.__version__)
!python --version

In [ ]:
import camelot

import re
 
 
# pdf_file_path =r"C:\Users\admin\Downloads\more retail limited\more retail limited\0000704865_2019_06_12_03_59_19_PM.pdf"
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"
 
 
tables_camelot = camelot.read_pdf(path, flavor='stream', pages='all')
 
 
for i,table in enumerate(tables_camelot, start=1):

    print(f"Table {i}:")

    print(table.df) 

    print("\n")

In [ ]:
# !pip uninstall camelot-py

In [ ]:
import subprocess

def extract_text_with_pdfbox(pdf_path):
    # Path to PDFBox jar file
    pdfbox_jar_path = "D:\Downloads\pdfbox-app-3.0.2.jar"
    
    command = [
        "java", "-jar", pdfbox_jar_path, "export:text", pdf_path
    ]
    
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        extracted_text = result.stdout
        return extracted_text.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error executing PDFBox command: {e}")
        return None

if __name__ == "__main__":
    pdf_path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"
    extracted _text = extract_text_with_pdfbox(pdf_path)
    
    if extracted_text:
        print(extracted_text)
    else:
        print("Failed to extract text from PDF.")

In [ ]:
!java -jar "D:\Downloads\pdfbox-app-3.0.2.jar" ExtractText "C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"

In [4]:
from PyPDF2 import PdfReader
import os

pdfs_dir = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf"
pdf_read = PdfReader(pdfs_dir)
text = '\n'.join([page.extract_text() for page in pdf_read.pages])
text

'Max Hypermarket India Pvt Ltd\nPurchase Order\n(System Generated)Corporate and Registered office:\n#39/3 & 44,\n2nd Floor, Above SPAR Hypermarket\nBannerghatta Road\nBangalore\nPh.No :+918041811600\nGST :29AAECM0847J1Z8  TIN \n:29880462412\nLocation:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173\nUser Id:  SCHEDRMS 4/8/2024 4:59:30 AM\nDelivery \nAddress:MARINA MALL CHN\n MARINA MALL, NO 13/1A\nEGATTUR OLD \nMAHABALIPURAM, \nTIRUPORUR TALUK  \nKANCHIPURAM DISTRICT \nCHENNAI 603106PO No: 11237019 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-\nCHENNAI\nPO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD  \nALAPAKKAM PORUR   CHENNAI 600116 \nGST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766\nTIN: 33AAECM0847J1ZJ PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW \nPO version: Original PO Status: Approved TIN:\nSKU Code\nSKU DescEAN\nHSNAR Qty MRP Unit  \nCostDisc % Tax-Rate%-TaxAmt Total Value\n100041077\nHIMALAYA FAIRNESS \nCREAM 50G8901138836146\n33049910    \nREG6 100 67.37CGST-9%-6.06\nSGST-9%-6.06477 \n100043179\nHIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML8901138512187\n33049990    \nREG 36 80 53.9SGST-9%-4.85\nCGST-9%-4.852289.6  \n100043181\nHIMALAYA PURIFYING\nNEEM FACE WASH 100\nML8901138512460\n33049990    \nPSS 24 150 101.06SGST-9%-9.1\nCGST-9%-9.12862 \n100043219\nHIMALAYA NEEM \nFOAMING FACE WASH \n150ML8901138512811\n33049990    \nREG 6 275 185.28SGST-9%-16.67\nCGST-9%-16.671311.75  \n100043661\nHIMALAYA PURIFYING\nNEEM SCRUB 100ML8901138821920\n33049990    \nREG12 160 107.8CGST-9%-9.7\nSGST-9%-9.71526.4  \n103656221\nHIMALAYA MEN POWER\nGLOW LICORICE FACE\nWASH 100ML8901138831073\n33049990    \nREG 6 189 127.33CGST-9%-11.46\nSGST-9%-11.46901.53  \n115400549\nHIMALAYA MEN\'S \nPIMPLE CLEAR NEEM \nFACE WASH 100ML8901138835330\n33049990    \nREG 6 189 127.33CGST-9%-11.46\nSGST-9%-11.46901.53  \n115400581\nHIMALAYA OIL CLEAR\nMUD FACE PACK 50 \nGMS8901138821968\n33049990    \nREG 30 85 57.27SGST-9%-5.15\nCGST-9%-5.152027.25  \n115400725\nHIMALAYA \nPROTECTIVE \nSUNSCREEN LOTION \n100ML8901138511104\n33049930    \nREG12 220 148.22CGST-9%-13.34\nSGST-9%-13.342098.8  \n120853981\nHIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n200ML8901138836450\n33049990    \nREG12 235 158.33SGST-9%-14.25\nCGST-9%-14.252241.9  \n122727785\nHIMALAYA TAN \nREMOVAL ORANGE \nFACE WASH 100ML8901138837044\n33049990    \nREG 12 180 121.27SGST-9%-10.91\nCGST-9%-10.911717.2  \n122728227\nHIMALAYA \nREFRESHING AND \nCLARIFYING TONER \n100ML8901138510329\n33049990    \nREG12 110 74.11SGST-9%-6.67\nCGST-9%-6.671049.4  \n128640525\nHIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERRY FACE \nWASH 100ML8901138839659\n33049990    \nREG12 160 107.8SGST-9%-9.7\nCGST-9%-9.71526.4  \n128640568\nHIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY FACE \nWASH 100ML8901138839680\n33049990    \nREG12 160 107.8CGST-9%-9.7\nSGST-9%-9.71526.4  \nMax Hypermarket India Pvt Ltd\nPurchase Order\n(System Generated)Corporate and Registered office:\n#39/3 & 44,\n2nd Floor, Above SPAR Hypermarket\nBannerghatta Road\nBangalore\nPh.No :+918041811600\nGST :29AAECM0847J1Z8  TIN \n:29880462412\nLocation:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173\nUser Id:  SCHEDRMS 4/8/2024 4:59:30 AM\nSKU Code\nSKU DescEAN\nHSNAR Qty MRP Unit  \nCostDisc % Tax-Rate%-TaxAmt Total Value\n150509435\nHIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTION 200ML8901138848736\n33049990    \nREG 6 205 138.11SGST-9%-12.43\nCGST-9%-12.43977.85  \n150509451\nHIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTION 400ML8901138848743\n33049990    \nREG 6 370 249.28CGST-9%-22.44\nSGST-9%-22.441764.9  \n154309377\nHIMALAYA NATURAL \nGLOW ALOEVERA GEL \n100ML8901138848484\n33049990    \nREG 24 85 57.27CGST-9%-5.15\nSGST-9%-5.151621.8  \n154309414\nHIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMULETHI SHEET MASK8901138849313\n33049990    \nREG20 75 50.53SGST-9%-4.55\nCGST-9%-4.551192.5  \n154309457\nHIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY SHEET \nMASK8901138849306\n33049990    \nREG20 75 50.53CGST-9%-4.55\nSGST-9%-4.551192.5  \n161614011\nHIMALAYA ROSE FACE\nWASH 100ML8901138847272\n33049990    \nREG24 160 107.8SGST-9%-9.7\nCGST-9%-9.73052.8  \n161614038\nHIMALAYA YOUTH \nETERNITY FACE \nSHEET MASK 1N8901138849320\n33049990    \nREG 20 85 57.27CGST-9%-5.15\nSGST-9%-5.151351.5  \nTotal:     5127.0972        33,611.01\nPurchase Order Terms & Conditions:\n1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and \nstamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice \nand not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed \ninvoice does not require any signature " ).\n2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the \nauthority must accompany with the goods / products (where ever it is applicable).\n3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and \norder.\n4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in \nreturn of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior \napproval from the Supplier / Vendor is required.\n5.All supplies should be strictly according to delivery date mentioned in the P.O.\n6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food \nSafety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.\n7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.\n8.All suppliers should strictly raise one invoice for one P.O for one delivery location.\n9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a \nsingle consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor, \nin terms of the Point No.4 above.\n10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of\nthe details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice\nof the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated \nissue.\n11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise \nshould carry the supplier barcode and not style code.\n12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working \ndays except on Sunday\'s, festival and national holidays. For actual delivery time contact respective delivery \nlocation.  \n13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase \nledger account.\n14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be \ncommunicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of\nthe Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on \nthe parties.\nMax Hypermarket India Pvt Ltd\nPurchase Order\n(System Generated)Corporate and Registered office:\n#39/3 & 44,\n2nd Floor, Above SPAR Hypermarket\nBannerghatta Road\nBangalore\nPh.No :+918041811600\nGST :29AAECM0847J1Z8  TIN \n:29880462412\nLocation:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173\nUser Id:  SCHEDRMS 4/8/2024 4:59:30 AM\n15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will \ndischarge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from \nthe Authority whatsoever anytime. \n16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged \nduties / tax liabilities to the Authority.\n17.The PO value is inclusive of delivery charges to the warehouse / store.\n18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be \nreceived by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are \nsent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for \ncollection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are \ncollected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective \nreceiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30 \ndays.\n19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.\n20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of\nchange shall be recovered from the seller.\n21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association \nwith the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and \nundertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in \nfuture.\n22.You understand and acknowledge that under Company\'s Code of Conduct and the Whistle Blower Policy, you shall report \nany unethical practice or wrongful conduct in the Company by way of an e-mail addressed to \ncomplianceofficer@maxhypermarkets.com .\n23.Incase \xa0any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe\nseller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to\nrecover\xa0 suchtaxliability amount/disallowed input \xa0GSTcredit withInterest andpenalty charged byGSTAuthority.\n24.Login to Vendor Portal to check Account Statements.\n25.For any further queries/ clarifications contact Service Helpdesk email ID:\nSpartradeaccounts.Helpdesk@landmarkgroup.in\n.\nBuyer\'s Signature Vendor\'s Signature'

In [41]:
import re
from PyPDF2 import PdfReader
import os
import pandas as pd

pdf_path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf"
pdf_read = PdfReader(pdf_path)
text = '\n'.join([page.extract_text() for page in pdf_read.pages])
pattern = r"(\d+)\n(HIM.+?)(\d{13})\n(\d+)\s*\n(\w{0,3})\s*(\d+)\s*(\d+)\s*(\d+\.\d+)(\w+)-(\d+)%-(\d+\.\d+)\n(\w+)-(\d+)%-(\d+\.\d{2})(\d+\.?\d*)"
rows = re.findall(pattern, text, re.DOTALL)
new_rows = []
for match in rows:
    match = list(match)
    if match[8]=='CGST':
        temp1 = match[8]
        temp2 = match[9]
        temp3 = match[10]
        match[8] = match[11]
        match[9] = match[12]
        match[10] = match[13]
        match[11] = temp1
        match[12] = temp2
        match[13] = temp3
    new_rows.append(match)
cols = ["SKU Code", "SKU Desc", "EAN", "HSN", "AR", "Qty", "MRP", "Unit Cost", "CGST", "SGST Tax-Rate%", "SGST TaxAmt","SGST", "CGST Tax-Rate%", "CGST TaxAmt", "Total Value"]
df = pd.DataFrame(new_rows, columns=cols)
del df['CGST']
del df['SGST']
print(text)
df

Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
Delivery
Address:MARINA MALL CHN
 MARINA MALL, NO 13/1A
EGATTUR OLD
MAHABALIPURAM,
TIRUPORUR TALUK
KANCHIPURAM DISTRICT
CHENNAI 603106PO No: 11237019 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD
ALAPAKKAM PORUR   CHENNAI 600116
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33AAECM0847J1ZJ PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW
PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100041077
HIMALAYA FAIRNESS
CREAM 50G8901138836146
33049910
REG6 100 67.37CGST-9%-6.06
SGST-9%-6.06477
100043179
HIMALAYA PURIFYING
NEEM FACE WASH 50
ML8901138512187
33049990
REG 36 80 53.9SGST-9%-4.85
CGST-9%-4.852289.6
100043181
HIMALAYA PURIFYING
NEEM FACE WASH 100
ML8901138512460
33049990
PSS 24 150 101.06SGST-9%-9.1
CGST-9%-9.12862
100043219
HIMALAYA NEEM
FOAMING FACE WASH
150ML8901138512811
33049990
REG 6 275 185.28SGST-9%-16.67
CGST-9%-16.671311.75
100043661
HIMALAYA PURIFYING
NEEM SCRUB 100ML8901138821920
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
103656221
HIMALAYA MEN POWER
GLOW LICORICE FACE
WASH 100ML8901138831073
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400549
HIMALAYA MEN'S
PIMPLE CLEAR NEEM
FACE WASH 100ML8901138835330
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400581
HIMALAYA OIL CLEAR
MUD FACE PACK 50
GMS8901138821968
33049990
REG 30 85 57.27SGST-9%-5.15
CGST-9%-5.152027.25
115400725
HIMALAYA
PROTECTIVE
SUNSCREEN LOTION
100ML8901138511104
33049930
REG12 220 148.22CGST-9%-13.34
SGST-9%-13.342098.8
120853981
HIMALAYA
MOISTURIZING
ALOEVERA FACE WASH
200ML8901138836450
33049990
REG12 235 158.33SGST-9%-14.25
CGST-9%-14.252241.9
122727785
HIMALAYA TAN
REMOVAL ORANGE
FACE WASH 100ML8901138837044
33049990
REG 12 180 121.27SGST-9%-10.91
CGST-9%-10.911717.2
122728227
HIMALAYA
REFRESHING AND
CLARIFYING TONER
100ML8901138510329
33049990
REG12 110 74.11SGST-9%-6.67
CGST-9%-6.671049.4
128640525
HIMALAYA FRESH
START - OIL CLEAR
STRAWBERRY FACE
WASH 100ML8901138839659
33049990
REG12 160 107.8SGST-9%-9.7
CGST-9%-9.71526.4
128640568
HIMALAYA FRESH
START - OIL CLEAR
BLUEBERRY FACE
WASH 100ML8901138839680
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
150509435
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 200ML8901138848736
33049990
REG 6 205 138.11SGST-9%-12.43
CGST-9%-12.43977.85
150509451
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 400ML8901138848743
33049990
REG 6 370 249.28CGST-9%-22.44
SGST-9%-22.441764.9
154309377
HIMALAYA NATURAL
GLOW ALOEVERA GEL
100ML8901138848484
33049990
REG 24 85 57.27CGST-9%-5.15
SGST-9%-5.151621.8
154309414
HIMALAYA CLEAR
COMPLEXION
BRIGHTENING
MULETHI SHEET MASK8901138849313
33049990
REG20 75 50.53SGST-9%-4.55
CGST-9%-4.551192.5
154309457
HIMALAYA FRESH
START OIL CLEAR
STRAWBERRY SHEET
MASK8901138849306
33049990
REG20 75 50.53CGST-9%-4.55
SGST-9%-4.551192.5
161614011
HIMALAYA ROSE FACE
WASH 100ML8901138847272
33049990
REG24 160 107.8SGST-9%-9.7
CGST-9%-9.73052.8
161614038
HIMALAYA YOUTH
ETERNITY FACE
SHEET MASK 1N8901138849320
33049990
REG 20 85 57.27CGST-9%-5.15
SGST-9%-5.151351.5
Total:     5127.0972        33,611.01
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature

,SKU Code,SKU Desc,EAN,HSN,AR,Qty,MRP,Unit Cost,SGST Tax-Rate%,SGST TaxAmt,CGST Tax-Rate%,CGST TaxAmt,Total Value
0,100041077,HIMALAYA FAIRNESS \nCREAM 50G,8901138836146,33049910,REG,6,100,67.37,9,6.06,9,6.06,477
1,100043179,HIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML,8901138512187,33049990,REG,36,80,53.9,9,4.85,9,4.85,2289.6
2,100043181,HIMALAYA PURIFYING\nNEEM FACE WASH 100\nML,8901138512460,33049990,PSS,24,150,101.06,9,9.1,9,9.12,862
3,100043219,HIMALAYA NEEM \nFOAMING FACE WASH \n150ML,8901138512811,33049990,REG,6,275,185.28,9,16.67,9,16.67,1311.75
4,100043661,HIMALAYA PURIFYING\nNEEM SCRUB 100ML,8901138821920,33049990,REG,12,160,107.8,9,9.71,9,9.7,526.4
5,103656221,HIMALAYA MEN POWER\nGLOW LICORICE FACE\nWASH 1...,8901138831073,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
6,115400549,HIMALAYA MEN'S \nPIMPLE CLEAR NEEM \nFACE WASH...,8901138835330,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
7,115400581,HIMALAYA OIL CLEAR\nMUD FACE PACK 50 \nGMS,8901138821968,33049990,REG,30,85,57.27,9,5.15,9,5.15,2027.25
8,115400725,HIMALAYA \nPROTECTIVE \nSUNSCREEN LOTION \n100ML,8901138511104,33049930,REG,12,220,148.22,9,13.34,9,13.34,2098.8
9,120853981,HIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n...,8901138836450,33049990,REG,12,235,158.33,9,14.25,9,14.25,2241.9
10,122727785,HIMALAYA TAN \nREMOVAL ORANGE \nFACE WASH 100ML,8901138837044,33049990,REG,12,180,121.27,9,10.91,9,10.91,1717.2
11,122728227,HIMALAYA \nREFRESHING AND \nCLARIFYING TONER \...,8901138510329,33049990,REG,12,110,74.11,9,6.67,9,6.67,1049.4
12,128640525,HIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERR...,8901138839659,33049990,REG,12,160,107.8,9,9.7,9,9.71,526.4
13,128640568,HIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY...,8901138839680,33049990,REG,12,160,107.8,9,9.71,9,9.7,526.4
14,150509435,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848736,33049990,REG,6,205,138.11,9,12.43,9,12.43,977.85
15,150509451,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848743,33049990,REG,6,370,249.28,9,22.44,9,22.44,1764.9
16,154309377,HIMALAYA NATURAL \nGLOW ALOEVERA GEL \n100ML,8901138848484,33049990,REG,24,85,57.27,9,5.15,9,5.15,1621.8
17,154309414,HIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMU...,8901138849313,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.5
18,154309457,HIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY ...,8901138849306,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.5
19,161614011,HIMALAYA ROSE FACE\nWASH 100ML,8901138847272,33049990,REG,24,160,107.8,9,9.7,9,9.73,052.8
20,161614038,HIMALAYA YOUTH \nETERNITY FACE \nSHEET MASK 1N,8901138849320,33049990,REG,20,85,57.27,9,5.15,9,5.15,1351.5

In [38]:
import pandas as pd
from PyPDF2 import PdfReader
import re
import os

def extract_data(pdf_path):
    pdf_read = PdfReader(pdf_path)
    text = '\n'.join([page.extract_text() for page in pdf_read.pages])
    print(text)
    pattern = r"(\d+)\n(HIM.+?)(\d{13})\n(\d+)\s*\n(\w{0,3})\s*(\d+)\s*(\d+)\s*(\d+\.?\d*)(\w+)-(\d+)%-(\d+\.\d+)\n(\w+)-(\d+)%-(\d+\.\d{2})(\d+\.?\d*)"
    rows = re.findall(pattern, text, re.DOTALL)
    new_rows = []
    for match in rows:
        match = list(match)
        if match[8]=='CGST':
            temp1 = match[8]
            temp2 = match[9]
            temp3 = match[10]
            match[8] = match[11]
            match[9] = match[12]
            match[10] = match[13]
            match[11] = temp1
            match[12] = temp2
            match[13] = temp3
        new_rows.append(match)
    cols = ["SKU Code", "SKU Desc", "EAN", "HSN", "AR", "Qty", "MRP", "Unit Cost", "CGST", "SGST Tax-Rate%", "SGST TaxAmt","SGST", "CGST Tax-Rate%", "CGST TaxAmt", "Total Value"]
    df = pd.DataFrame(new_rows, columns=cols)
    del df['CGST']
    del df['SGST']
    
    numerics = ["SKU Code", "EAN", "HSN", "Qty", "MRP", "Unit Cost", "SGST Tax-Rate%", "SGST TaxAmt", "CGST Tax-Rate%", "CGST TaxAmt", "Total Value"]
    for col in numerics:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df
    
directory = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max"
all_dfs = []
for file in os.listdir(directory):
    pdf_path = os.path.join(directory, file)
    print(pdf_path)
    df = extract_data(pdf_path)
    all_dfs.append(df)
#     print(df.to_string())
#     print("____________________________________________________________")
merged_table = pd.concat([table for table in all_dfs], ignore_index=True)
merged_table

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
Delivery
Address:MARINA MALL CHN
 MARINA MALL, NO 13/1A
EGATTUR OLD
MAHABALIPURAM,
TIRUPORUR TALUK
KANCHIPURAM DISTRICT
CHENNAI 603106PO No: 11237019 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD
ALAPAKKAM PORUR   CHENNAI 600116
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33AAECM0847J1ZJ PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW
PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100041077
HIMALAYA FAIRNESS
CREAM 50G8901138836146
33049910
REG6 100 67.37CGST-9%-6.06
SGST-9%-6.06477
100043179
HIMALAYA PURIFYING
NEEM FACE WASH 50
ML8901138512187
33049990
REG 36 80 53.9SGST-9%-4.85
CGST-9%-4.852289.6
100043181
HIMALAYA PURIFYING
NEEM FACE WASH 100
ML8901138512460
33049990
PSS 24 150 101.06SGST-9%-9.1
CGST-9%-9.12862
100043219
HIMALAYA NEEM
FOAMING FACE WASH
150ML8901138512811
33049990
REG 6 275 185.28SGST-9%-16.67
CGST-9%-16.671311.75
100043661
HIMALAYA PURIFYING
NEEM SCRUB 100ML8901138821920
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
103656221
HIMALAYA MEN POWER
GLOW LICORICE FACE
WASH 100ML8901138831073
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400549
HIMALAYA MEN'S
PIMPLE CLEAR NEEM
FACE WASH 100ML8901138835330
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400581
HIMALAYA OIL CLEAR
MUD FACE PACK 50
GMS8901138821968
33049990
REG 30 85 57.27SGST-9%-5.15
CGST-9%-5.152027.25
115400725
HIMALAYA
PROTECTIVE
SUNSCREEN LOTION
100ML8901138511104
33049930
REG12 220 148.22CGST-9%-13.34
SGST-9%-13.342098.8
120853981
HIMALAYA
MOISTURIZING
ALOEVERA FACE WASH
200ML8901138836450
33049990
REG12 235 158.33SGST-9%-14.25
CGST-9%-14.252241.9
122727785
HIMALAYA TAN
REMOVAL ORANGE
FACE WASH 100ML8901138837044
33049990
REG 12 180 121.27SGST-9%-10.91
CGST-9%-10.911717.2
122728227
HIMALAYA
REFRESHING AND
CLARIFYING TONER
100ML8901138510329
33049990
REG12 110 74.11SGST-9%-6.67
CGST-9%-6.671049.4
128640525
HIMALAYA FRESH
START - OIL CLEAR
STRAWBERRY FACE
WASH 100ML8901138839659
33049990
REG12 160 107.8SGST-9%-9.7
CGST-9%-9.71526.4
128640568
HIMALAYA FRESH
START - OIL CLEAR
BLUEBERRY FACE
WASH 100ML8901138839680
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
150509435
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 200ML8901138848736
33049990
REG 6 205 138.11SGST-9%-12.43
CGST-9%-12.43977.85
150509451
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 400ML8901138848743
33049990
REG 6 370 249.28CGST-9%-22.44
SGST-9%-22.441764.9
154309377
HIMALAYA NATURAL
GLOW ALOEVERA GEL
100ML8901138848484
33049990
REG 24 85 57.27CGST-9%-5.15
SGST-9%-5.151621.8
154309414
HIMALAYA CLEAR
COMPLEXION
BRIGHTENING
MULETHI SHEET MASK8901138849313
33049990
REG20 75 50.53SGST-9%-4.55
CGST-9%-4.551192.5
154309457
HIMALAYA FRESH
START OIL CLEAR
STRAWBERRY SHEET
MASK8901138849306
33049990
REG20 75 50.53CGST-9%-4.55
SGST-9%-4.551192.5
161614011
HIMALAYA ROSE FACE
WASH 100ML8901138847272
33049990
REG24 160 107.8SGST-9%-9.7
CGST-9%-9.73052.8
161614038
HIMALAYA YOUTH
ETERNITY FACE
SHEET MASK 1N8901138849320
33049990
REG 20 85 57.27CGST-9%-5.15
SGST-9%-5.151351.5
Total:     5127.0972        33,611.01
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_35000072315120240410024021PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  FORUM MALL - CHN Contact Person:THIYAGARAJAN Phone: 8050041880
User Id:  SCHEDRMS 4/8/2024 4:59:34 AM
Delivery
Address:FORUM MALL - CHN
UNIT NO 1, LOWER GRD
FLR  THE FORUM VIJAYA
MALL,183A  ARCOT ROAD,
VADAPALANI CHENNAI
600026PO No: 11237022 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD
ALAPAKKAM PORUR   CHENNAI 600116
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33961943783 PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW
PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100042811
HIMALAYA NEEM AND
TURMERIC SOAP 75G8901138711962
34011190
REG90 38 25.6SGST-9%-2.3
CGST-9%-2.32718.91
115420726
HIMALAYA NEEM AND
TURMERIC SOAP
75G*48901138827885
34011190
REG 48 141 95SGST-9%-8.55
CGST-9%-8.555380.56
Total:     1235.5176        8,099.47
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  FORUM MALL - CHN Contact Person:THIYAGARAJAN Phone: 8050041880
User Id:  SCHEDRMS 4/8/2024 4:59:34 AM
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_57000072309820240410075541PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:02:29 AM
Delivery
Address:VEGAS MALL
VEGAS MALL  UNIT NOS LG
14, LOWER GROUND FLOOR,
PLOT NO. 06, SECTOR 14
NORTH, DWARKA, NEW
DELHI 110078PO No: 11236931 Supplier: 59770 - THE HIMALAYA DRUG COMPANY-
DELHI
PO Date: 07-APR-2024 915-916  RITHALA INDUSTRIAL AREA,
RITHALA  NORTH WEST DELHI DELHI
110085
GST: 07AAECM0847J1ZE Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: PO Expiry Date: 14-APR-2024 GST: 07AADFT3025B1ZR
NA PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100009743
HIMALAYA BABY
CREAM 50ML8901138511487
33049990
REG24 95 59.58CGST-9%-5.36
SGST-9%-5.361687.2
100009745
HIMALAYA BABY
POWDER 100G8901138511814
33049190
REG18 105 65.85SGST-9%-5.93
CGST-9%-5.931398.6
100009975
HIMALAYA BABY
POWDER 400G8901138824037
33049190
REG10 290 181.86SGST-9%-16.37
CGST-9%-16.372146
120854941
HIMALAYA GENTLE
BABY WIPES 72S PO28901138834739
48182000
REG6 350 222.46SGST-9%-20.02
CGST-9%-20.021575
161614193
HIMALAYA BABY
MASSAGE OIL
MUSTARD 100ML8901138846961
33049990
REG 24 125 78.39CGST-9%-7.06
SGST-9%-7.062220
Total:     1376.9732        9,026.80
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.

,SKU Code,SKU Desc,EAN,HSN,AR,Qty,MRP,Unit Cost,SGST Tax-Rate%,SGST TaxAmt,CGST Tax-Rate%,CGST TaxAmt,Total Value
0,100041077,HIMALAYA FAIRNESS \nCREAM 50G,8901138836146,33049910,REG,6,100,67.37,9,6.06,9,6.06,477.00
1,100043179,HIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML,8901138512187,33049990,REG,36,80,53.90,9,4.85,9,4.85,2289.60
2,100043181,HIMALAYA PURIFYING\nNEEM FACE WASH 100\nML,8901138512460,33049990,PSS,24,150,101.06,9,9.10,9,9.12,862.00
3,100043219,HIMALAYA NEEM \nFOAMING FACE WASH \n150ML,8901138512811,33049990,REG,6,275,185.28,9,16.67,9,16.67,1311.75
4,100043661,HIMALAYA PURIFYING\nNEEM SCRUB 100ML,8901138821920,33049990,REG,12,160,107.80,9,9.71,9,9.70,526.40
5,103656221,HIMALAYA MEN POWER\nGLOW LICORICE FACE\nWASH 1...,8901138831073,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
6,115400549,HIMALAYA MEN'S \nPIMPLE CLEAR NEEM \nFACE WASH...,8901138835330,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
7,115400581,HIMALAYA OIL CLEAR\nMUD FACE PACK 50 \nGMS,8901138821968,33049990,REG,30,85,57.27,9,5.15,9,5.15,2027.25
8,115400725,HIMALAYA \nPROTECTIVE \nSUNSCREEN LOTION \n100ML,8901138511104,33049930,REG,12,220,148.22,9,13.34,9,13.34,2098.80
9,120853981,HIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n...,8901138836450,33049990,REG,12,235,158.33,9,14.25,9,14.25,2241.90
10,122727785,HIMALAYA TAN \nREMOVAL ORANGE \nFACE WASH 100ML,8901138837044,33049990,REG,12,180,121.27,9,10.91,9,10.91,1717.20
11,122728227,HIMALAYA \nREFRESHING AND \nCLARIFYING TONER \...,8901138510329,33049990,REG,12,110,74.11,9,6.67,9,6.67,1049.40
12,128640525,HIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERR...,8901138839659,33049990,REG,12,160,107.80,9,9.70,9,9.71,526.40
13,128640568,HIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY...,8901138839680,33049990,REG,12,160,107.80,9,9.71,9,9.70,526.40
14,150509435,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848736,33049990,REG,6,205,138.11,9,12.43,9,12.43,977.85
15,150509451,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848743,33049990,REG,6,370,249.28,9,22.44,9,22.44,1764.90
16,154309377,HIMALAYA NATURAL \nGLOW ALOEVERA GEL \n100ML,8901138848484,33049990,REG,24,85,57.27,9,5.15,9,5.15,1621.80
17,154309414,HIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMU...,8901138849313,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
18,154309457,HIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY ...,8901138849306,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
19,161614011,HIMALAYA ROSE FACE\nWASH 100ML,8901138847272,33049990,REG,24,160,107.80,9,9.70,9,9.73,52.80
20,161614038,HIMALAYA YOUTH \nETERNITY FACE \nSHEET MASK 1N,8901138849320,33049990,REG,20,85,57.27,9,5.15,9,5.15,1351.50
21,100042811,HIMALAYA NEEM AND \nTURMERIC SOAP 75G,8901138711962,34011190,REG,90,38,25.60,9,2.30,9,2.32,718.91
22,115420726,HIMALAYA NEEM AND \nTURMERIC SOAP \n75G*4,8901138827885,34011190,REG,48,141,95.00,9,8.55,9,8.55,5380.56
23,100009743,HIMALAYA BABY \nCREAM 50ML,8901138511487,33049990,REG,24,95,59.58,9,5.36,9,5.36,1687.20
24,100009745,HIMALAYA BABY \nPOWDER 100G,8901138511814,33049190,REG,18,105,65.85,9,5.93,9,5.93,1398.60
25,100009975,HIMALAYA BABY \nPOWDER 400G,8901138824037,33049190,REG,10,290,181.86,9,16.37,9,16.37,2146.00
26,120854941,HIMALAYA GENTLE \nBABY WIPES 72S PO2,8901138834739,48182000,REG,6,350,222.46,9,20.02,9,20.02,1575.00
27,161614193,HIMALAYA BABY \nMASSAGE OIL \nMUSTARD 100ML,8901138846961,33049990,REG,24,125,78.39,9,7.06,9,7.06,2220.00
28,100043179,HIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML,8901138512187,33049990,PSS,36,80,53.90,9,4.85,9,4.85,2289.60
29,100043181,HIMALAYA PURIFYING\nNEEM FACE WASH 100\nML,8901138512460,33049990,PSS,48,150,101.06,9,9.10,9,9.15,724.00
30,100043455,HIMALAYA FAIRNESS \nKESAR FACE WASH \n50ML,8901138819675,33049990,REG,30,85,57.27,9,5.15,9,5.15,2027.25
31,111500569,HIMALAYA STRESS \nRELIEF MASSAGE OIL\n200ML,8901138510626,33049990,REG,6,175,124.22,6,7.45,6,7.45,834.75
32,120853964,HIMALAYA PURIFYINF\nNEEM FACE WASH \n300ML,8901138835545,33049990,KVI,6,345,232.44,9,20.92,9,20.92,1645.65
33,120853981,HIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n...,8901138836450,33049990,REG,6,235,158.33,9,14.25,9,14.25,1120.95
34,122728227,HIMALAYA \nREFRESHING AND \nCLARIFYING TONER \...,8901138510329,33049990,REG,12,110,74.11,9,6.67,9,6.67,1049.40
35,128640525,HIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERR...,8901138839659,33049990,REG,12,160,107.80,9,9.70,9,9.71,526.40
36,128640568,HIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY...,8901138839680,33049990,REG,12,160,107.80,9,9.70,9,9.71,526.40
37,150509451,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848743,33049990,REG,6,370,249.28,9,22.44,9,22.44,1764.90
38,154309414,HIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMU...,8901138849313,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
39,154309457,HIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY ...,8901138849306,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
40,101542984,HIMALAYA ANTI HAIR\nFALL CREAM 175ML,8901138836160,33059030,REG,12,100,67.37,9,6.06,9,6.06,954.00
41,122728702,HIMALAYA ANIT HAIR\nFALL CONDITIONER \n100ML,8901138838539,33051090,REG,18,90,60.64,9,5.46,9,5.46,1287.90
42,154309676,HIMALAYA AYURVEDA \nGUM CARE \nTOOTHPASTE 80G,8901138847012,33061020,REG,48,65,43.79,9,3.94,9,3.94,2480.40
43,111500681,HIMALAYA \nANTISEPTIC CREAM \n20G,8901138509026,30049011,REG,12,55,39.04,6,2.34,6,2.34,524.70

In [4]:
import PyPDF2
import re

def detect_pdf_version(pdf_path):
    with open(pdf_path, 'rb') as file:
        file_header = file.read(1024)  # Read the first 1024 bytes (header)
        
        # Regular expression to find PDF version in the header
        version_match = re.search(rb"%PDF-(\d\.\d)", file_header)
        
        if version_match:
            pdf_version = version_match.group(1).decode()
            return pdf_version
        else:
            return "Unknown"

if __name__ == "__main__":
    pdf_path = 'C:\\Users\\TP_USER\\Downloads\\POReaderFormats\\POReaderFormats\\Walmart\\1712733040_29000070938720240410124104PM.PDF'
    
    try:
        version = detect_pdf_version(pdf_path)
        print(f"PDF Version: {version}")
    except Exception as e:
        print(f"Error reading PDF: {e}")

PDF Version: 1.6

In [27]:
import re
from PyPDF2 import PdfReader
import os

pdfs_dir = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats"
def contains_image(pdf_path):
    with open(pdf_path, 'rb') as file:
        pdf_reader = PdfReader(file)
        
        for page in pdf_reader.pages:
            if '/XObject' in page['/Resources']:
                return True
    return False

def detect_pdf_version(pdf_path):
    with open(pdf_path, 'rb') as file:
        file_header = file.read(1024)
        
        version_match = re.search(rb"%PDF-(\d\.\d)", file_header)
        
        if version_match:
            pdf_version = version_match.group(1).decode()
            return pdf_version
        else:
            return "Unknown"
# pdf_v_dicts = {'1.0':0, '1.1':0, '1.2':0, '1.3':0, '1.4':0, '1.5':0, '1.6':0, '1.7':0, "Unknown":0 }
pdf_v_dicts = {'1.0':{"Yes": 0, "No": 0}, '1.1':{"Yes": 0, "No": 0}, '1.2':{"Yes": 0, "No": 0}, '1.3':{"Yes": 0, "No": 0}, '1.4':{"Yes": 0, "No": 0}, '1.5':{"Yes": 0, "No": 0}, '1.6':{"Yes": 0, "No": 0}, '1.7':{"Yes": 0, "No": 0}, "Unknown":{"Yes": 0, "No": 0} }

pdf_versions = []
for folder in os.listdir(pdfs_dir):
    pdf_v_dicts2 = {'1.0':{"Yes": 0, "No": 0}, '1.1':{"Yes": 0, "No": 0}, '1.2':{"Yes": 0, "No": 0}, '1.3':{"Yes": 0, "No": 0}, '1.4':{"Yes": 0, "No": 0}, '1.5':{"Yes": 0, "No": 0}, '1.6':{"Yes": 0, "No": 0}, '1.7':{"Yes": 0, "No": 0}, "Unknown":{"Yes": 0, "No": 0} }
    
    directory_path = os.path.join(pdfs_dir, folder)
    print("\n", directory_path)

    for pdf in os.listdir(directory_path):
        if pdf.lower().endswith("pdf"):
            pdf_path = os.path.join(directory_path, pdf)
            version = detect_pdf_version(pdf_path)
            print(f"{pdf}:\t{version}")
            pdf_versions.append(version)
            if contains_image(pdf_path):   
                pdf_v_dicts[version]["Yes"]+=1 
                pdf_v_dicts2[version]["Yes"]+=1
                print(pdf_path)
            else:
                pdf_v_dicts[version]["No"]+=1 
                pdf_v_dicts2[version]["No"]+=1
    print(folder)
    for version in pdf_v_dicts2.items():
        if version[1]['Yes'] != 0 or version[1]['No'] != 0:
            print(version)

pdf_v_dicts

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya
0000704866_2018_06_22_02_14_03_PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_06_22_02_14_03_PM.pdf
0000704866_2018_06_25_11_44_16_AM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_06_25_11_44_16_AM.pdf
0000704866_2018_06_29_03_23_08_PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_06_29_03_23_08_PM.pdf
0000704866_2018_07_06_12_16_48_PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_07_06_12_16_48_PM.pdf
0000704866_2018_07_13_11_44_44_AM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_07_13_11_44_44_AM.pdf
1545711589620_1_0000707320_2018_12_25_09_48_35_AM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\1545711589620_1_0000707320_2018_12_25_09_48_35_AM.pdf
Aditya
('1.3', {'Yes': 6, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo
MTPO-731157-638276269826284184.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276269826284184.pdf
MTPO-731157-638276270138159286.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276270138159286.pdf
MTPO-731157-638276270440660100.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276270440660100.pdf
MTPO-731157-638276270876911265.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276270876911265.pdf
MTPO-731157-638276271176599639.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276271176599639.pdf
MTPO-731157-638276272219721636.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276272219721636.pdf
MTPO-731157-638276272573175595.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276272573175595.pdf
MTPO-731157-638276273527685560.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276273527685560.pdf
MTPO-731157-638276274134676406.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276274134676406.pdf
MTPO-731157-638276274457645956.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276274457645956.pdf
Apollo
('1.3', {'Yes': 10, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts
1582693640233_1_0000721831_2020_02_26_10_35_47_AM.pdf:	1.7
1712732435_85000072118820240410123151PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732435_85000072118820240410123151PM.pdf
1712732436_22000071748720240410123131PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732436_22000071748720240410123131PM.pdf
1712732436_43000071748720240410123117PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732436_43000071748720240410123117PM.pdf
1712732557_73000072118820240410123210PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732557_73000072118820240410123210PM.pdf
1712734729_38000071511320240410011018PM.pdf:	1.7
1712734729_6000071511320240410010933PM.pdf:	1.7
1712734850_13000073169620240410011204PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712734850_13000073169620240410011204PM.pdf
1712734850_28000073203020240410011137PM.pdf:	1.7
1712735455_64000073169620240410012107PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712735455_64000073169620240410012107PM.pdf
1712735937_41000072579020240410012842PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712735937_41000072579020240410012842PM.pdf
1712736059_67000072579020240410013030PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712736059_67000072579020240410013030PM.pdf
1712736180_16000072243820240410013354PM.pdf:	1.7
1712739670_02000072857320240410023206PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_02000072857320240410023206PM.pdf
1712739670_2000072857320240410023147PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_2000072857320240410023147PM.pdf
1712739670_37000072857320240410023124PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_37000072857320240410023124PM.pdf
1712739670_54000072857320240410023105PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_54000072857320240410023105PM.pdf
1712739791_08000072857320240410023413PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739791_08000072857320240410023413PM.pdf
1712740272_87000072874220240410024113PM.pdf:	1.7
1712743166_08000073241420240410033032PM.pdf:	1.7
1712743166_31000073241420240410033015PM.pdf:	1.7
1712743166_55000073241420240410032959PM.pdf:	1.7
1712743166_76000072874220240410032921PM.pdf:	1.7
1712745333_75000072337220240410040626PM.pdf:	1.7
1712750748_28000072373920240410053608PM.pdf:	1.7
MTPO-700574-637511386383630680.pdf:	1.7
MTPO-700574-637511424018065542.pdf:	1.7
MTPO-700574-637511577726599357.pdf:	1.7
MTPO-700574-637511578859350907.pdf:	1.7
MTPO-700574-637514850368847470.pdf:	1.7
MTPO-700574-637515093437838850.pdf:	1.7
MTPO-700574-637515917044811228.pdf:	1.7
MTPO-700574-637520904875680873.pdf:	1.7
MTPO-700574-637526152673937634.pdf:	1.7
MTPO-700574-637536608297402648.pdf:	1.7
MTPO-700574-637581703685500816.pdf:	1.7
MTPO-701489-637500333928797475.pdf:	1.7
MTPO-701489-637508880999132200.pdf:	1.4
MTPO-701489-637508881361023338.pdf:	1.4
MTPO-701489-637508881760946527.pdf:	1.4
MTPO-701489-637511658932004915.pdf:	1.4
MTPO-701489-637511663135162510.pdf:	1.4
MTPO-701489-637514387980399574.pdf:	1.7
MTPO-701489-637514801622948962.pdf:	1.7
MTPO-701489-637514802176663254.pdf:	1.7
MTPO-701489-637514843672110025.pdf:	1.7
MTPO-701489-637515125918965560.pdf:	1.7
MTPO-701489-637517476751078434.pdf:	1.4
MTPO-701489-637535031453670189.pdf:	1.4
MTPO-701489-637910886296937485.pdf:	1.4
MTPO-701489-637910886674306165.pdf:	1.4
MTPO-701686-637499384375117957.pdf:	1.7
MTPO-701686-637508843573575247.pdf:	1.7
MTPO-701686-637516853242431611.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637516853242431611.pdf
MTPO-701686-637522693294795291.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637522693294795291.pdf
MTPO-701686-637552048042073949.pdf:	1.7
MTPO-701686-637806124972423192.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637806124972423192.pdf
MTPO-701686-637859009160538999.pdf:	1.4
MTPO-701686-637910675703076374.pdf:	1.5
MTPO-701686-637910677076807255.pdf:	1.5
MTPO-701686-637910729741631377.pdf:	1.5
MTPO-701686-637910789576466177.pdf:	1.5
MTPO-701686-637911510965298811.pdf:	1.5
MTPO-701686-637913214625802769.pdf:	1.5
MTPO-701686-637913260387166167.pdf:	1.5
MTPO-703557-637461347520753879.pdf:	1.4
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637461347520753879.pdf
MTPO-703557-637467611908542946.pdf:	1.4
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637467611908542946.pdf
MTPO-703557-637476257086291678.pdf:	1.4
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637476257086291678.pdf
MTPO-703557-637496855413315295.pdf:	1.7
MTPO-703557-637496856152008988.pdf:	1.7
MTPO-703557-637496857788024637.pdf:	1.7
MTPO-703557-637496872081088397.pdf:	1.7
MTPO-703557-637496952029944468.pdf:	1.7
MTPO-703557-637497684423809190.pdf:	1.7
MTPO-703557-637497831289675519.pdf:	1.7
MTPO-703557-637498517143151469.pdf:	1.7
MTPO-703557-637498714495535986.pdf:	1.7
MTPO-703557-637499514652301426.pdf:	1.7
MTPO-703557-637503009082777438.pdf:	1.7
MTPO-703557-637503858372734011.pdf:	1.7
MTPO-703557-637504778717906414.pdf:	1.7
MTPO-703557-637505600022390925.pdf:	1.7
MTPO-703557-637509080759494492.pdf:	1.7
MTPO-703558-637499797932888908.pdf:	1.3
MTPO-703558-637499798592621426.pdf:	1.3
MTPO-703558-637499800306468189.pdf:	1.3
MTPO-703558-637499805440731119.pdf:	1.3
MTPO-703558-637507475639065995.pdf:	1.7
MTPO-703558-637507564333957469.pdf:	1.7
MTPO-703558-637507573157881036.pdf:	1.7
MTPO-703558-637507576066617343.pdf:	1.7
MTPO-703558-637512518657711236.pdf:	1.7
MTPO-703558-637512524488735389.pdf:	1.7
MTPO-703558-637512525446748022.pdf:	1.7
MTPO-703558-637512526989718029.pdf:	1.7
MTPO-703558-637512529487401326.pdf:	1.7
MTPO-703558-637512532846364364.pdf:	1.4
MTPO-703558-637512540511142394.pdf:	1.7
MTPO-703558-637512583645089973.pdf:	1.3
MTPO-716824-637506273606008958.pdf:	1.4
MTPO-716824-637506274093993136.pdf:	1.4
MTPO-716824-637508042951078933.pdf:	1.7
MTPO-716824-637517815639652287.pdf:	1.7
MTPO-716824-637538170511588086.pdf:	1.7
MTPO-716824-637538205363983676.pdf:	1.7
MTPO-716824-637916195707704961.pdf:	1.7
MTPO-716824-637916196353240567.pdf:	1.7
MTPO-716824-637916197332355760.pdf:	1.7
MTPO-716825-637530501095931758.pdf:	1.4
MTPO-718576-637497726947159935.pdf:	1.4
MTPO-718576-637497727254189834.pdf:	1.4
MTPO-718576-637497727648551346.pdf:	1.4
MTPO-718576-637497734960588239.pdf:	1.4
MTPO-718576-637497738092645874.pdf:	1.4
MTPO-718576-637499415136930716.pdf:	1.7
MTPO-718576-637499415605894912.pdf:	1.7
MTPO-718576-637500212287586835.pdf:	1.7
MTPO-718576-637504573080763900.pdf:	1.4
MTPO-718576-637504790138172301.pdf:	1.4
MTPO-718576-637505528235743178.pdf:	1.7
MTPO-718576-637505532461918231.pdf:	1.7
MTPO-718576-637505543388100249.pdf:	1.4
MTPO-718576-637506266156202291.pdf:	1.7
MTPO-718576-637506269870317333.pdf:	1.4
MTPO-718576-637508013129485847.pdf:	1.4
MTPO-718576-637508014947730772.pdf:	1.4
MTPO-718576-637509832439172892.pdf:	1.7
MTPO-718576-637514903665213601.pdf:	1.7
MTPO-718576-637514965566330767.pdf:	1.4
MTPO-718576-637516703394780617.pdf:	1.7
MTPO-718576-637516719756357869.pdf:	1.4
MTPO-718576-637517612035633994.pdf:	1.7
MTPO-718576-637518346685585291.pdf:	1.4
MTPO-718576-637523747972929176.pdf:	1.4
MTPO-718576-637527074830254984.pdf:	1.4
MTPO-718576-637533962013464064.pdf:	1.4
MTPO-718576-637539113557869582.pdf:	1.4
MTPO-718576-637587451017025046.pdf:	1.7
MTPO-718576-637953030375168503.pdf:	1.7
MTPO-718576-638041958462864901.pdf:	1.7
MTPO-718576-638247734552415187.pdf:	1.7
MTPO-718576-638252279579115950.pdf:	1.7
MTPO-718576-638252279957504465.pdf:	1.7
MTPO-719018-637711005133402599.pdf:	1.7
MTPO-719018-637711006364647831.pdf:	1.7
MTPO-719018-637712082776712527.pdf:	1.7
MTPO-719018-637712083270523685.pdf:	1.7
MTPO-719018-637712084214674282.pdf:	1.7
MTPO-719018-637715561826134325.pdf:	1.7
MTPO-719018-637717878784484191.pdf:	1.7
MTPO-719018-637723925213921148.pdf:	1.7
MTPO-719018-637730024385680493.pdf:	1.7
MTPO-719018-637734476571787537.pdf:	1.7
MTPO-719018-637734481357435801.pdf:	1.7
MTPO-719018-637811523052676932.pdf:	1.5
MTPO-719018-637811523443370743.pdf:	1.5
MTPO-719855-637506582526496146.pdf:	1.4
MTPO-719855-637526554042183520.pdf:	1.4
MTPO-719855-637536000486785480.pdf:	1.4
MTPO-719855-638194888527872550.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719855-638194888527872550.pdf
MTPO-719855-638246775479483880.pdf:	1.5
MTPO-720910-637503874422611546.pdf:	1.4
MTPO-720910-637503875469837690.pdf:	1.4
MTPO-720910-637503877243397490.pdf:	1.4
MTPO-720910-637503879131023149.pdf:	1.4
MTPO-720910-637503890009911366.pdf:	1.4
MTPO-720910-637503890608839345.pdf:	1.4
MTPO-720910-637503899687591645.pdf:	1.4
MTPO-720910-637503918720455172.pdf:	1.4
MTPO-723781-638041947484600930.pdf:	1.7
MTPO-723781-638041956759124766.pdf:	1.7
MTPO-723781-638041961117060912.pdf:	1.7
MTPO-723781-638041963660009842.pdf:	1.7
MTPO-723781-638041965964407228.pdf:	1.7
MTPO-723781-638067076139065300.pdf:	1.7
MTPO-723781-638158680874712839.pdf:	1.7
MTPO-723781-638158684971555107.pdf:	1.7
MTPO-723781-638158686427732119.pdf:	1.7
MTPO-723781-638158687237635937.pdf:	1.7
AvenueSupermarts
('1.3', {'Yes': 3, 'No': 5})
('1.4', {'Yes': 3, 'No': 43})
('1.5', {'Yes': 0, 'No': 10})
('1.7', {'Yes': 14, 'No': 101})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry
1582693400232_1_0000717697_2020_02_26_10_31_13_AM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1582693400232_1_0000717697_2020_02_26_10_31_13_AM.pdf
1712732194_47000072817120240410122738PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712732194_47000072817120240410122738PM.pdf
1712734005_25000071046420240410125809PM.pdf:	1.7
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712734005_25000071046420240410125809PM.pdf
1712735334_83000072817020240410011940PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712735334_83000072817020240410011940PM.pdf
1712736421_01000072920220240410013724PM.pdf:	1.5
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712736421_01000072920220240410013724PM.pdf
1712741356_61000072927220240410030001PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712741356_61000072927220240410030001PM.pdf
1712748582_35000072800220240410045921PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712748582_35000072800220240410045921PM.pdf
1712749304_24000073128920240410051146PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712749304_24000073128920240410051146PM.pdf
FirstCry
('1.3', {'Yes': 6, 'No': 0})
('1.5', {'Yes': 1, 'No': 0})
('1.7', {'Yes': 1, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max
1712740152_2000072315020240410024041PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf
1712740152_35000072315120240410024021PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_35000072315120240410024021PM.pdf
1712759055_57000072309820240410075541PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_57000072309820240410075541PM.pdf
1712759055_82000072309820240410075513PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_82000072309820240410075513PM.pdf
1712759055_99000072309820240410075459PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_99000072309820240410075459PM.pdf
1712759056_15000072309820240410075444PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759056_15000072309820240410075444PM.pdf
Max
('1.6', {'Yes': 6, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro
1712732315_17000073207120240410122851PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732315_17000073207120240410122851PM.PDF
1712732436_05000073253120240410123141PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_05000073253120240410123141PM.PDF
1712732436_76000073220420240410123058PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_76000073220420240410123058PM.PDF
1712732436_96000073253920240410123012PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_96000073253920240410123012PM.PDF
1712732557_54000073253720240410123226PM.PDF:	1.3

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732557_54000073253720240410123226PM.PDF
1712741235_5000070644720240410025834PM.pdf:	1.4
1712741235_71000071164920240410025804PM.pdf:	1.4
1712741235_85000070644720240410025744PM.pdf:	1.4
1712752432_81000073212320240410060440PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712752432_81000073212320240410060440PM.PDF
Metro
('1.3', {'Yes': 6, 'No': 0})
('1.4', {'Yes': 0, 'No': 3})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More
0000704865_2019_06_12_03_59_19_PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\0000704865_2019_06_12_03_59_19_PM.pdf
0000704865_2019_06_14_01_09_28_PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\0000704865_2019_06_14_01_09_28_PM.pdf
1712734971_63000072226420240410011224PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712734971_63000072226420240410011224PM.pdf
1712735092_12000072524520240410011600PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735092_12000072524520240410011600PM.pdf
1712735092_84000072524520240410011454PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735092_84000072524520240410011454PM.pdf
1712735213_33000072591220240410011808PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735213_33000072591220240410011808PM.pdf
1712735213_54000072226420240410011725PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735213_54000072226420240410011725PM.pdf
1712736662_18000072748420240410014123PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712736662_18000072748420240410014123PM.pdf
More
('1.3', {'Yes': 8, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\OPTIVAL
1712732436_57000071057820240410123117PM.pdf:	1.4
1712735335_04000071057820240410011846PM.pdf:	1.4
OPTIVAL
('1.4', {'Yes': 0, 'No': 2})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\PNB
0000704860_2023_05_22_09_40_08_AM.pdf:	1.4
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\PNB\0000704860_2023_05_22_09_40_08_AM.pdf
0000704860_2023_05_22_11_03_02_AM.pdf:	1.4
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\PNB\0000704860_2023_05_22_11_03_02_AM.pdf
PNB
('1.4', {'Yes': 2, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance
0000704860_2023_06_14_01_00_01_PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\0000704860_2023_06_14_01_00_01_PM.PDF
0000704860_2023_06_14_12_30_49_PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\0000704860_2023_06_14_12_30_49_PM.PDF
0000704860_2023_06_14_12_47_34_PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\0000704860_2023_06_14_12_47_34_PM.PDF
1582693520229_1_0000711842_2020_02_26_10_34_57_AM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1582693520229_1_0000711842_2020_02_26_10_34_57_AM.pdf
1712733160_89000070492820240410124410PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733160_89000070492820240410124410PM.pdf
1712733161_1000073219620240410124401PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733161_1000073219620240410124401PM.PDF
1712733161_35000073219620240410124346PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733161_35000073219620240410124346PM.PDF
1712733281_93000073028220240410124518PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733281_93000073028220240410124518PM.pdf
1712733282_2000073219620240410124428PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733282_2000073219620240410124428PM.PDF
1712733282_47000073219620240410124413PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733282_47000073219620240410124413PM.PDF
1712733403_08000073028220240410124702PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733403_08000073028220240410124702PM.pdf
1712733403_3000070492820240410124617PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733403_3000070492820240410124617PM.pdf
1712734005_05000072717520240410125810PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734005_05000072717520240410125810PM.PDF
1712734005_44000072717520240410125740PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734005_44000072717520240410125740PM.PDF
1712734005_69000072717520240410125714PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734005_69000072717520240410125714PM.PDF
1712734126_26000073071420240410125949PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734126_26000073071420240410125949PM.pdf
1712734126_46000072717520240410125833PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734126_46000072717520240410125833PM.PDF
1712734247_03000073071420240410010024PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734247_03000073071420240410010024PM.pdf
1712734367_59000072551020240410010410PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734367_59000072551020240410010410PM.pdf
1712734367_76000073071420240410010238PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734367_76000073071420240410010238PM.pdf
1712734488_23000072551020240410010505PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734488_23000072551020240410010505PM.pdf
1712734488_4000072551020240410010447PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734488_4000072551020240410010447PM.pdf
1712734488_57000072551020240410010428PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734488_57000072551020240410010428PM.pdf
1712734970_84000073071420240410011415PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734970_84000073071420240410011415PM.pdf
1712735455_81000072226920240410012113PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712735455_81000072226920240410012113PM.pdf
1712735455_98000072226920240410012031PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712735455_98000072226920240410012031PM.pdf
1712736661_93000070494020240410014207PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712736661_93000070494020240410014207PM.PDF
1712741236_03000073013220240410025722PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712741236_03000073013220240410025722PM.PDF
1712748581_95000072539320240410050048PM.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712748581_95000072539320240410050048PM.PDF
1712748582_17000072539320240410050033PM.pdf:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712748582_17000072539320240410050033PM.pdf
1712752433_07000073223920240410060438PM.pdf:	1.5
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712752433_07000073223920240410060438PM.pdf
Reliance
('1.3', {'Yes': 30, 'No': 0})
('1.5', {'Yes': 1, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\SampleandBlank
0000704860_2023_05_23_03_18_06_PM.pdf:	1.6
0000704860_2023_05_23_04_03_01_PM.pdf:	1.3
0000704860_2023_05_25_04_38_14_PM.pdf:	1.6
SampleandBlank
('1.3', {'Yes': 0, 'No': 1})
('1.6', {'Yes': 0, 'No': 2})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Vishal
MTPO-719018-637476241752854111.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Vishal\MTPO-719018-637476241752854111.PDF
MTPO-719018-637535840943261295.PDF:	1.3
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Vishal\MTPO-719018-637535840943261295.PDF
Vishal
('1.3', {'Yes': 2, 'No': 0})

 C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart
1712733039_24000070938720240410124200PM.PDF:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733039_24000070938720240410124200PM.PDF
1712733039_84000070938720240410124139PM.PDF:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733039_84000070938720240410124139PM.PDF
1712733040_29000070938720240410124104PM.PDF:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF
1712734971_01000070919420240410011351PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712734971_01000070919420240410011351PM.pdf
1712735092_29000071992120240410011511PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712735092_29000071992120240410011511PM.pdf
1712735213_7000072494220240410011641PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712735213_7000072494220240410011641PM.pdf
1712736057_93000070920420240410013210PM.PDF:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736057_93000070920420240410013210PM.PDF
1712736058_64000070920420240410013158PM.PDF:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736058_64000070920420240410013158PM.PDF
1712736059_11000070920420240410013148PM.PDF:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736059_11000070920420240410013148PM.PDF
1712741477_08000070919720240410030249PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_08000070919720240410030249PM.pdf
1712741477_45000070919720240410030227PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_45000070919720240410030227PM.pdf
1712741477_75000070919720240410030205PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_75000070919720240410030205PM.pdf
1712741478_18000070919720240410030144PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_18000070919720240410030144PM.pdf
1712741478_47000070919720240410030124PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_47000070919720240410030124PM.pdf

1712741478_76000070919720240410030103PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_76000070919720240410030103PM.pdf
1712741599_52000070919720240410030427PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741599_52000070919720240410030427PM.pdf
1712741599_84000070919720240410030402PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741599_84000070919720240410030402PM.pdf
1712741600_13000070919720240410030333PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741600_13000070919720240410030333PM.pdf
1712741600_45000070919720240410030310PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741600_45000070919720240410030310PM.pdf
1712741961_76000071112020240410031042PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741961_76000071112020240410031042PM.pdf
1712741962_23000071112020240410031001PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741962_23000071112020240410031001PM.pdf
1712742082_84000071112020240410031109PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712742082_84000071112020240410031109PM.pdf
1712744009_12000071112020240410034418PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712744009_12000071112020240410034418PM.pdf
1712744490_73000070919720240410035155PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712744490_73000070919720240410035155PM.pdf
1712744491_27000070919720240410035135PM.pdf:	1.6
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712744491_27000070919720240410035135PM.pdf
Walmart
('1.6', {'Yes': 25, 'No': 0})

{'1.0': {'Yes': 0, 'No': 0},
 '1.1': {'Yes': 0, 'No': 0},
 '1.2': {'Yes': 0, 'No': 0},
 '1.3': {'Yes': 71, 'No': 6},
 '1.4': {'Yes': 5, 'No': 48},
 '1.5': {'Yes': 2, 'No': 10},
 '1.6': {'Yes': 31, 'No': 2},
 '1.7': {'Yes': 15, 'No': 101},
 'Unknown': {'Yes': 0, 'No': 0}}

In [43]:
pdfs_dir = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart"
print(len(os.listdir(pdfs_dir)))
for pdf_name in os.listdir(pdfs_dir):
    
    pdf_path = os.path.join(pdfs_dir, pdf_name)
    print(pdf_path)
    pdf_read = PdfReader(pdf_path)
    text = '\n'.join([page.extract_text() for page in pdf_read.pages])
    version = detect_pdf_version(pdf_path)
    print("___________________________________________________________________________________")
    print(f"PDF Version: {version}")
    print(text)

25
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733039_24000070938720240410124200PM.PDF
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
Plot o.31,1st Floor, Kedia Business Pa
rk Opp:Ahmadji Bhai Petrol Pump, NH 06
Raipur,Chhattisgarh,492099,India
22AADFT3025B1ZZ GSTIN                            :
2005492201 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801392227 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4716)
Cash N Carry - Raipur - 1
BHANPURI, RING ROAD 2,
NEAR SANDEEP COLD STORAGE
RAIPUR-492008,India
Place of Supply : Chhattisgarh
22AADCB2110L1ZA GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4716)
Cash N Carry - Raipur - 1
BHANPURI, RING ROAD 2,
NEAR SANDEEP COLD STORAGE
RAIPUR-492008,India
Place of Supply : Chhattisgarh
22AADCB2110L1ZA GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#17106
#HIMALAYA BABY WIPES
GENTLE 72 N
#330790
#8901138513
#89011385131843 CS24EA/1CS 200.00/EA 2644.07 7932.21 IN: CGST(9%) - 713.90
IN: SGST(9%) - 713.90
IN: GST Comp.
CESS(0.00%) - 0.009360.01
2#17107
#HIMALAYA BABY SOAP
GENTLE 4N X 75 g
#340111
#8901138831
#89011388317381 CS18EA/1CS 228.00/EA 2260.68 2260.68 IN: CGST(9%) - 203.46
IN: SGST(9%) - 203.46
IN: GST Comp.
CESS(0.00%) - 0.002667.60
3#17110
#HIMALAYA BABY LOTION
100 ml
#330499
#8901138511
#89011385114633 CS36EA/1CS 110.00/EA 2181.36 6544.08 IN: CGST(9%) - 588.97
IN: SGST(9%) - 588.97
IN: GST Comp.
CESS(0.00%) - 0.007722.02
4#17685
#HIMALAYA BABY POWDER
200g
#330491
#8901138513
#89011385131536 CS24EA/1CS 195.00/EA 2577.97 15467.82 IN: CGST(9%) - 1392.10
IN: SGST(9%) - 1392.10
IN: GST Comp.
CESS(0.00%) - 0.0018252.02
5#19291
#HIMALAYA BABY LOTION
200 ml
#330499
#8901138511
#89011385114702 CS25EA/1CS 195.00/EA 2685.25 5370.50 IN: CGST(9%) - 483.35
IN: SGST(9%) - 483.35
IN: GST Comp.
CESS(0.00%) - 0.006337.20
: 08.04.2024 PO Order Dt : 7801392227 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4716) Bill To             :
Cash N Carry - Raipur - 1 Ship To               :
2005492201 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3
Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
6#20581
#HIMALAYA BABY
SHAMPOO GENTLE 200ml
#330590
#8901138511
#89011385114561 CS25EA/1CS 205.00/EA 2823.00 2823.00 IN: CGST(9%) - 254.07
IN: SGST(9%) - 254.07
IN: GST Comp.
CESS(0.00%) - 0.003331.14
7#20582
#HIMALAYA BABY
MASSAGE OIL 200ml
#330491
#8901138512
#89011385124083 CS36EA/1CS 210.00/EA 4164.41 12493.23 IN: CGST(9%) - 1124.39
IN: SGST(9%) - 1124.39
IN: GST Comp.
CESS(0.00%) - 0.0014742.01
8#23858
#HIMALAYA BABY SOAP
GENTLE 75g
#340111
#8901138511
#890113851183821 CS72EA/1CS 62.00/EA 2458.98 51638.58 IN: CGST(9%) - 4647.47
IN: SGST(9%) - 4647.47
IN: GST Comp.
CESS(0.00%) - 0.0060933.52
9#29555
#HIMALAYA BABY CREAM
50g
#330491
#8901138511
#89011385114879 CS50EA/1CS 95.00/EA 2616.50 23548.50 IN: CGST(9%) - 2119.37
IN: SGST(9%) - 2119.37
IN: GST Comp.
CESS(0.00%) - 0.0027787.24
10#29556
#HIMALAYA BABY CREAM
200 ml
#330491
#8901138831
#89011388315781 CS24EA/1CS 280.00/EA 3701.69 3701.69 IN: CGST(9%) - 333.15
IN: SGST(9%) - 333.15
IN: GST Comp.
CESS(0.00%) - 0.004367.99
131780.29 Total cost without tax
23720.46 Total tax amount
[(INR)  ONE LAKH FIFTY FIVE THOUSAND FIVE HUNDRED AND PAISE SEVENTY FIVE Only]155,500.75 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801392227 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4716) Bill To            :
Cash N Carry - Raipur - 1 Ship To               :
2005492201 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 3
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733039_84000070938720240410124139PM.PDF
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
Plot o.31,1st Floor, Kedia Business Pa
rk Opp:Ahmadji Bhai Petrol Pump, NH 06
Raipur,Chhattisgarh,492099,India
22AADFT3025B1ZZ GSTIN                            :
2005492201 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801392226 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4716)
Cash N Carry - Raipur - 1
BHANPURI, RING ROAD 2,
NEAR SANDEEP COLD STORAGE
RAIPUR-492008,India
Place of Supply : Chhattisgarh
22AADCB2110L1ZA GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4716)
Cash N Carry - Raipur - 1
BHANPURI, RING ROAD 2,
NEAR SANDEEP COLD STORAGE
RAIPUR-492008,India
Place of Supply : Chhattisgarh
22AADCB2110L1ZA GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#14898
#HIMALAYA FACE WASH
NEEM 50 ml
#330499
#8901138512
#89011385121871 CS72EA/1CS 80.00/EA 4002.71 4002.71 IN: CGST(9%) - 360.24
IN: SGST(9%) - 360.24
IN: GST Comp.
CESS(0.00%) - 0.004723.19
2#14899
#HIMALAYA FACE WASH
NEEM 100 ml
#330499
#8901138512
#89011385124601 CS48EA/1CS 150.00/EA 5003.39 5003.39 IN: CGST(9%) - 450.31
IN: SGST(9%) - 450.31
IN: GST Comp.
CESS(0.00%) - 0.005904.01
3#15665
#HIMALAYA FACEWASH
NEEM 150 ml
#330499
#8901138815
#89011388154311 CS24EA/1CS 205.00/EA 3418.98 3418.98 IN: CGST(9%) - 307.71
IN: SGST(9%) - 307.71
IN: GST Comp.
CESS(0.00%) - 0.004034.40
4#35339
#HIMALAYA BABY POWDER
100g
#330491
#8901138511
#890113851181423 CS36EA/1CS 105.00/EA 2082.20 47890.60 IN: CGST(9%) - 4310.15
IN: SGST(9%) - 4310.15
IN: GST Comp.
CESS(0.00%) - 0.0056510.90
5#15780
#HIMALAYA SOAP NEEM &
TURMERIC 4U X 75 g
#340111
#8901138827
#89011388278851 CS48EA/1CS 141.00/EA 4703.19 4703.19 IN: CGST(9%) - 423.29
IN: SGST(9%) - 423.29
IN: GST Comp.
CESS(0.00%) - 0.005549.77
65018.87 Total cost without tax
11703.40 Total tax amount
: 08.04.2024 PO Order Dt : 7801392226 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4716) Bill To             :
Cash N Carry - Raipur - 1 Ship To               :
2005492201 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3[(INR)  SEVENTY SIX THOUSAND SEVEN HUNDRED TWENTY TWO AND PAISE TWENTY SEVEN Only]76,722.27 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801392226 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4716) Bill To            :
Cash N Carry - Raipur - 1 Ship To               :
2005492201 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 3
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
Plot o.31,1st Floor, Kedia Business Pa
rk Opp:Ahmadji Bhai Petrol Pump, NH 06
Raipur,Chhattisgarh,492099,India
22AADFT3025B1ZZ GSTIN                            :
2005492201 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801392225 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4716)
Cash N Carry - Raipur - 1
BHANPURI, RING ROAD 2,
NEAR SANDEEP COLD STORAGE
RAIPUR-492008,India
Place of Supply : Chhattisgarh
22AADCB2110L1ZA GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4716)
Cash N Carry - Raipur - 1
BHANPURI, RING ROAD 2,
NEAR SANDEEP COLD STORAGE
RAIPUR-492008,India
Place of Supply : Chhattisgarh
22AADCB2110L1ZA GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#20133
#HIMALAYA FACE WASH
PURFYING NEEM2X150ml
#340130
#89011388231151 CS12EA/1CS 450.00/EA 3752.54 3752.54 IN: CGST(9%) - 337.73
IN: SGST(9%) - 337.73
IN: GST Comp.
CESS(0.00%) - 0.004428.00
2#18051
#HIMALAYA BABY WIPES 2
U X 72U
#33074900
#89011388347399 CS12EA/1CS 350.00/EA 2313.56 20822.04 IN: CGST(9%) - 1873.98
IN: SGST(9%) - 1873.98
IN: GST Comp.
CESS(0.00%) - 0.0024570.00
3#38963
#HIMALAYA PURIFYING
TULSI HANDWASH 750 ml
#330499
#89011388447384 CS12EA/1CS 115.00/EA 959.04 3836.16 IN: CGST(9%) - 345.25
IN: SGST(9%) - 345.25
IN: GST Comp.
CESS(0.00%) - 0.004526.66
28410.74 Total cost without tax
5113.92 Total tax amount
[(INR)  THIRTY THREE THOUSAND FIVE HUNDRED TWENTY FOUR AND PAISE SIXTY SIX Only]33,524.66 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801392225 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4716) Bill To            :
Cash N Carry - Raipur - 1 Ship To               :
2005492201 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.

___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
D.NO.14-96, Survey No.121/4, 123/4A, S
hed No.2C Kesarpalli Village, Gannavar
Vijayawada,Andhra Pradesh,521102,India
37AADFT3025B1ZO GSTIN                            :
2005493701 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801392078 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4799)
Cash N Carry - Visakhapatnam
89/5, 89/6, 89/8, 89/17
SURVEY NOS. 89/1, 89/2,
VISAKHAPATNAM-530026,India
Place of Supply : Andhra Pradesh
37AADCB2110L1ZZ GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4799)
Cash N Carry - Visakhapatnam
89/5, 89/6, 89/8, 89/17
SURVEY NOS. 89/1, 89/2,
VISAKHAPATNAM-530026,India
Place of Supply : Andhra Pradesh
37AADCB2110L1ZZ GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#14903
#HIMALAYA ANTI HAIR FALL
SHAMPOO 180ml
#330590
#89011388159361 CS24EA/1CS 160.00/EA 2668.32 2668.32 IN: CGST(9%) - 240.15
IN: SGST(9%) - 240.15
IN: GST Comp.
CESS(0.00%) - 0.003148.62
2#14898
#HIMALAYA FACE WASH
NEEM 50 ml
#330499
#89011385121871 CS72EA/1CS 80.00/EA 4002.71 4002.71 IN: CGST(9%) - 360.24
IN: SGST(9%) - 360.24
IN: GST Comp.
CESS(0.00%) - 0.004723.19
3#14899
#HIMALAYA FACE WASH
NEEM 100 ml
#330499
#89011385124601 CS48EA/1CS 150.00/EA 5003.39 5003.39 IN: CGST(9%) - 450.31
IN: SGST(9%) - 450.31
IN: GST Comp.
CESS(0.00%) - 0.005904.01
4#17685
#HIMALAYA BABY POWDER
200g
#330491
#89011385131532 CS24EA/1CS 195.00/EA 2577.97 5155.94 IN: CGST(9%) - 464.03
IN: SGST(9%) - 464.03
IN: GST Comp.
CESS(0.00%) - 0.006084.00
5#20581
#HIMALAYA BABY
SHAMPOO GENTLE 200ml
#330590
#89011385114562 CS25EA/1CS 205.00/EA 2823.00 5646.00 IN: CGST(9%) - 508.14
IN: SGST(9%) - 508.14
IN: GST Comp.
CESS(0.00%) - 0.006662.28
: 08.04.2024 PO Order Dt : 7801392078 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4799) Bill To             :
Cash N Carry - Visakhapatnam Ship To               :
2005493701 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3
Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
6#23858
#HIMALAYA BABY SOAP
GENTLE 75g
#340111
#89011385118381 CS72EA/1CS 62.00/EA 2458.98 2458.98 IN: CGST(9%) - 221.31
IN: SGST(9%) - 221.31
IN: GST Comp.
CESS(0.00%) - 0.002901.60
7#47131
#HIMALAYA EXTRA MOISTR
BABY SOAP 125g
#340111
#89011388222241 CS60EA/1CS 90.00/EA 2974.58 2974.58 IN: CGST(9%) - 267.71
IN: SGST(9%) - 267.71
IN: GST Comp.
CESS(0.00%) - 0.003510.00
8#53483
#HIMALAYA AYURVEDA
SANDALGLOW SOAP
4X75gm
#340111
#89011380008061 CS24EA/1CS 156.00/EA 2601.76 2601.76 IN: CGST(9%) - 234.16
IN: SGST(9%) - 234.16
IN: GST Comp.
CESS(0.00%) - 0.003070.08
9#53484
#HIMALAYA AYURVEDA
SANDAL GLOW SOAP
125gm
#340111
#89011380006461 CS72EA/1CS 69.00/EA 3452.34 3452.34 IN: CGST(9%) - 310.71
IN: SGST(9%) - 310.71
IN: GST Comp.
CESS(0.00%) - 0.004073.76
33964.02 Total cost without tax
6113.52 Total tax amount
[(INR)  FORTY THOUSAND SEVENTY SEVEN AND PAISE FIFTY FOUR Only]40,077.54 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801392078 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4799) Bill To            :
Cash N Carry - Visakhapatnam Ship To               :
2005493701 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 3
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712735213_7000072494220240410011641PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 4
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
D.NO.14-96, Survey No.121/4, 123/4A, S
hed No.2C Kesarpalli Village, Gannavar
Vijayawada,Andhra Pradesh,521102,India
37AADFT3025B1ZO GSTIN                            :
2005493701 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801392040 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4805)
Cash N Carry - Tirupati 4805
VILLAGE THUKIVAKAM OR RENIGUNTA,
SURVEY NO. 840/1A,
TIRUPATI-517506,India
Place of Supply : Andhra Pradesh
37AADCB2110L1ZZ GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4805)
Cash N Carry - Tirupati 4805
VILLAGE THUKIVAKAM OR RENIGUNTA,
SURVEY NO. 840/1A,
TIRUPATI-517506,India
Place of Supply : Andhra Pradesh
37AADCB2110L1ZZ GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#14897
#HIMALAYA FACE WASH
NEEM 12 U X 15 ml
#340130
#89011385136271 CS15EA/1CS 15.00/EA 1876.27 1876.27 IN: CGST(9%) - 168.86
IN: SGST(9%) - 168.86
IN: GST Comp.
CESS(0.00%) - 0.002213.99
2#14898
#HIMALAYA FACE WASH
NEEM 50 ml
#330499
#89011385121871 CS72EA/1CS 80.00/EA 4002.71 4002.71 IN: CGST(9%) - 360.24
IN: SGST(9%) - 360.24
IN: GST Comp.
CESS(0.00%) - 0.004723.19
3#14899
#HIMALAYA FACE WASH
NEEM 100 ml
#330499
#89011385124601 CS48EA/1CS 150.00/EA 5003.39 5003.39 IN: CGST(9%) - 450.31
IN: SGST(9%) - 450.31
IN: GST Comp.
CESS(0.00%) - 0.005904.01
4#20133
#HIMALAYA FACE WASH
PURFYING NEEM2X150ml
#340130
#89011388231151 CS12EA/1CS 345.00/EA 2876.88 2876.88 IN: CGST(9%) - 258.92
IN: SGST(9%) - 258.92
IN: GST Comp.
CESS(0.00%) - 0.003394.72
5#15443
#HIMALAYA COMPLETE
CARE TOOTHPASTE 150 g
#330610
#89011388361081 CS36EA/1CS 90.00/EA 2251.53 2251.53 IN: CGST(9%) - 202.64
IN: SGST(9%) - 202.64
IN: GST Comp.
CESS(0.00%) - 0.002656.81
: 08.04.2024 PO Order Dt : 7801392040 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4805) Bill To             :
Cash N Carry - Tirupati 4805 Ship To               :
2005493701 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 4
Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
6#17108
#HIMALAYA BABY SOAP
125g
#340111
#89011385126061 CS60EA/1CS 90.00/EA 2974.58 2974.58 IN: CGST(9%) - 267.71
IN: SGST(9%) - 267.71
IN: GST Comp.
CESS(0.00%) - 0.003510.00
7#17112
#HIMALAYA BABY
SHAMPOO GENTLE 100 ml
#330510
#89011385114492 CS36EA/1CS 105.00/EA 2082.24 4164.48 IN: CGST(9%) - 374.80
IN: SGST(9%) - 374.80
IN: GST Comp.
CESS(0.00%) - 0.004914.08
8#17685
#HIMALAYA BABY POWDER
200g
#330491
#89011385131533 CS24EA/1CS 195.00/EA 2577.97 7733.91 IN: CGST(9%) - 696.05
IN: SGST(9%) - 696.05
IN: GST Comp.
CESS(0.00%) - 0.009126.01
9#20581
#HIMALAYA BABY
SHAMPOO GENTLE 200ml
#330590
#89011385114561 CS25EA/1CS 185.00/EA 2823.00 2823.00 IN: CGST(9%) - 254.07
IN: SGST(9%) - 254.07
IN: GST Comp.
CESS(0.00%) - 0.003331.14
10#23858
#HIMALAYA BABY SOAP
GENTLE 75g
#340111
#89011385118383 CS72EA/1CS 62.00/EA 2458.98 7376.94 IN: CGST(9%) - 663.92
IN: SGST(9%) - 663.92
IN: GST Comp.
CESS(0.00%) - 0.008704.78
11#35339
#HIMALAYA BABY POWDER
100g
#330491
#89011385118143 CS36EA/1CS 105.00/EA 2082.20 6246.60 IN: CGST(9%) - 562.19
IN: SGST(9%) - 562.19
IN: GST Comp.
CESS(0.00%) - 0.007370.98
47330.29 Total cost without tax
8519.42 Total tax amount
[(INR)  FIFTY FIVE THOUSAND EIGHT HUNDRED FORTY NINE AND PAISE SEVENTY ONE Only]55,849.71 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
: 08.04.2024 PO Order Dt : 7801392040 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4805) Bill To             :
Cash N Carry - Tirupati 4805 Ship To               :
2005493701 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 4* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801392040 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4805) Bill To            :
Cash N Carry - Tirupati 4805 Ship To               :
2005493701 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 4 of 4
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736057_93000070920420240410013210PM.PDF
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
C-1/36 &  37 PHASE II Transport Nagar,
Lucknow,Uttar Pradesh,226012,India
09AADFT3025B1ZN GSTIN                            :
2005490901 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801391649 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4727)
Cash N Carry - Lucknow
SUSHANT GOLF CITY AMAR SHAHEED PATH
LUCKNOW-226002,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4727)
Cash N Carry - Lucknow
SUSHANT GOLF CITY AMAR SHAHEED PATH
LUCKNOW-226002,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#16520
#HIMALAYA SKIN CREAM
NOURISHING 50ml
#330491
#8901138506
#89011385063771 CS30EA/1CS 85.00/EA 1772.03 1772.03 IN: CGST(9%) - 159.48
IN: SGST(9%) - 159.48
IN: GST Comp.
CESS(0.00%) - 0.002090.99
2#14897
#HIMALAYA FACE WASH
NEEM 12 U X 15 ml
#340130
#8901138513
#89011385136273 CS15EA/1CS 15.00/EA 1876.27 5628.81 IN: CGST(9%) - 506.59
IN: SGST(9%) - 506.59
IN: GST Comp.
CESS(0.00%) - 0.006641.99
3#16443
#HIMALAYA FACE WASH
NEEM PURIFYING 200 ml
#330499
#8901138822
#89011388224772 CS18EA/1CS 299.00/EA 3740.04 7480.08 IN: CGST(9%) - 673.21
IN: SGST(9%) - 673.21
IN: GST Comp.
CESS(0.00%) - 0.008826.50
4#25251
#HIMALAYA FACE WASH
KESAR 150 ml
#330499
#8901138825
#89011388253791 CS24EA/1CS 210.00/EA 3502.37 3502.37 IN: CGST(9%) - 315.21
IN: SGST(9%) - 315.21
IN: GST Comp.
CESS(0.00%) - 0.004132.79
5#36379
#HIMALAYA FACEWASHOIL
CLEAR LEMON 100 ml
#330499
#89011388396731 CS30EA/1CS 160.00/EA 3335.59 3335.59 IN: CGST(9%) - 300.20
IN: SGST(9%) - 300.20
IN: GST Comp.
CESS(0.00%) - 0.003935.99
: 08.04.2024 PO Order Dt : 7801391649 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4727) Bill To             :
Cash N Carry - Lucknow Ship To               :
2005490901 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3
Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost

___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
C-1/36 &  37 PHASE II Transport Nagar,
Lucknow,Uttar Pradesh,226012,India
09AADFT3025B1ZN GSTIN                            :
2005490901 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 6300452910 PURCHASE ORDER NO.
: 04.04.2024 ORDER DATE
: 18.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4727)
Cash N Carry - Lucknow
SUSHANT GOLF CITY AMAR SHAHEED PATH
LUCKNOW-226002,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4727)
Cash N Carry - Lucknow
SUSHANT GOLF CITY AMAR SHAHEED PATH
LUCKNOW-226002,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#17112
#HIMALAYA BABY
SHAMPOO GENTLE 100 ml
#330510
#8901138511
#890113851144931 CS36EA/1CS 105.00/EA 2082.24 64549.44 IN: CGST(9%) - 5809.45
IN: SGST(9%) - 5809.45
IN: GST Comp.
CESS(0.00%) - 0.0076168.34
2#17685
#HIMALAYA BABY POWDER
200g
#330491
#8901138513
#890113851315321 CS24EA/1CS 195.00/EA 2577.97 54137.37 IN: CGST(9%) - 4872.36
IN: SGST(9%) - 4872.36
IN: GST Comp.
CESS(0.00%) - 0.0063882.09
3#19290
#HIMALAYA BABY CREAM
100 ml
#330499
#8901138511
#890113851149410 CS48EA/1CS 175.00/EA 4362.71 43627.10 IN: CGST(9%) - 3926.44
IN: SGST(9%) - 3926.44
IN: GST Comp.
CESS(0.00%) - 0.0051479.98
4#29555
#HIMALAYA BABY CREAM
50g
#330491
#8901138511
#890113851148721 CS50EA/1CS 95.00/EA 2616.50 54946.50 IN: CGST(9%) - 4945.19
IN: SGST(9%) - 4945.19
IN: GST Comp.
CESS(0.00%) - 0.0064836.88
217260.41 Total cost without tax
39106.88 Total tax amount
[(INR)  TWO LAKH FIFTY SIX THOUSAND THREE HUNDRED SIXTY SEVEN AND PAISE TWENTY NINE Only]256,367.29 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
: 04.04.2024 PO Order Dt : 6300452910 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4727) Bill To             :
Cash N Carry - Lucknow Ship To               :
2005490901 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3* Computer/System generated purchase order and does not require any signature
: 04.04.2024 PO Order Dt : 6300452910 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4727) Bill To            :
Cash N Carry - Lucknow Ship To               :
2005490901 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 3
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_08000070919720240410030249PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 6300452976 PURCHASE ORDER NO.
: 04.04.2024 ORDER DATE
: 18.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#14897
#HIMALAYA FACE WASH
NEEM 12 U X 15 ml
#340130
#89011385136271 CS15EA/1CS 15.00/EA 1876.27 1876.27 IN: CGST(9%) - 168.86
IN: SGST(9%) - 168.86
IN: GST Comp.
CESS(0.00%) - 0.002213.99
1876.27 Total cost without tax
337.72 Total tax amount
[(INR)  TWO THOUSAND TWO HUNDRED THIRTEEN AND PAISE NINETY NINE Only]2,213.99 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 04.04.2024 PO Order Dt : 6300452976 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4720) Bill To            :
Cash N Carry - Meerut Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_45000070919720240410030227PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 6300452991 PURCHASE ORDER NO.
: 04.04.2024 ORDER DATE
: 18.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#15443
#HIMALAYA COMPLETE
CARE TOOTHPASTE 150 g
#330610
#8901138826
#89011388361081 CS36EA/1CS 90.00/EA 2251.53 2251.53 IN: CGST(9%) - 202.64
IN: SGST(9%) - 202.64
IN: GST Comp.
CESS(0.00%) - 0.002656.81
2251.53 Total cost without tax
405.28 Total tax amount
[(INR)  TWO THOUSAND SIX HUNDRED FIFTY SIX AND PAISE EIGHTY ONE Only]2,656.81 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 04.04.2024 PO Order Dt : 6300452991 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4720) Bill To            :
Cash N Carry - Meerut Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_75000070919720240410030205PM.pdf

___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 6300452931 PURCHASE ORDER NO.
: 04.04.2024 ORDER DATE
: 18.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#46279
#HIMALAYA OLIVE EXTRA
NOURISH CREAM 200g
#330499
#89011388489651 CS12EA/1CS 235.00/EA 1959.66 1959.66 IN: CGST(9%) - 176.37
IN: SGST(9%) - 176.37
IN: GST Comp.
CESS(0.00%) - 0.002312.40
1959.66 Total cost without tax
352.74 Total tax amount
[(INR)  TWO THOUSAND THREE HUNDRED TWELVE AND PAISE FORTY Only]2,312.40 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 04.04.2024 PO Order Dt : 6300452931 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4720) Bill To            :
Cash N Carry - Meerut Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_76000070919720240410030103PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 6300452936 PURCHASE ORDER NO.
: 04.04.2024 ORDER DATE
: 18.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#16518
#HIMALAYA BODY LOTION
COCOA BUTTER 200ml
#330499
#89011385081421 CS24EA/1CS 170.00/EA 2835.25 2835.25 IN: CGST(9%) - 255.17
IN: SGST(9%) - 255.17
IN: GST Comp.
CESS(0.00%) - 0.003345.59
2#16520
#HIMALAYA SKIN CREAM
NOURISHING 50ml
#330491
#8901138506
#89011385063771 CS30EA/1CS 85.00/EA 1772.03 1772.03 IN: CGST(9%) - 159.48
IN: SGST(9%) - 159.48
IN: GST Comp.
CESS(0.00%) - 0.002090.99
3#23284
#HIMALAYA SKIN
CREAMNOURISHING 100ml
#330499
#89011388352791 CS18EA/1CS 150.00/EA 1876.27 1876.27 IN: CGST(9%) - 168.86
IN: SGST(9%) - 168.86
IN: GST Comp.
CESS(0.00%) - 0.002213.99
4#29907
#HIMALAYA CREAM COCOA
BUTTER 200 ml
#330499
#89011388374021 CS12EA/1CS 270.00/EA 2251.53 2251.53 IN: CGST(9%) - 202.64
IN: SGST(9%) - 202.64
IN: GST Comp.
CESS(0.00%) - 0.002656.81
8735.08 Total cost without tax
1572.30 Total tax amount
[(INR)  TEN THOUSAND THREE HUNDRED SEVEN AND PAISE THIRTY EIGHT Only]10,307.38 Total PO AMOUNT including Taxes (INR)
: 04.04.2024 PO Order Dt : 6300452936 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4720) Bill To             :
Cash N Carry - Meerut Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 04.04.2024 PO Order Dt : 6300452936 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4720) Bill To            :
Cash N Carry - Meerut Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 3
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741599_52000070919720240410030427PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 6300453055 PURCHASE ORDER NO.
: 04.04.2024 ORDER DATE
: 18.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4720)
Cash N Carry - Meerut
VILLAGE - NAGLA, TEHSIL KASAMPUR,
KHATA NO 344, KHASRA NO.165
MEERUT-250001,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#38963
#HIMALAYA PURIFYING
TULSI HANDWASH 750 ml
#330499
#89011388447381 CS12EA/1CS 115.00/EA 959.04 959.04IN: CGST(9%) - 86.31
IN: SGST(9%) - 86.31
IN: GST Comp.
CESS(0.00%) - 0.001131.66
959.04 Total cost without tax
172.62 Total tax amount
[(INR)  ONE THOUSAND ONE HUNDRED THIRTY ONE AND PAISE SIXTY SIX Only]1,131.66 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 04.04.2024 PO Order Dt : 6300453055 PO No
: 18.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4720) Bill To            :
Cash N Carry - Meerut Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741599_84000070919720240410030402PM.pdf

___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 3
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801391690 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4797)
Cash N Carry - Agra - 2
SITE-A, SIKANDRA
PLOT NO A/1 INDUSTRIAL AREA,
AGRA-282007,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4797)
Cash N Carry - Agra - 2
SITE-A, SIKANDRA
PLOT NO A/1 INDUSTRIAL AREA,
AGRA-282007,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#14897
#HIMALAYA FACE WASH
NEEM 12 U X 15 ml
#340130
#89011385136271 CS15EA/1CS 15.00/EA 1876.27 1876.27 IN: CGST(9%) - 168.86
IN: SGST(9%) - 168.86
IN: GST Comp.
CESS(0.00%) - 0.002213.99
2#14898
#HIMALAYA FACE WASH
NEEM 50 ml
#330499
#8901138512
#89011385121871 CS72EA/1CS 80.00/EA 4002.71 4002.71 IN: CGST(9%) - 360.24
IN: SGST(9%) - 360.24
IN: GST Comp.
CESS(0.00%) - 0.004723.19
3#15665
#HIMALAYA FACEWASH
NEEM 150 ml
#330499
#8901138815
#89011388154311 CS24EA/1CS 225.00/EA 3752.64 3752.64 IN: CGST(9%) - 337.74
IN: SGST(9%) - 337.74
IN: GST Comp.
CESS(0.00%) - 0.004428.12
4#15443
#HIMALAYA COMPLETE
CARE TOOTHPASTE 150 g
#330610
#8901138826
#89011388361082 CS36EA/1CS 90.00/EA 2251.52 4503.04 IN: CGST(9%) - 405.27
IN: SGST(9%) - 405.27
IN: GST Comp.
CESS(0.00%) - 0.005313.58
14134.66 Total cost without tax
2544.22 Total tax amount
[(INR)  SIXTEEN THOUSAND SIX HUNDRED SEVENTY EIGHT AND PAISE EIGHTY EIGHT Only]16,678.88 Total PO AMOUNT including Taxes (INR)
: 08.04.2024 PO Order Dt : 7801391690 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4797) Bill To             :
Cash N Carry - Agra - 2 Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 3Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801391690 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4797) Bill To            :
Cash N Carry - Agra - 2 Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 3 of 3
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741962_23000071112020240410031001PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801391691 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4797)
Cash N Carry - Agra - 2
SITE-A, SIKANDRA
PLOT NO A/1 INDUSTRIAL AREA,
AGRA-282007,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4797)
Cash N Carry - Agra - 2
SITE-A, SIKANDRA
PLOT NO A/1 INDUSTRIAL AREA,
AGRA-282007,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#20581
#HIMALAYA BABY
SHAMPOO GENTLE 200ml
#330590
#8901138511
#89011385114561 CS25EA/1CS 205.00/EA 2823.00 2823.00 IN: CGST(9%) - 254.07
IN: SGST(9%) - 254.07
IN: GST Comp.
CESS(0.00%) - 0.003331.14
2823.00 Total cost without tax
508.14 Total tax amount
[(INR)  THREE THOUSAND THREE HUNDRED THIRTY ONE AND PAISE FOURTEEN Only]3,331.14 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801391691 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4797) Bill To            :
Cash N Carry - Agra - 2 Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your
invoice or making payment to you whichever is earlier, TCS u/s 206C(1H) of the Act is not applicable. Hence, if invoices
raised by you on or after July 01, 2021 contain TCS u/s 206C(1H), we will not pay the same.
.
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712742082_84000071112020240410031109PM.pdf
___________________________________________________________________________________
PDF Version: 1.6
Page 1 of 2
TO / SHIP FROM:
THE HIMALAYA DRUG COMPANY
95, Anand Industrial Estate , Branch :
10 , Anand Industrial Estate , Mohan N
Ghaziabad,Uttar Pradesh,201007,India
09AADFT3025B1ZN GSTIN                            :
2005490902 Supplier No.                   :
080-67549336 Telephone No.               :
Contact Person              :
: 7801391689 PURCHASE ORDER NO.
: 08.04.2024 ORDER DATE
: 22.04.2024 PO CANCEL DATE
PAYMENT TERMS : As per TOT
E-Invoice Applicable on Vendor as per GST LawPURCHASE ORDER
BILL TO:
Wal-Mart India Pvt. Ltd. (4797)
Cash N Carry - Agra - 2
SITE-A, SIKANDRA
PLOT NO A/1 INDUSTRIAL AREA,
AGRA-282007,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
SHIP TO:
Wal-Mart India Pvt. Ltd. (4797)
Cash N Carry - Agra - 2
SITE-A, SIKANDRA
PLOT NO A/1 INDUSTRIAL AREA,
AGRA-282007,India
Place of Supply : Uttar Pradesh
09AADCB2110L1ZY GSTIN NO  :
Please quote Purchase order number on Invoice and all correspondence. Please ensure you follow the 'Wal-Mart India
Pvt. Ltd.' store supply guidelines.
Vendor Partner needs to ensure resolving any mismatch for "HSN Code , Tax rate , Ship to and Bill to Location ", before
delivery of  goods at Walmart location else the invoice cannot be processed .

Sr.No#Article
#Article Description
#HSN
#Vendor Stock
#EAN
Quantity
Ordered
UOM
Pack
MRP
Cost
Line Cost
Excl Tax
Tax DetailsTotal
Amount
(Incl.
Taxes)
1#20133
#HIMALAYA FACE WASH
PURFYING NEEM2X150ml
#340130
#89011388231152 CS12EA/1CS 450.00/EA 3752.54 7505.08 IN: CGST(9%) - 675.46
IN: SGST(9%) - 675.46
IN: GST Comp.
CESS(0.00%) - 0.008856.00
2#38963
#HIMALAYA PURIFYING
TULSI HANDWASH 750 ml
#330499
#89011388447381 CS12EA/1CS 115.00/EA 959.04 959.04IN: CGST(9%) - 86.31
IN: SGST(9%) - 86.31
IN: GST Comp.
CESS(0.00%) - 0.001131.66
3#38966
#HIMALAYA TULSI & LEMON
HANDWASH 750ml
#330499
#89011388447524 CS12EA/1CS 115.00/EA 959.04 3836.16 IN: CGST(9%) - 345.25
IN: SGST(9%) - 345.25
IN: GST Comp.
CESS(0.00%) - 0.004526.66
12300.28 Total cost without tax
2214.04 Total tax amount
[(INR)  FOURTEEN THOUSAND FIVE HUNDRED FOURTEEN AND PAISE THIRTY TWO Only]14,514.32 Total PO AMOUNT including Taxes (INR)
Shipping Instruction    :
Dispatch Mode     :
* Computer/System generated purchase order and does not require any signature
: 08.04.2024 PO Order Dt : 7801391689 PO No
: 22.04.2024 PO cancel Dt
Wal-Mart India Pvt. Ltd. (4797) Bill To            :
Cash N Carry - Agra - 2 Ship To               :
2005490902 Vendor No          :
THE HIMALAYA DRUG
COMPANYVendor Name     :
Page 2 of 2
Wal-Mart India Pvt. Ltd.
 Regd. Office : E-20,1st and 2nd Floor,Hauz Khas Main Market,New Delhi # 110016,India
 Home Office : 4TH FLOOR ORCHID CENTER, SECTOR 53,GURGAON # 122002,India
OTHER TERMS AND CONDITIONS
 1. The Purchase order (“PO”) is subject to the terms and conditions agreed in the supplier agreement. In case of any
deviation between the terms of the PO and the  supplier agreement, the supplier agreement shall supersede the PO.
 2. All Invoices should have reference of the PO” against which supply has been carried out.
 3. Please mention your GSTN, Service Tax number and PAN on each invoice
 4. Check all details mentioned in the PO especially HSN, ship point and applicable tax before dispatch of the goods. In case
of any deviation, the Supplier should get the  same rectified before dispatch.
 5. Payment would be done basis PO cost or invoice cost, whichever is lower.
 6. The Supplier must deliver the goods to the shipping address on or before Cancel Date mentioned in the PO. Time is of
the essence for delivery.
 7. Supply should be done along with original invoice and one additional copy. Please note that incomplete invoices can be
rejected.
 8. All supplies should be accompanied with all statutory documentation, without which deliveries will be rejected. In such
cases, the Supplier shall re-deliver the goods at   the sole cost of the Supplier.
 9. Every invoice should contain supplies from single PO only. One PO can be served in multiple invoices.
 10. Suppliers shall schedule appointment for delivery of goods at the shipping address in advance. Deliveries without prior
appointment can be subject to rejection/delay/detention
 11. The payment for goods rejected during inspection/receiving will not be made and the same will be returned by Wal-Mart
India Private Limited (“WMIPL”) at your risk and cost.
 12. You shall register and keep in force all applicable statutory compliances/registrations (such as GSTN / Sales tax/ VAT,
Excise Duty, Service Tax etc.) as relevant from  time to time for carrying out the business, mentioned in this PO as the
case may be.
 13. The Supplier may make deliveries of goods by installments or deliver part of the goods mentioned in PO only with the
express written approval of WMIPL, prior to delivery.
 14. If the Goods are advertised or promotional merchandise and not delivered to WMIPL at the shipping address by the
Delivery Date then without limitation to any other rights or remedies WMIPL has the right without notice to make
replacement  purchases of such Goods at the Supplier's sole expense.
 15. Without limitation to any other rights or remedies available with WMIPL, the Supplier shall compensate WMIPL if it fails to
deliver all of the Goods in accordance with the PO at the shipping address by the Delivery Date (which shall include
without limitation any and all consequential or indirect losses and loss of profits).
 16. TDS shall be deductible as per the relevant statutes of the Income Tax Act, 1961 and rules framed there under from time
to time.
 17. In case any credit, refund or other benefit is denied or delayed to Walmart due to any non-compliance with respect to E-
invoicing by Vendor, Vendor shall reimburse to Company, the loss including, but not limited to,the input tax credit loss,
interest and penalty. In addition to the aforesaid, Walmart shall be entitled  to set off any loss including, but not limited
to,the input tax credit loss, interest and penalty that it may incur due to Vendor's GST non-compliance from any amount
payable to the Vendor.
 18. All disputes arising out of this PO shall be subject to jurisdiction of courts in New Delhi.
 19. Since we would be ensuring compliance with Section 194Q of the Income Tax Act, 1961 (the Act) while processing your

In [18]:
import re
from PyPDF2 import PdfReader
import os

pdfs_dir = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats"


def detect_pdf_version(pdf_path):
    with open(pdf_path, 'rb') as file:
        file_header = file.read(1024)

        version_match = re.search(rb"%PDF-(\d\.\d)", file_header)

        if version_match:
            pdf_version = version_match.group(1).decode()
            return pdf_version
        else:
            return "Unknown"


def extract_from_pdf(pdf_path):
    try:
        pdf_read = PdfReader(pdf_path)
        text = '\n'.join([page.extract_text() for page in pdf_read.pages])
        print(pdf_path)
#         print(text[:100])
        if not text:
            print("!!!!!!!\n\nNo data found\n\n!!!!!!")
        return text
    except Exception as e:
        print(f"Error processing {pdf_path}: {e}")
pdf_v_dicts = {'1.0':0, '1.1':0, '1.2':0, '1.3':0, '1.4':0, '1.5':0, '1.6':0, '1.7':0, "Unknown":0 }
all_found = 0
all_not_found = 0
for folder in os.listdir(pdfs_dir):
    data_found = 0
    not_found = 0
    directory_path = os.path.join(pdfs_dir, folder)
#     print("\n", directory_path)

    for pdf in os.listdir(directory_path):
        if pdf.lower().endswith("pdf"):
            pdf_path = os.path.join(directory_path, pdf)
            version = detect_pdf_version(pdf_path)
            print(f"\n\nPDF Version:{version}___________________________________________________________")
            text = extract_from_pdf(pdf_path)
            
            if text:
                data_found+=1
                pdf_v_dicts[version]+=1
            else:
                not_found += 1
    all_found += data_found
    all_not_found += not_found
    print(f"Total PDFs in {folder}: {len(os.listdir(directory_path))}")
    print(f"Total data extracted found: {data_found} and not found: {not_found}")
    print("###############################################################################################################################################################################################################################################################################################################################################")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("Data Found", all_found)
print("Data Not Found", all_not_found)
print(pdf_v_dicts)

PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_06_22_02_14_03_PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_06_25_11_44_16_AM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_06_29_03_23_08_PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_07_06_12_16_48_PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_07_13_11_44_44_AM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\1545711589620_1_0000707320_2018_12_25_09_48_35_AM.pdf
Total PDFs in Aditya: 6
Total data extracted found: 6 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276269826284184.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276270138159286.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276270440660100.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276270876911265.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276271176599639.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276272219721636.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276272573175595.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276273527685560.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276274134676406.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276274457645956.pdf
Total PDFs in Apollo: 10
Total data extracted found: 10 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1582693640233_1_0000721831_2020_02_26_10_35_47_AM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732435_85000072118820240410123151PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732436_22000071748720240410123131PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732436_43000071748720240410123117PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732557_73000072118820240410123210PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712734729_38000071511320240410011018PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712734729_6000071511320240410010933PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712734850_13000073169620240410011204PM.pdf
!!!!!!!

No data found

!!!!!!


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712734850_28000073203020240410011137PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712735455_64000073169620240410012107PM.pdf
!!!!!!!

No data found

!!!!!!


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712735937_41000072579020240410012842PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712736059_67000072579020240410013030PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712736180_16000072243820240410013354PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_02000072857320240410023206PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_2000072857320240410023147PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_37000072857320240410023124PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739670_54000072857320240410023105PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712739791_08000072857320240410023413PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712740272_87000072874220240410024113PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712743166_08000073241420240410033032PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712743166_31000073241420240410033015PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712743166_55000073241420240410032959PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712743166_76000072874220240410032921PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712745333_75000072337220240410040626PM.pdf


PDF Version:1.7___________________________________________________________

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712750748_28000072373920240410053608PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637511386383630680.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637511424018065542.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637511577726599357.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637511578859350907.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637514850368847470.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637515093437838850.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637515917044811228.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637520904875680873.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637526152673937634.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637536608297402648.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-700574-637581703685500816.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637500333928797475.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637508880999132200.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637508881361023338.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637508881760946527.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637511658932004915.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637511663135162510.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637514387980399574.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637514801622948962.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637514802176663254.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637514843672110025.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637515125918965560.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637517476751078434.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637535031453670189.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637910886296937485.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701489-637910886674306165.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637499384375117957.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637508843573575247.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637516853242431611.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637522693294795291.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637552048042073949.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637806124972423192.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637859009160538999.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637910675703076374.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637910677076807255.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637910729741631377.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637910789576466177.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637911510965298811.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637913214625802769.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-701686-637913260387166167.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637461347520753879.pdf
!!!!!!!

No data found

!!!!!!


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637467611908542946.pdf
!!!!!!!

No data found

!!!!!!


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637476257086291678.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637496855413315295.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637496856152008988.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637496857788024637.pdf

PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637496872081088397.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637496952029944468.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637497684423809190.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637497831289675519.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637498517143151469.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637498714495535986.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637499514652301426.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637503009082777438.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637503858372734011.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637504778717906414.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637505600022390925.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703557-637509080759494492.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637499797932888908.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637499798592621426.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637499800306468189.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637499805440731119.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637507475639065995.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637507564333957469.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637507573157881036.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637507576066617343.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512518657711236.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512524488735389.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512525446748022.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512526989718029.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512529487401326.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512532846364364.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512540511142394.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-703558-637512583645089973.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637506273606008958.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637506274093993136.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637508042951078933.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637517815639652287.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637538170511588086.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637538205363983676.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637916195707704961.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637916196353240567.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716824-637916197332355760.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-716825-637530501095931758.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637497726947159935.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637497727254189834.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637497727648551346.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637497734960588239.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637497738092645874.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637499415136930716.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637499415605894912.pdf

PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637500212287586835.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637504573080763900.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637504790138172301.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637505528235743178.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637505532461918231.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637505543388100249.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637506266156202291.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637506269870317333.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637508013129485847.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637508014947730772.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637509832439172892.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637514903665213601.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637514965566330767.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637516703394780617.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637516719756357869.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637517612035633994.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637518346685585291.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637523747972929176.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637527074830254984.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637533962013464064.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637539113557869582.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637587451017025046.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-637953030375168503.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-638041958462864901.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-638247734552415187.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-638252279579115950.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-718576-638252279957504465.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637711005133402599.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637711006364647831.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637712082776712527.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637712083270523685.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637712084214674282.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637715561826134325.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637717878784484191.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637723925213921148.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637730024385680493.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637734476571787537.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637734481357435801.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637811523052676932.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719018-637811523443370743.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719855-637506582526496146.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719855-637526554042183520.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719855-637536000486785480.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719855-638194888527872550.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-719855-638246775479483880.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503874422611546.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503875469837690.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503877243397490.pdf


PDF Version:1.4___________________________________________________________

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503879131023149.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503890009911366.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503890608839345.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503899687591645.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-720910-637503918720455172.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638041947484600930.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638041956759124766.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638041961117060912.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638041963660009842.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638041965964407228.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638067076139065300.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638158680874712839.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638158684971555107.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638158686427732119.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\MTPO-723781-638158687237635937.pdf
Total PDFs in AvenueSupermarts: 179
Total data extracted found: 175 and not found: 4
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1582693400232_1_0000717697_2020_02_26_10_31_13_AM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712732194_47000072817120240410122738PM.pdf


PDF Version:1.7___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712734005_25000071046420240410125809PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712735334_83000072817020240410011940PM.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712736421_01000072920220240410013724PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712741356_61000072927220240410030001PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712748582_35000072800220240410045921PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712749304_24000073128920240410051146PM.pdf
Total PDFs in FirstCry: 8
Total data extracted found: 8 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_35000072315120240410024021PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_57000072309820240410075541PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_82000072309820240410075513PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_99000072309820240410075459PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759056_15000072309820240410075444PM.pdf
Total PDFs in Max: 6
Total data extracted found: 6 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732315_17000073207120240410122851PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_05000073253120240410123141PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_76000073220420240410123058PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_96000073253920240410123012PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732557_54000073253720240410123226PM.PDF


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712741235_5000070644720240410025834PM.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712741235_71000071164920240410025804PM.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712741235_85000070644720240410025744PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712752432_81000073212320240410060440PM.PDF
Total PDFs in Metro: 10
Total data extracted found: 9 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\0000704865_2019_06_12_03_59_19_PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\0000704865_2019_06_14_01_09_28_PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712734971_63000072226420240410011224PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735092_12000072524520240410011600PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735092_84000072524520240410011454PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735213_33000072591220240410011808PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712735213_54000072226420240410011725PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\More\1712736662_18000072748420240410014123PM.pdf
Total PDFs in More: 8
Total data extracted found: 8 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.4___________________________________________________________

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\OPTIVAL\1712732436_57000071057820240410123117PM.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\OPTIVAL\1712735335_04000071057820240410011846PM.pdf
Total PDFs in OPTIVAL: 2
Total data extracted found: 2 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\PNB\0000704860_2023_05_22_09_40_08_AM.pdf


PDF Version:1.4___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\PNB\0000704860_2023_05_22_11_03_02_AM.pdf
Total PDFs in PNB: 2
Total data extracted found: 2 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\0000704860_2023_06_14_01_00_01_PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\0000704860_2023_06_14_12_30_49_PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\0000704860_2023_06_14_12_47_34_PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1582693520229_1_0000711842_2020_02_26_10_34_57_AM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733160_89000070492820240410124410PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733161_1000073219620240410124401PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733161_35000073219620240410124346PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733281_93000073028220240410124518PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733282_2000073219620240410124428PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733282_47000073219620240410124413PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733403_08000073028220240410124702PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712733403_3000070492820240410124617PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734005_05000072717520240410125810PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734005_44000072717520240410125740PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734005_69000072717520240410125714PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734126_26000073071420240410125949PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734126_46000072717520240410125833PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734247_03000073071420240410010024PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734367_59000072551020240410010410PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734367_76000073071420240410010238PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734488_23000072551020240410010505PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734488_4000072551020240410010447PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734488_57000072551020240410010428PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712734970_84000073071420240410011415PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712735455_81000072226920240410012113PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712735455_98000072226920240410012031PM.pdf


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712736661_93000070494020240410014207PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712741236_03000073013220240410025722PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712748581_95000072539320240410050048PM.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712748582_17000072539320240410050033PM.pdf


PDF Version:1.5___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Reliance\1712752433_07000073223920240410060438PM.pdf
Total PDFs in Reliance: 31
Total data extracted found: 31 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\SampleandBlank\0000704860_2023_05_23_03_18_06_PM.pdf
!!!!!!!

No data found

!!!!!!


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\SampleandBlank\0000704860_2023_05_23_04_03_01_PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\SampleandBlank\0000704860_2023_05_25_04_38_14_PM.pdf
!!!!!!!

No data found

!!!!!!
Total PDFs in SampleandBlank: 3
Total data extracted found: 1 and not found: 2
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Vishal\MTPO-719018-637476241752854111.PDF


PDF Version:1.3___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Vishal\MTPO-719018-637535840943261295.PDF
Total PDFs in Vishal: 2
Total data extracted found: 2 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733039_24000070938720240410124200PM.PDF


PDF Version:1.6___________________________________________________________

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733039_84000070938720240410124139PM.PDF


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712734971_01000070919420240410011351PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712735092_29000071992120240410011511PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712735213_7000072494220240410011641PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736057_93000070920420240410013210PM.PDF


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736058_64000070920420240410013158PM.PDF


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712736059_11000070920420240410013148PM.PDF


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_08000070919720240410030249PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_45000070919720240410030227PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741477_75000070919720240410030205PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_18000070919720240410030144PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_47000070919720240410030124PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741478_76000070919720240410030103PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741599_52000070919720240410030427PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741599_84000070919720240410030402PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741600_13000070919720240410030333PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741600_45000070919720240410030310PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741961_76000071112020240410031042PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712741962_23000071112020240410031001PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712742082_84000071112020240410031109PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712744009_12000071112020240410034418PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712744490_73000070919720240410035155PM.pdf


PDF Version:1.6___________________________________________________________
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712744491_27000070919720240410035135PM.pdf
Total PDFs in Walmart: 25
Total data extracted found: 25 and not found: 0
###############################################################################################################################################################################################################################################################################################################################################
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Data Found 285
Data Not Found 6
{'1.0': 0, '1.1': 0, '1.2': 0, '1.3': 77, '1.4': 51, '1.5': 12, '1.6': 31, '1.7': 114, 'Unknown': 0}

In [60]:
all_found + all_not_found

295

In [62]:
import camelot

path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"
tables = camelot.read_pdf(path, pages='all')
tables

In [39]:
import os
import camelot

text = ''

def read_pdf(pdf_path):
    global text
    tables = camelot.read_pdf(pdf_path, flavor='lattice')
    for table in tables:
        table_string = table.df.to_string(index=False, header=False)
        text += table_string + '\n'
        # Alternatively, you can directly add the string representation of the table
        # text += '\n'.join(['\t'.join(map(str, row)) for row in table.data]) + '\n'

pdfs_folder = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart"

# for file in os.listdir(pdfs_folder):
#     if file.endswith('.pdf'):
#         pdf_path = os.path.join(pdfs_folder, file)
#         try:
#             read_pdf(pdf_path)
#         except Exception as e:
#             print(f"Error processing {file} at {pdf_path}: {e}")
#         break  
        
read_pdf(r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf")

text

"                                                          SKU Code\\nSKU Desc                EAN\\nHSN  AR Qty MRP Unit  \\nCost Disc %             Tax-Rate%-TaxAmt Total Value\n                                    100041077\\nHIMALAYA FAIRNESS \\nCREAM 50G 8901138836146\\n33049910 REG   6 100        67.37          CGST-9%-6.06\\nSGST-9%-6.06         477\n                       100043179\\nHIMALAYA PURIFYING\\nNEEM FACE WASH 50 \\nML 8901138512187\\n33049990 REG  36  80         53.9          SGST-9%-4.85\\nCGST-9%-4.85      2289.6\n                       100043181\\nHIMALAYA PURIFYING\\nNEEM FACE WASH 100\\nML 8901138512460\\n33049990 PSS  24 150       101.06            SGST-9%-9.1\\nCGST-9%-9.1        2862\n                        100043219\\nHIMALAYA NEEM \\nFOAMING FACE WASH \\n150ML 8901138512811\\n33049990 REG   6 275       185.28        SGST-9%-16.67\\nCGST-9%-16.67     1311.75\n                             100043661\\nHIMALAYA PURIFYING\\nNEEM SCRUB 100ML 8901138821920\\n33049990 REG  12 160        107.8            CGST-9%-9.7\\nSGST-9%-9.7      1526.4\n               103656221\\nHIMALAYA MEN POWER\\nGLOW LICORICE FACE\\nWASH 100ML 8901138831073\\n33049990 REG   6 189       127.33        CGST-9%-11.46\\nSGST-9%-11.46      901.53\n             115400549\\nHIMALAYA MEN'S \\nPIMPLE CLEAR NEEM \\nFACE WASH 100ML 8901138835330\\n33049990 REG   6 189       127.33        CGST-9%-11.46\\nSGST-9%-11.46      901.53\n                       115400581\\nHIMALAYA OIL CLEAR\\nMUD FACE PACK 50 \\nGMS 8901138821968\\n33049990 REG  30  85        57.27          SGST-9%-5.15\\nCGST-9%-5.15     2027.25\n                 115400725\\nHIMALAYA \\nPROTECTIVE \\nSUNSCREEN LOTION \\n100ML 8901138511104\\n33049930 REG  12 220       148.22        CGST-9%-13.34\\nSGST-9%-13.34      2098.8\n              120853981\\nHIMALAYA \\nMOISTURIZING \\nALOEVERA FACE WASH\\n200ML 8901138836450\\n33049990 REG  12 235       158.33        SGST-9%-14.25\\nCGST-9%-14.25      2241.9\n                  122727785\\nHIMALAYA TAN \\nREMOVAL ORANGE \\nFACE WASH 100ML 8901138837044\\n33049990 REG  12 180       121.27        SGST-9%-10.91\\nCGST-9%-10.91      1717.2\n             122728227\\nHIMALAYA \\nREFRESHING AND \\nCLARIFYING TONER \\n100ML 8901138510329\\n33049990 REG  12 110        74.11          SGST-9%-6.67\\nCGST-9%-6.67      1049.4\n128640525\\nHIMALAYA FRESH \\nSTART - OIL CLEAR \\nSTRAWBERRY FACE \\nWASH 100ML 8901138839659\\n33049990 REG  12 160        107.8            SGST-9%-9.7\\nCGST-9%-9.7      1526.4\n 128640568\\nHIMALAYA FRESH \\nSTART - OIL CLEAR \\nBLUEBERRY FACE \\nWASH 100ML 8901138839680\\n33049990 REG  12 160        107.8            CGST-9%-9.7\\nSGST-9%-9.7      1526.4\n"

In [1]:
import camelot
import pandas as pd

path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Walmart\1712733040_29000070938720240410124104PM.PDF"
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf"
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Aditya\0000704866_2018_07_13_11_44_44_AM.pdf" #dont
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Apollo\MTPO-731157-638276274134676406.pdf"
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\AvenueSupermarts\1712732435_85000072118820240410123151PM.pdf" #not recognized
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\FirstCry\1712748582_35000072800220240410045921PM.pdf"
path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Metro\1712732436_96000073253920240410123012PM.PDF"

tables = camelot.read_pdf(path, pages='all')
df = pd.DataFrame()
if tables:
    df = pd.concat([table.df for table in tables])
df

,0,1,2,3,4,5,6,7,8,9,10
0,Vendor Code : 25016840\n Himalaya Wellness C...,,PO NO.: 5103790879 Site : T2OZ\n PO Date...,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Pin Code : 452010, India\n E-Mail : reshma...",,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STORE BHIND\n In accepting this PURCHASE OR...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Delivery Address : \n Central Warehouse, God...",,"TOTAL BASIC VALUE\n INR\n51,624.74\n TOTAL...",,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"INR\n60,917.20\n Total Order Value :",,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,DELIVERY DATE : 15.04.2024\n Delivery Term ...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,.,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Buyer : Himani Kamble\n Phone : 8104979676\...,For STORE BHIND\n Metro Cash & Carry India P...,,SELLER'S Acceptence\nSignature Title ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Sr.No Article No.,HSN Code,EAN No.\n Vendor Article No.\n Vendor Item No,Material Description\n Delivery Date\n Site,Quantity,UOM,MRP,Base Cost,CGST (%)\nSGST(%)\nCESS(%),CGST\nSGST\nCESS,Total Base Value
1,1,490003400\n 33051090,8901138511449,HIMALAYA GENTLE BABY SHAMPOO 100 ML\nBTL\n 15....,2.000 \n 72.000,C07\nEA,"3,780.00 \n 105.00","2,338.47",9.00 \n 9.00 \n 0.00,420.93\n420.93\n0.00,"4,676.95"
2,2,490003401\n 33049930,8901138511739,HIMALAYA BABY MASSAGE OIL 100 ML BTL\n 15.04.2...,1.000 \n 48.000,C07\nEA,"6,240.00 \n 130.00","3,860.34",9.00 \n 9.00 \n 0.00,347.43\n347.43\n0.00,"3,860.34"
3,3,490003407\n 33049120,8901138511814,HIMALAYA BABY POWDER 100 G BTL\n 15.04.2024\n ...,2.000 \n 72.000,C07\nEA,"3,780.00 \n 105.00","2,338.47",9.00 \n 9.00 \n 0.00,420.93\n420.93\n0.00,"4,676.95"
4,4,490003412\n 33049930,8901138512187,HIMALAYA PURFYNG NEEM FACEWASH 50ML\nTUBE\n 15...,2.000 \n 144.000,C24\nEA,"5,760.00 \n 80.00","4,002.71",9.00 \n 9.00 \n 0.00,720.49\n720.49\n0.00,"8,005.42"
5,5,490003413\n 33049990,8901138512460,HIMALAYA PURFYG NEEM FACEWASH 100ML\nTUBE\n 15...,1.000 \n 48.000,C25\nEA,"7,200.00 \n 150.00","5,003.39",9.00 \n 9.00 \n 0.00,450.31\n450.31\n0.00,"5,003.39"
6,6,490782404\n 33051090,8901138511456,HIMALAYA GNTL BBY SHMP(HIB&CHK)200ML\nPET\n 15...,1.000 \n 25.000,C07\nEA,"5,125.00 \n 205.00","3,170.55",9.00 \n 9.00 \n 0.00,285.35\n285.35\n0.00,"3,170.55"
7,7,490782406\n 34011110,8901138512606,HIMALAYA GENTLE BABY SOAP 125 G CBD\n 15.04.20...,1.000 \n 60.000,C07\nEA,"5,400.00 \n 90.00","3,340.68",9.00 \n 9.00 \n 0.00,300.66\n300.66\n0.00,"3,340.68"
8,8,490782407\n 33049120,8901138513153,HIMALAYA BABY POWDER 200 G BTL\n 15.04.2024\n ...,1.000 \n 24.000,C07\nEA,"4,680.00 \n 195.00","2,895.25",9.00 \n 9.00 \n 0.00,260.57\n260.57\n0.00,"2,895.25"
9,9,490782408\n 33049930,8901138511494,HIMALAYA BBY CRM EX SFT & GTL 100ML\nTUBE\n 15...,1.000 \n 48.000,C07\nEA,"8,400.00 \n 175.00","5,196.61",9.00 \n 9.00 \n 0.00,467.69\n467.69\n0.00,"5,196.61"
0,Sr.No Article No.,HSN Code,EAN No.\n Vendor Article No.\n Vendor Item No,Material Description\n Delivery Date\n Site,Quantity,UOM,MRP,Base Cost,CGST (%)\nSGST(%)\nCESS(%),CGST\nSGST\nCESS,Total Base Value
1,10,490896773\n 33079090,8901138513184,HIMALAYA GENTLE BABY WIPES 72 PCS PP\n 15.04.2...,1.000 \n 24.000,C07\nEA,"4,800.00 \n 200.00","2,969.49",9.00 \n 9.00 \n 0.00,267.25\n267.25\n0.00,"2,969.49"
2,11,491238726\n 33049930,8901138511470,HIMALAYA BABY LOTION 200 ML BTL\n 15.04.2024\n...,1.000 \n 25.000,C06\nEA,"4,875.00 \n 195.00","3,015.89",9.00 \n 9.00 \n 0.00,271.43\n271.43\n0.00,"3,015.89"
3,12,491598912\n 34013090,8901138844752,HIM PR HANDS TLS&LMN DC HW RFL 750ML\nPCH\n 15...,2.000 \n 24.000,CAR\nEA,"1,380.00 \n 115.00",958.98,9.00 \n 9.00 \n 0.00,172.62\n172.62\n0.00,"1,917.97"
4,13,491631825\n 34011110,8901138511838,HIMALAYA GENTLE BABY SOAP 75G CBD\n 15.04.2024...,1.000 \n 72.000,CAR\nEA,"4,680.00 \n 65.00","2,895.25",9.00 \n 9.00 \n 0.00,260.57\n260.57\n0.00,"2,895.25"
5,Grand Total of Qty,,,,17.000,,,,,,
6,,,,,TOTAL BASIC VALUE,,,,,INR,"51,624.74"
7,,,,,TOTAL CGST,,,,,INR,"4,646.23"
8,,,,,TOTAL SGST,,,,,INR,"4,646.23"
9,,,,,Total Order Value:,,,,,INR,"60,917.20"
0,Site,Site Name,Address,GSTN No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,T2OZ,STORE BHIND,"Metro Cash & Carry India Priva,Central Warehou...",23AACCM4684P1ZZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN

                                                   0
0  Himalaya Baby Cream\nCGST - 9%\n161.13\n1\n330...
1  Himalaya Baby Cream\nCGST - 9%\n287.94\n2\n330...
2  Himalaya Baby Gift\nCGST - 9%\n129.89\n3\n3304...
3  Himalaya For Moms\nCGST - 9%\n427.61\n4\n33049...
4  Himalaya for\nCGST - 6%\n158.83\n5\n30049011\n...
5  Himalaya Gentle Baby\nCGST - 6%\n100.29\n6\n96...
6  HimalayaBaby Wash\nCGST - 9%\n535.44\n7\n34013...