In [1]:
import re
from PyPDF2 import PdfReader
import os
import pandas as pd

pdf_path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf"
pdf_read = PdfReader(pdf_path)
text = '\n'.join([page.extract_text() for page in pdf_read.pages])
pattern = r"(\d+)\n(HIM.+?)(\d{13})\n(\d+)\s*\n(\w{0,3})\s*(\d+)\s*(\d+)\s*(\d+\.\d+)(\w+)-(\d+)%-(\d+\.\d+)\n(\w+)-(\d+)%-(\d+\.\d{2})(\d+\.?\d*)"
rows = re.findall(pattern, text, re.DOTALL)
new_rows = []
for match in rows:
    match = list(match)
    if match[8]=='CGST':
        temp1 = match[8]
        temp2 = match[9]
        temp3 = match[10]
        match[8] = match[11]
        match[9] = match[12]
        match[10] = match[13]
        match[11] = temp1
        match[12] = temp2
        match[13] = temp3
    new_rows.append(match)
cols = ["SKU Code", "SKU Desc", "EAN", "HSN", "AR", "Qty", "MRP", "Unit Cost", "CGST", "SGST Tax-Rate%", "SGST TaxAmt","SGST", "CGST Tax-Rate%", "CGST TaxAmt", "Total Value"]
df = pd.DataFrame(new_rows, columns=cols)
del df['CGST']
del df['SGST']
print(text)
df

Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
Delivery
Address:MARINA MALL CHN
 MARINA MALL, NO 13/1A
EGATTUR OLD
MAHABALIPURAM,
TIRUPORUR TALUK
KANCHIPURAM DISTRICT
CHENNAI 603106PO No: 11237019 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD
ALAPAKKAM PORUR   CHENNAI 600116
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33AAECM0847J1ZJ PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW
PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100041077
HIMALAYA FAIRNESS
CREAM 50G8901138836146
33049910
REG6 100 67.37CGST-9%-6.06
SGST-9%-6.06477
100043179
HIMALAYA PURIFYING
NEEM FACE WASH 50
ML8901138512187
33049990
REG 36 80 53.9SGST-9%-4.85
CGST-9%-4.852289.6
100043181
HIMALAYA PURIFYING
NEEM FACE WASH 100
ML8901138512460
33049990
PSS 24 150 101.06SGST-9%-9.1
CGST-9%-9.12862
100043219
HIMALAYA NEEM
FOAMING FACE WASH
150ML8901138512811
33049990
REG 6 275 185.28SGST-9%-16.67
CGST-9%-16.671311.75
100043661
HIMALAYA PURIFYING
NEEM SCRUB 100ML8901138821920
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
103656221
HIMALAYA MEN POWER
GLOW LICORICE FACE
WASH 100ML8901138831073
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400549
HIMALAYA MEN'S
PIMPLE CLEAR NEEM
FACE WASH 100ML8901138835330
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400581
HIMALAYA OIL CLEAR
MUD FACE PACK 50
GMS8901138821968
33049990
REG 30 85 57.27SGST-9%-5.15
CGST-9%-5.152027.25
115400725
HIMALAYA
PROTECTIVE
SUNSCREEN LOTION
100ML8901138511104
33049930
REG12 220 148.22CGST-9%-13.34
SGST-9%-13.342098.8
120853981
HIMALAYA
MOISTURIZING
ALOEVERA FACE WASH
200ML8901138836450
33049990
REG12 235 158.33SGST-9%-14.25
CGST-9%-14.252241.9
122727785
HIMALAYA TAN
REMOVAL ORANGE
FACE WASH 100ML8901138837044
33049990
REG 12 180 121.27SGST-9%-10.91
CGST-9%-10.911717.2
122728227
HIMALAYA
REFRESHING AND
CLARIFYING TONER
100ML8901138510329
33049990
REG12 110 74.11SGST-9%-6.67
CGST-9%-6.671049.4
128640525
HIMALAYA FRESH
START - OIL CLEAR
STRAWBERRY FACE
WASH 100ML8901138839659
33049990
REG12 160 107.8SGST-9%-9.7
CGST-9%-9.71526.4
128640568
HIMALAYA FRESH
START - OIL CLEAR
BLUEBERRY FACE
WASH 100ML8901138839680
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
150509435
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 200ML8901138848736
33049990
REG 6 205 138.11SGST-9%-12.43
CGST-9%-12.43977.85
150509451
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 400ML8901138848743
33049990
REG 6 370 249.28CGST-9%-22.44
SGST-9%-22.441764.9
154309377
HIMALAYA NATURAL
GLOW ALOEVERA GEL
100ML8901138848484
33049990
REG 24 85 57.27CGST-9%-5.15
SGST-9%-5.151621.8
154309414
HIMALAYA CLEAR
COMPLEXION
BRIGHTENING
MULETHI SHEET MASK8901138849313
33049990
REG20 75 50.53SGST-9%-4.55
CGST-9%-4.551192.5
154309457
HIMALAYA FRESH
START OIL CLEAR
STRAWBERRY SHEET
MASK8901138849306
33049990
REG20 75 50.53CGST-9%-4.55
SGST-9%-4.551192.5
161614011
HIMALAYA ROSE FACE
WASH 100ML8901138847272
33049990
REG24 160 107.8SGST-9%-9.7
CGST-9%-9.73052.8
161614038
HIMALAYA YOUTH
ETERNITY FACE
SHEET MASK 1N8901138849320
33049990
REG 20 85 57.27CGST-9%-5.15
SGST-9%-5.151351.5
Total:     5127.0972        33,611.01
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature

,SKU Code,SKU Desc,EAN,HSN,AR,Qty,MRP,Unit Cost,SGST Tax-Rate%,SGST TaxAmt,CGST Tax-Rate%,CGST TaxAmt,Total Value
0,100041077,HIMALAYA FAIRNESS \nCREAM 50G,8901138836146,33049910,REG,6,100,67.37,9,6.06,9,6.06,477
1,100043179,HIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML,8901138512187,33049990,REG,36,80,53.9,9,4.85,9,4.85,2289.6
2,100043181,HIMALAYA PURIFYING\nNEEM FACE WASH 100\nML,8901138512460,33049990,PSS,24,150,101.06,9,9.1,9,9.12,862
3,100043219,HIMALAYA NEEM \nFOAMING FACE WASH \n150ML,8901138512811,33049990,REG,6,275,185.28,9,16.67,9,16.67,1311.75
4,100043661,HIMALAYA PURIFYING\nNEEM SCRUB 100ML,8901138821920,33049990,REG,12,160,107.8,9,9.71,9,9.7,526.4
5,103656221,HIMALAYA MEN POWER\nGLOW LICORICE FACE\nWASH 1...,8901138831073,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
6,115400549,HIMALAYA MEN'S \nPIMPLE CLEAR NEEM \nFACE WASH...,8901138835330,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
7,115400581,HIMALAYA OIL CLEAR\nMUD FACE PACK 50 \nGMS,8901138821968,33049990,REG,30,85,57.27,9,5.15,9,5.15,2027.25
8,115400725,HIMALAYA \nPROTECTIVE \nSUNSCREEN LOTION \n100ML,8901138511104,33049930,REG,12,220,148.22,9,13.34,9,13.34,2098.8
9,120853981,HIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n...,8901138836450,33049990,REG,12,235,158.33,9,14.25,9,14.25,2241.9
10,122727785,HIMALAYA TAN \nREMOVAL ORANGE \nFACE WASH 100ML,8901138837044,33049990,REG,12,180,121.27,9,10.91,9,10.91,1717.2
11,122728227,HIMALAYA \nREFRESHING AND \nCLARIFYING TONER \...,8901138510329,33049990,REG,12,110,74.11,9,6.67,9,6.67,1049.4
12,128640525,HIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERR...,8901138839659,33049990,REG,12,160,107.8,9,9.7,9,9.71,526.4
13,128640568,HIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY...,8901138839680,33049990,REG,12,160,107.8,9,9.71,9,9.7,526.4
14,150509435,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848736,33049990,REG,6,205,138.11,9,12.43,9,12.43,977.85
15,150509451,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848743,33049990,REG,6,370,249.28,9,22.44,9,22.44,1764.9
16,154309377,HIMALAYA NATURAL \nGLOW ALOEVERA GEL \n100ML,8901138848484,33049990,REG,24,85,57.27,9,5.15,9,5.15,1621.8
17,154309414,HIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMU...,8901138849313,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.5
18,154309457,HIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY ...,8901138849306,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.5
19,161614011,HIMALAYA ROSE FACE\nWASH 100ML,8901138847272,33049990,REG,24,160,107.8,9,9.7,9,9.73,052.8
20,161614038,HIMALAYA YOUTH \nETERNITY FACE \nSHEET MASK 1N,8901138849320,33049990,REG,20,85,57.27,9,5.15,9,5.15,1351.5

In [1]:
import pandas as pd
from PyPDF2 import PdfReader
import re
import os

def extract_data(pdf_path):
    pdf_read = PdfReader(pdf_path)
    text = '\n'.join([page.extract_text() for page in pdf_read.pages])
    print(text)
    pattern = r"(\d+)\n(HIM.+?)(\d{13})\n(\d+)\s*\n(\w{0,3})\s*(\d+)\s*(\d+)\s*(\d+\.?\d*)(\w+)-(\d+)%-(\d+\.\d+)\n(\w+)-(\d+)%-(\d+\.\d{2})(\d+\.?\d*)"
    rows = re.findall(pattern, text, re.DOTALL)
    new_rows = []
    for match in rows:
        match = list(match)
        if match[8]=='CGST':
            temp1 = match[8]
            temp2 = match[9]
            temp3 = match[10]
            match[8] = match[11]
            match[9] = match[12]
            match[10] = match[13]
            match[11] = temp1
            match[12] = temp2
            match[13] = temp3
        new_rows.append(match)
    cols = ["SKU Code", "SKU Desc", "EAN", "HSN", "AR", "Qty", "MRP", "Unit Cost", "SGST", "SGST Tax-Rate%", "SGST TaxAmt","CGST", "CGST Tax-Rate%", "CGST TaxAmt", "Total Value"]
    df = pd.DataFrame(new_rows, columns=cols)
    del df['CGST']
    del df['SGST']
    
    numerics = ["SKU Code", "EAN", "HSN", "Qty", "MRP", "Unit Cost", "SGST Tax-Rate%", "SGST TaxAmt", "CGST Tax-Rate%", "CGST TaxAmt", "Total Value"]
    for col in numerics:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df
    
directory = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max"
all_dfs = []
for file in os.listdir(directory):
    pdf_path = os.path.join(directory, file)
    print(pdf_path)
    df = extract_data(pdf_path)
    all_dfs.append(df)
#     print(df.to_string())
#     print("____________________________________________________________")
merged_table = pd.concat([table for table in all_dfs], ignore_index=True)
merged_table

C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
Delivery
Address:MARINA MALL CHN
 MARINA MALL, NO 13/1A
EGATTUR OLD
MAHABALIPURAM,
TIRUPORUR TALUK
KANCHIPURAM DISTRICT
CHENNAI 603106PO No: 11237019 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD
ALAPAKKAM PORUR   CHENNAI 600116
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33AAECM0847J1ZJ PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW
PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100041077
HIMALAYA FAIRNESS
CREAM 50G8901138836146
33049910
REG6 100 67.37CGST-9%-6.06
SGST-9%-6.06477
100043179
HIMALAYA PURIFYING
NEEM FACE WASH 50
ML8901138512187
33049990
REG 36 80 53.9SGST-9%-4.85
CGST-9%-4.852289.6
100043181
HIMALAYA PURIFYING
NEEM FACE WASH 100
ML8901138512460
33049990
PSS 24 150 101.06SGST-9%-9.1
CGST-9%-9.12862
100043219
HIMALAYA NEEM
FOAMING FACE WASH
150ML8901138512811
33049990
REG 6 275 185.28SGST-9%-16.67
CGST-9%-16.671311.75
100043661
HIMALAYA PURIFYING
NEEM SCRUB 100ML8901138821920
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
103656221
HIMALAYA MEN POWER
GLOW LICORICE FACE
WASH 100ML8901138831073
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400549
HIMALAYA MEN'S
PIMPLE CLEAR NEEM
FACE WASH 100ML8901138835330
33049990
REG 6 189 127.33CGST-9%-11.46
SGST-9%-11.46901.53
115400581
HIMALAYA OIL CLEAR
MUD FACE PACK 50
GMS8901138821968
33049990
REG 30 85 57.27SGST-9%-5.15
CGST-9%-5.152027.25
115400725
HIMALAYA
PROTECTIVE
SUNSCREEN LOTION
100ML8901138511104
33049930
REG12 220 148.22CGST-9%-13.34
SGST-9%-13.342098.8
120853981
HIMALAYA
MOISTURIZING
ALOEVERA FACE WASH
200ML8901138836450
33049990
REG12 235 158.33SGST-9%-14.25
CGST-9%-14.252241.9
122727785
HIMALAYA TAN
REMOVAL ORANGE
FACE WASH 100ML8901138837044
33049990
REG 12 180 121.27SGST-9%-10.91
CGST-9%-10.911717.2
122728227
HIMALAYA
REFRESHING AND
CLARIFYING TONER
100ML8901138510329
33049990
REG12 110 74.11SGST-9%-6.67
CGST-9%-6.671049.4
128640525
HIMALAYA FRESH
START - OIL CLEAR
STRAWBERRY FACE
WASH 100ML8901138839659
33049990
REG12 160 107.8SGST-9%-9.7
CGST-9%-9.71526.4
128640568
HIMALAYA FRESH
START - OIL CLEAR
BLUEBERRY FACE
WASH 100ML8901138839680
33049990
REG12 160 107.8CGST-9%-9.7
SGST-9%-9.71526.4
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
150509435
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 200ML8901138848736
33049990
REG 6 205 138.11SGST-9%-12.43
CGST-9%-12.43977.85
150509451
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 400ML8901138848743
33049990
REG 6 370 249.28CGST-9%-22.44
SGST-9%-22.441764.9
154309377
HIMALAYA NATURAL
GLOW ALOEVERA GEL
100ML8901138848484
33049990
REG 24 85 57.27CGST-9%-5.15
SGST-9%-5.151621.8
154309414
HIMALAYA CLEAR
COMPLEXION
BRIGHTENING
MULETHI SHEET MASK8901138849313
33049990
REG20 75 50.53SGST-9%-4.55
CGST-9%-4.551192.5
154309457
HIMALAYA FRESH
START OIL CLEAR
STRAWBERRY SHEET
MASK8901138849306
33049990
REG20 75 50.53CGST-9%-4.55
SGST-9%-4.551192.5
161614011
HIMALAYA ROSE FACE
WASH 100ML8901138847272
33049990
REG24 160 107.8SGST-9%-9.7
CGST-9%-9.73052.8
161614038
HIMALAYA YOUTH
ETERNITY FACE
SHEET MASK 1N8901138849320
33049990
REG 20 85 57.27CGST-9%-5.15
SGST-9%-5.151351.5
Total:     5127.0972        33,611.01
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  MARINA MALL CHN Contact Person:JAISHANKAR KUMAR Phone: 9901932173
User Id:  SCHEDRMS 4/8/2024 4:59:30 AM
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_35000072315120240410024021PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  FORUM MALL - CHN Contact Person:THIYAGARAJAN Phone: 8050041880
User Id:  SCHEDRMS 4/8/2024 4:59:34 AM
Delivery
Address:FORUM MALL - CHN
UNIT NO 1, LOWER GRD
FLR  THE FORUM VIJAYA
MALL,183A  ARCOT ROAD,
VADAPALANI CHENNAI
600026PO No: 11237022 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD
ALAPAKKAM PORUR   CHENNAI 600116
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33961943783 PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW
PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100042811
HIMALAYA NEEM AND
TURMERIC SOAP 75G8901138711962
34011190
REG90 38 25.6SGST-9%-2.3
CGST-9%-2.32718.91
115420726
HIMALAYA NEEM AND
TURMERIC SOAP
75G*48901138827885
34011190
REG 48 141 95SGST-9%-8.55
CGST-9%-8.555380.56
Total:     1235.5176        8,099.47
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  FORUM MALL - CHN Contact Person:THIYAGARAJAN Phone: 8050041880
User Id:  SCHEDRMS 4/8/2024 4:59:34 AM
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_57000072309820240410075541PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:02:29 AM
Delivery
Address:VEGAS MALL
VEGAS MALL  UNIT NOS LG
14, LOWER GROUND FLOOR,
PLOT NO. 06, SECTOR 14
NORTH, DWARKA, NEW
DELHI 110078PO No: 11236931 Supplier: 59770 - THE HIMALAYA DRUG COMPANY-
DELHI
PO Date: 07-APR-2024 915-916  RITHALA INDUSTRIAL AREA,
RITHALA  NORTH WEST DELHI DELHI
110085
GST: 07AAECM0847J1ZE Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: PO Expiry Date: 14-APR-2024 GST: 07AADFT3025B1ZR
NA PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100009743
HIMALAYA BABY
CREAM 50ML8901138511487
33049990
REG24 95 59.58CGST-9%-5.36
SGST-9%-5.361687.2
100009745
HIMALAYA BABY
POWDER 100G8901138511814
33049190
REG18 105 65.85SGST-9%-5.93
CGST-9%-5.931398.6
100009975
HIMALAYA BABY
POWDER 400G8901138824037
33049190
REG10 290 181.86SGST-9%-16.37
CGST-9%-16.372146
120854941
HIMALAYA GENTLE
BABY WIPES 72S PO28901138834739
48182000
REG6 350 222.46SGST-9%-20.02
CGST-9%-20.021575
161614193
HIMALAYA BABY
MASSAGE OIL
MUSTARD 100ML8901138846961
33049990
REG 24 125 78.39CGST-9%-7.06
SGST-9%-7.062220
Total:     1376.9732        9,026.80
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.

Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:59:37 AM
Delivery
Address:VEGAS MALL
VEGAS MALL  UNIT NOS LG
14, LOWER GROUND FLOOR,
PLOT NO. 06, SECTOR 14
NORTH, DWARKA, NEW
DELHI 110078PO No: 11236941 Supplier: 59770 - THE HIMALAYA DRUG COMPANY-
DELHI
PO Date: 07-APR-2024 915-916  RITHALA INDUSTRIAL AREA,
RITHALA  NORTH WEST DELHI DELHI
110085
GST: 07AAECM0847J1ZE Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: PO Expiry Date: 14-APR-2024 GST: 07AADFT3025B1ZR
NA PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
100043179
HIMALAYA PURIFYING
NEEM FACE WASH 50
ML8901138512187
33049990
PSS 36 80 53.9CGST-9%-4.85
SGST-9%-4.852289.6
100043181
HIMALAYA PURIFYING
NEEM FACE WASH 100
ML8901138512460
33049990
PSS 48 150 101.06SGST-9%-9.1
CGST-9%-9.15724
100043455
HIMALAYA FAIRNESS
KESAR FACE WASH
50ML8901138819675
33049990
REG 30 85 57.27CGST-9%-5.15
SGST-9%-5.152027.25
111500569
HIMALAYA STRESS
RELIEF MASSAGE OIL
200ML8901138510626
33049990
REG 6 175 124.22SGST-6%-7.45
CGST-6%-7.45834.75
120853964
HIMALAYA PURIFYINF
NEEM FACE WASH
300ML8901138835545
33049990
KVI 6 345 232.44CGST-9%-20.92
SGST-9%-20.921645.65
120853981
HIMALAYA
MOISTURIZING
ALOEVERA FACE WASH
200ML8901138836450
33049990
REG6 235 158.33CGST-9%-14.25
SGST-9%-14.251120.95
122728227
HIMALAYA
REFRESHING AND
CLARIFYING TONER
100ML8901138510329
33049990
REG12 110 74.11CGST-9%-6.67
SGST-9%-6.671049.4
128640525
HIMALAYA FRESH
START - OIL CLEAR
STRAWBERRY FACE
WASH 100ML8901138839659
33049990
REG12 160 107.8SGST-9%-9.7
CGST-9%-9.71526.4
128640568
HIMALAYA FRESH
START - OIL CLEAR
BLUEBERRY FACE
WASH 100ML8901138839680
33049990
REG12 160 107.8SGST-9%-9.7
CGST-9%-9.71526.4
150509451
HIMALAYA OLIVE
EXTRA NOURISHING
BODY LOTION 400ML8901138848743
33049990
REG 6 370 249.28CGST-9%-22.44
SGST-9%-22.441764.9
154309414
HIMALAYA CLEAR
COMPLEXION
BRIGHTENING
MULETHI SHEET MASK8901138849313
33049990
REG20 75 50.53SGST-9%-4.55
CGST-9%-4.551192.5
154309457
HIMALAYA FRESH
START OIL CLEAR
STRAWBERRY SHEET
MASK8901138849306
33049990
REG20 75 50.53SGST-9%-4.55
CGST-9%-4.551192.5
Total:     3301.9056        21,894.30
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:59:37 AM
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:59:37 AM
.
Buyer's Signature Vendor's Signature
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759055_99000072309820240410075459PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:59:40 AM
Delivery
Address:VEGAS MALL
VEGAS MALL  UNIT NOS LG
14, LOWER GROUND FLOOR,
PLOT NO. 06, SECTOR 14
NORTH, DWARKA, NEW
DELHI 110078PO No: 11236943 Supplier: 59770 - THE HIMALAYA DRUG COMPANY-
DELHI
PO Date: 07-APR-2024 915-916  RITHALA INDUSTRIAL AREA,
RITHALA  NORTH WEST DELHI DELHI
110085
GST: 07AAECM0847J1ZE Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: PO Expiry Date: 14-APR-2024 GST: 07AADFT3025B1ZR
NA PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
101542984
HIMALAYA ANTI HAIR
FALL CREAM 175ML8901138836160
33059030
REG12 100 67.37CGST-9%-6.06
SGST-9%-6.06954
122728702
HIMALAYA ANIT HAIR
FALL CONDITIONER
100ML8901138838539
33051090
REG 18 90 60.64CGST-9%-5.46
SGST-9%-5.461287.9
154309676
HIMALAYA AYURVEDA
GUM CARE
TOOTHPASTE 80G8901138847012
33061020
REG 48 65 43.79CGST-9%-3.94
SGST-9%-3.942480.4
Total:     720.3504        4,722.30
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.
13.FORMS & STATUTORY: C-FORM will be issued based on actual quantity accepted and date of booking into the purchase
ledger account.
14.In case of any discrepancies noticed during in-warding the consignment at warehouse / store, the same shall be
communicated to the Supplier / Vendor on the Goods Receipt Note (GRN). The endorsement as to the quantity and value of
the Product/s by Max Hypermarket on the GRN at time of receiving / inward of products / goods is final and binding on
the parties.
15.The PO value is inclusive of applicable duties and taxes including central excise duty plus cess and the vendor will
discharge the duty liability to the Authority on time and Max Hypermarket will not be responsible for any claim from
the Authority whatsoever anytime.
16.The vendor upon request at any time will supply us with all supporting document/s in support of having discharged
duties / tax liabilities to the Authority.
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:59:40 AM
17.The PO value is inclusive of delivery charges to the warehouse / store.
18.Goods received through Courier or Transports or through a carrier, in a damaged or unsalable condition, will not be
received by the Stores / Distribution Centre. Such goods, if not taken back by the Carrier through which they are
sent, will be retained at Stores / Distribution Centers. Necessary information would be passed on to the supplier for
collection of such damaged or unsalable goods. Suppliers / vendors should make arrangements to ensure the goods are
collected within a period of 30 Days from the date of receipt/ GRN. Such goods would be scrapped at the respective
receiving locations in case if they are not collected back by the vendor/suppliers within the stipulated period of 30
days.
19.On Purchase, Maxhypermarket has the right to sell the same through its various channels including online.
20.In case of any change in sales tax rates after purchase, the difference of tax amount on the stock held on the date of
change shall be recovered from the seller.
21.You acknowledge and declare that you do not have any conflict of interest for entering into a contract/ association
with the Company. You have taken note of the Code of Conduct as well as the Whistle Blower Policy of the Company and
undertake to inform the Company, without delay, in case of any Conflict of Interest or breach of Code of Conduct in
future.
22.You understand and acknowledge that under Company's Code of Conduct and the Whistle Blower Policy, you shall report
any unethical practice or wrongful conduct in the Company by way of an e-mail addressed to
complianceofficer@maxhypermarkets.com .
23.Incase  any liabilities arise infuture to"Max" ordisallowance forGSTinput taxcredit duetodefault bythe
seller onaccount ofnon-payment oftaxes collected/non-filing/incorrect filing ofreturns, Maxwill have right to
recover  suchtaxliability amount/disallowed input  GSTcredit withInterest andpenalty charged byGSTAuthority.
24.Login to Vendor Portal to check Account Statements.
25.For any further queries/ clarifications contact Service Helpdesk email ID:
Spartradeaccounts.Helpdesk@landmarkgroup.in
.
Buyer's Signature Vendor's Signature
C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712759056_15000072309820240410075444PM.pdf
Max Hypermarket India Pvt Ltd
Purchase Order
(System Generated)Corporate and Registered office:
#39/3 & 44,
2nd Floor, Above SPAR Hypermarket
Bannerghatta Road
Bangalore
Ph.No :+918041811600
GST :29AAECM0847J1Z8  TIN
:29880462412
Location:  VEGAS MALL Contact Person:RITESH GAUTAM Phone: 9810443455
User Id:  SCHEDRMS 4/8/2024 4:59:44 AM
Delivery
Address:VEGAS MALL
VEGAS MALL  UNIT NOS LG
14, LOWER GROUND FLOOR,
PLOT NO. 06, SECTOR 14
NORTH, DWARKA, NEW
DELHI 110078PO No: 11236944 Supplier: 59770 - THE HIMALAYA DRUG COMPANY-
DELHI
PO Date: 07-APR-2024 915-916  RITHALA INDUSTRIAL AREA,
RITHALA  NORTH WEST DELHI DELHI
110085
GST: 07AAECM0847J1ZE Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: PO Expiry Date: 14-APR-2024 GST: 07AADFT3025B1ZR
NA PO version: Original PO Status: Approved TIN:
SKU Code
SKU DescEAN
HSNAR Qty MRP Unit
CostDisc % Tax-Rate%-TaxAmt Total Value
111500681
HIMALAYA
ANTISEPTIC CREAM
20G8901138509026
30049011
REG 12 55 39.04SGST-6%-2.34
CGST-6%-2.34524.7
Total:     56.2176        524.70
Purchase Order Terms & Conditions:
1.The goods / products for delivery to our warehouse / store should always be accompanied with a  duly signed and
stamped original invoice  (P.O number incorporated therein) and a copy of P.O. (in case of computer generated invoice
and not duly signed,  please mention on the Invoice that "this is an approved electronically generated and confirmed
invoice does not require any signature " ).
2.The counter foil of waybill / road permit (with all details mentioned therein) duly signed and stamped by the
authority must accompany with the goods / products (where ever it is applicable).
3.The supply of goods / products should be strictly as per the PO and should have been packed in good condition and
order.
4.Any excess quantity and / or  mismatch of goods / products as compared to PO and delay in delivery will result in
return of the goods / products  back to the  Supplier / Vendor, solely at the cost, risk and for such return no prior
approval from the Supplier / Vendor is required.
5.All supplies should be strictly according to delivery date mentioned in the P.O.
6.Wherever applicable, all regulatory compliances must be fulfilled including but not limited to legal metrology / Food
Safety and Standards Act / Rules before delivery of goods / products to Max Hypermarket warehouse / store.
7.All disputes will be subject to exclusive jurisdiction of Courts at Bangalore only.
8.All suppliers should strictly raise one invoice for one P.O for one delivery location.
9.The goods / products supplied under single consignment should always carry same MRP. If the goods / products in a
single consignment carrying multiple MRP will not be accepted and the same will be returned to the Supplier / Vendor,
in terms of the Point No.4 above.
10.If there is any change or difference in MRP / Cost / Tax etc., of the Invoiced goods / products as compared to that of
the details mentioned in the PO, then at the time of delivery, the change / difference should be brought to the notice
of the Officials of Max Hypermarket India Private Limited and supplier/vendor need to endeavor to resolve associated
issue.
11.All the carton boxes should carry the concerned invoice & P.O number. In case of apparel & Textiles all merchandise
should carry the supplier barcode and not style code.
12.Standard delivery timing for all goods / products (except fresh produce) is between 9.00am and 4.00pm during working
days except on Sunday's, festival and national holidays. For actual delivery time contact respective delivery
location.

,SKU Code,SKU Desc,EAN,HSN,AR,Qty,MRP,Unit Cost,SGST Tax-Rate%,SGST TaxAmt,CGST Tax-Rate%,CGST TaxAmt,Total Value
0,100041077,HIMALAYA FAIRNESS \nCREAM 50G,8901138836146,33049910,REG,6,100,67.37,9,6.06,9,6.06,477.00
1,100043179,HIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML,8901138512187,33049990,REG,36,80,53.90,9,4.85,9,4.85,2289.60
2,100043181,HIMALAYA PURIFYING\nNEEM FACE WASH 100\nML,8901138512460,33049990,PSS,24,150,101.06,9,9.10,9,9.12,862.00
3,100043219,HIMALAYA NEEM \nFOAMING FACE WASH \n150ML,8901138512811,33049990,REG,6,275,185.28,9,16.67,9,16.67,1311.75
4,100043661,HIMALAYA PURIFYING\nNEEM SCRUB 100ML,8901138821920,33049990,REG,12,160,107.80,9,9.71,9,9.70,526.40
5,103656221,HIMALAYA MEN POWER\nGLOW LICORICE FACE\nWASH 1...,8901138831073,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
6,115400549,HIMALAYA MEN'S \nPIMPLE CLEAR NEEM \nFACE WASH...,8901138835330,33049990,REG,6,189,127.33,9,11.46,9,11.46,901.53
7,115400581,HIMALAYA OIL CLEAR\nMUD FACE PACK 50 \nGMS,8901138821968,33049990,REG,30,85,57.27,9,5.15,9,5.15,2027.25
8,115400725,HIMALAYA \nPROTECTIVE \nSUNSCREEN LOTION \n100ML,8901138511104,33049930,REG,12,220,148.22,9,13.34,9,13.34,2098.80
9,120853981,HIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n...,8901138836450,33049990,REG,12,235,158.33,9,14.25,9,14.25,2241.90
10,122727785,HIMALAYA TAN \nREMOVAL ORANGE \nFACE WASH 100ML,8901138837044,33049990,REG,12,180,121.27,9,10.91,9,10.91,1717.20
11,122728227,HIMALAYA \nREFRESHING AND \nCLARIFYING TONER \...,8901138510329,33049990,REG,12,110,74.11,9,6.67,9,6.67,1049.40
12,128640525,HIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERR...,8901138839659,33049990,REG,12,160,107.80,9,9.70,9,9.71,526.40
13,128640568,HIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY...,8901138839680,33049990,REG,12,160,107.80,9,9.71,9,9.70,526.40
14,150509435,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848736,33049990,REG,6,205,138.11,9,12.43,9,12.43,977.85
15,150509451,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848743,33049990,REG,6,370,249.28,9,22.44,9,22.44,1764.90
16,154309377,HIMALAYA NATURAL \nGLOW ALOEVERA GEL \n100ML,8901138848484,33049990,REG,24,85,57.27,9,5.15,9,5.15,1621.80
17,154309414,HIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMU...,8901138849313,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
18,154309457,HIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY ...,8901138849306,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
19,161614011,HIMALAYA ROSE FACE\nWASH 100ML,8901138847272,33049990,REG,24,160,107.80,9,9.70,9,9.73,52.80
20,161614038,HIMALAYA YOUTH \nETERNITY FACE \nSHEET MASK 1N,8901138849320,33049990,REG,20,85,57.27,9,5.15,9,5.15,1351.50
21,100042811,HIMALAYA NEEM AND \nTURMERIC SOAP 75G,8901138711962,34011190,REG,90,38,25.60,9,2.30,9,2.32,718.91
22,115420726,HIMALAYA NEEM AND \nTURMERIC SOAP \n75G*4,8901138827885,34011190,REG,48,141,95.00,9,8.55,9,8.55,5380.56
23,100009743,HIMALAYA BABY \nCREAM 50ML,8901138511487,33049990,REG,24,95,59.58,9,5.36,9,5.36,1687.20
24,100009745,HIMALAYA BABY \nPOWDER 100G,8901138511814,33049190,REG,18,105,65.85,9,5.93,9,5.93,1398.60
25,100009975,HIMALAYA BABY \nPOWDER 400G,8901138824037,33049190,REG,10,290,181.86,9,16.37,9,16.37,2146.00
26,120854941,HIMALAYA GENTLE \nBABY WIPES 72S PO2,8901138834739,48182000,REG,6,350,222.46,9,20.02,9,20.02,1575.00
27,161614193,HIMALAYA BABY \nMASSAGE OIL \nMUSTARD 100ML,8901138846961,33049990,REG,24,125,78.39,9,7.06,9,7.06,2220.00
28,100043179,HIMALAYA PURIFYING\nNEEM FACE WASH 50 \nML,8901138512187,33049990,PSS,36,80,53.90,9,4.85,9,4.85,2289.60
29,100043181,HIMALAYA PURIFYING\nNEEM FACE WASH 100\nML,8901138512460,33049990,PSS,48,150,101.06,9,9.10,9,9.15,724.00
30,100043455,HIMALAYA FAIRNESS \nKESAR FACE WASH \n50ML,8901138819675,33049990,REG,30,85,57.27,9,5.15,9,5.15,2027.25
31,111500569,HIMALAYA STRESS \nRELIEF MASSAGE OIL\n200ML,8901138510626,33049990,REG,6,175,124.22,6,7.45,6,7.45,834.75
32,120853964,HIMALAYA PURIFYINF\nNEEM FACE WASH \n300ML,8901138835545,33049990,KVI,6,345,232.44,9,20.92,9,20.92,1645.65
33,120853981,HIMALAYA \nMOISTURIZING \nALOEVERA FACE WASH\n...,8901138836450,33049990,REG,6,235,158.33,9,14.25,9,14.25,1120.95
34,122728227,HIMALAYA \nREFRESHING AND \nCLARIFYING TONER \...,8901138510329,33049990,REG,12,110,74.11,9,6.67,9,6.67,1049.40
35,128640525,HIMALAYA FRESH \nSTART - OIL CLEAR \nSTRAWBERR...,8901138839659,33049990,REG,12,160,107.80,9,9.70,9,9.71,526.40
36,128640568,HIMALAYA FRESH \nSTART - OIL CLEAR \nBLUEBERRY...,8901138839680,33049990,REG,12,160,107.80,9,9.70,9,9.71,526.40
37,150509451,HIMALAYA OLIVE \nEXTRA NOURISHING \nBODY LOTIO...,8901138848743,33049990,REG,6,370,249.28,9,22.44,9,22.44,1764.90
38,154309414,HIMALAYA CLEAR \nCOMPLEXION \nBRIGHTENING \nMU...,8901138849313,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
39,154309457,HIMALAYA FRESH \nSTART OIL CLEAR \nSTRAWBERRY ...,8901138849306,33049990,REG,20,75,50.53,9,4.55,9,4.55,1192.50
40,101542984,HIMALAYA ANTI HAIR\nFALL CREAM 175ML,8901138836160,33059030,REG,12,100,67.37,9,6.06,9,6.06,954.00
41,122728702,HIMALAYA ANIT HAIR\nFALL CONDITIONER \n100ML,8901138838539,33051090,REG,18,90,60.64,9,5.46,9,5.46,1287.90
42,154309676,HIMALAYA AYURVEDA \nGUM CARE \nTOOTHPASTE 80G,8901138847012,33061020,REG,48,65,43.79,9,3.94,9,3.94,2480.40
43,111500681,HIMALAYA \nANTISEPTIC CREAM \n20G,8901138509026,30049011,REG,12,55,39.04,6,2.34,6,2.34,524.70

In [ ]:
'''
Delivery 
Address:MARINA MALL CHN
 MARINA MALL, NO 13/1A
EGATTUR OLD 
MAHABALIPURAM, 
TIRUPORUR TALUK  
KANCHIPURAM DISTRICT 
CHENNAI 603106PO No: 11237019 Supplier: 60009 - THE HIMALAYA DRUG COMPANY-
CHENNAI
PO Date: 07-APR-2024 100A ALAPAKKAM MAIN ROAD  
ALAPAKKAM PORUR   CHENNAI 600116 
GST: 33AAECM0847J1ZJ Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: 33AAECM0847J1ZJ PO Expiry Date: 14-APR-2024 GST: 33AADFT3025B1ZW 
PO version: Original PO Status: Approved TIN:
'''

'''
Delivery 
Address:VEGAS MALL
VEGAS MALL  UNIT NOS LG
14, LOWER GROUND FLOOR,
PLOT NO. 06, SECTOR 14 
NORTH, DWARKA, NEW 
DELHI 110078PO No: 11236944 Supplier: 59770 - THE HIMALAYA DRUG COMPANY-
DELHI
PO Date: 07-APR-2024 915-916  RITHALA INDUSTRIAL AREA, 
RITHALA  NORTH WEST DELHI DELHI 
110085 
GST: 07AAECM0847J1ZE Delivery Date: 13-APR-2024 Ph.No: 9016157766
TIN: PO Expiry Date: 14-APR-2024 GST: 07AADFT3025B1ZR 
NA PO version: Original PO Status: Approved TIN:
'''

def extract_head_data(text):
    head_data = {}
    pattern = r"Delivery\s*\n?Address:(.+?)PO No:\s*(\d+)\s*Supplier:\s*(.+?)PO Date:\s*(\d+-\w+-\d+)(.+?)GST:\s*(\w*)\s*Delivery Date:\s*(\d+-\w+-\d+)\s*Ph.No:\s*(\d+)\n?\s*TIN:\s*(\w*)\s*PO Expiry Date:\s*(\d+-\w+-\d+)\s*GST:\s*(\w+)\s*\n(\w*)\s*PO version:\s*(\w+)\s*PO Status:\s*(\w+)\s*TIN:"
    matched = re.findall(pattern, text, re.DOTALL)
    if matched:
        for match in matched:
            head_data['Delivery Address'] = "".join(match[0].split('\n'))
            head_data['PO NO'] = match[1]
            head_data['Supplier'] = "".join("\n".join([match[2], match[4]]).split('\n'))
            head_data['PO Date'] = match[3]
            head_data['GST No'] = match[5]
            head_data['Delivery Date'] = match[6]
            head_data['Supplier Phone No'] = match[7]
            head_data['TIN'] = match[8]
            head_data['PO Expiry Date'] = match[9]
            head_data['Supplier GST No'] = match[10]
            head_data['PO Version'] = match[12]
            head_data['PO Status'] = match[13]
            head_data['Supplier TIN'] = match[11]
        df = pd.DataFrame(head_data, index=[0])
        dates = ['PO Date', 'Delivery Date', 'PO Expiry Date']
        for col in dates:
            df[col] = pd.to_datetime(df[col], errors='coerce')
        return df
    return None

        
# pdf_path = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max\1712740152_2000072315020240410024041PM.pdf"
pdf_dir = r"C:\Users\TP_USER\Downloads\POReaderFormats\POReaderFormats\Max"
count = 1
for pdf in os.listdir(pdf_dir):
    pdf_path = os.path.join(pdf_dir, pdf)
    pdf_read = PdfReader(pdf_path)
    text = '\n'.join([page.extract_text() for page in pdf_read.pages])
    head_data_df = extract_head_data(text)
    if head_data_df is not None:
        count = upload_to_mssql(head_data_df, count)
        print("Successfully upload data into mssql")
    else:
        print("Error uploading data into mssql")

In [ ]:
import pandas as pd
import pyodbc
from datetime import datetime

def upload_to_mssql(df, count=1):
    # Check if DataFrame is empty
    if df.empty:
        print("DataFrame is empty. No records to upload.")
        return

    current_datetime = datetime.now()

    # Database connection parameters
    server = 'TPSYS-2132'
    database = 'Himalaya_PDF_data'
    username = 'sa'
    password = 'Admin@123'
    driver = '{ODBC Driver 17 for SQL Server}'

    # Create a connection string
    conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'

    try:
        # Connect to SQL Server
        conn = pyodbc.connect(conn_str)

        # Create a cursor
        cursor = conn.cursor()
        # Insert DataFrame records into SQL Server table
        for index, row in df.iterrows():
            cursor.execute("""
            INSERT INTO HPOF_MT_Order_Header (
                Customer, Upload_Order_No, Upload_Order_date, CustomerPONo,
                CustomerPODate, CustomerDeliveryDate, SOOverAllStatus,
                SOOverAllLastModified_on
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, 
            "Cust"+str(count), count, current_datetime,
            row['PO NO'], row['PO Date'], row['Delivery Date'],
            'S', current_datetime)
            count += 1

        # Commit the transaction
        conn.commit()
        print("Data uploaded successfully.")
        return count

    except Exception as e:
        print(f"Error uploading data: {e}")

    finally:
        # Close the cursor and connection
        cursor.close()
        conn.close()