In [1]:
# !pip install ironpdf

In [2]:
# !pip install spacy

In [3]:
# !python -m spacy download en_core_web_sm

In [4]:
# !pip install tabula-py

In [5]:
# !pip install tabulate

In [64]:
# !pip install camelot-py

In [7]:
# !pip install opencv-python

In [65]:
# !pip install camelot-py[cv]

In [4]:
import ironpdf
from ironpdf import PdfDocument
pdf_file = PdfDocument.FromFile("0000704860_2023_06_14_01_00_01_PM.PDF")
ironpdf.License.LicenseKey = "IRONSUITE.LAXMIPRASANNA.PEDDAGUTTA.TALENTPACE.COM.13840-9CE3F82042-HW4SM7G2WAPTPW-YB6CB2C5IZEK-JR5YG7PRGQ43-Y3GY5YXY63J7-72T3FSGQY3G5-PAPKW6LTCHEH-3GOMZY-TOQBWFPCF6WLUA-DEPLOYMENT.TRIAL-Y2KBWZ.TRIAL.EXPIRES.13.MAR.2024"

Attempting import of IronPdf 2024.2.1.2
Checking directory "C:\Users\TP_USER\anaconda3"
Warning! Failed to install .NET 6.0. Consider manually installing .NET 6.0 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Succesfully located files in "C:\Users\TP_USER\anaconda3"
IronPdf detected root Python package directory of C:\Users\TP_USER\anaconda3/IronPdf.Slim
IronPdf will now download dependencies for Windows to C:\Users\TP_USER\anaconda3\IronPdf.Native.Chrome.Windows\2024.2.1.2. If you encounter any issues launching IronPdf, please remove .nupkg files from this directory and try again. Visit https://ironpdf.com/python/docs/ for more information.
Optionally you may set Installation.CustomDeploymentDirectory to a custom directory and manually download IronPdf.Native.Chrome.Windows NuGet package to this directory.

In [5]:
text = pdf_file.ExtractAllText()
print(text)

AMENDED PURCHASE ORDER - DO NOT DUPLICATE
This Amendment to the Purchase Order is issued to incorporate the following change(s) to the above noted Purchase Order:
 9200025737 dt. 14.06.2023.
______________________________________________________________________________
Amendment to the Total Price as a result of this Revision INR 0.00
Original/Previous Total Purchase Order Price : INR 98,322.18
Revised Total Purchase Order Price : INR 98,322.18
 Delivery Date 21.06.2023
______________________________________________________________________________
ALL OTHER REQUIREMENTS, TERMS AND CONDITIONS SHALL REMAIN UNCHANGED AS PER
THE ORIGINAL PURCHASE ORDER AND ANY PREVIOUS CHANGE ORDER REVISION(S).
______________________________________________________________________________
It is important that SELLER signs and returns the Purchase Change Order Copy within three (3) days of receipt. No other
form of Order acceptance will be accepted. Failure to return the copy does not diminish responsibilities as set forth here in
but may result in a delay to any payments that may be due.
______________________________________________________________________________
FOR
This is a computer generated document
 BUYER : RROPSFNR Authorised
______________________________________________________________________________
SELLER's Acceptance :
REGISTERED OFFICE : 3rd Floor, Court House Lokmanya Tilak Marg, Dhobi Talao, MUMBAI 400002

RELIANCE RETAIL LIMITED
FF101,Saffron
Panchwati 5 Rasta,
 Near Bank of Baroda Ambawadi,
Ahmedabad , 380006 GJ , IN
Telephone :
SELLER PURCHASE CHANGE ORDER
10004504 Original Order No.:SK6C/9200025737
Himalaya Wellness Company Revision No. : 0001
1 Ashish Estate Date : 14.06.2023
N H No 8 Aslali
THE HIMALA Delv Add :
AHMEDABAD GUJARAT Wh No 2 Uno Logistics Park
Pin Code: 382427 ven_country& Village Kochariya Bavla
Rajkot Highway
Attention :
Tel.No. : AHMEDABAD, Gujarat - 382220
E-Mail. : cfa.ahm.kbshah@himalayahealthcare.com Tel:/Fax:
Email:



______________________________________________________________________________________________________________
No Article No. EAN No Material Description Quantity UOM MRP Base Cost CGST(%) CGST(INR) Total Base
HSN/SAC Code Vendor Article No Delivery Date SGST(%) SGST(INR) Value(INR)
Vendor Item No Site CESS(%) CESS(INR) ______________________________________________________________________________________________________________
1 490003346 8901138002466 HIMALAYA AD TEA TREE SHAMPOO 180ML PET 2 CRT 3600.00 2,394.91 9.00 431.08 4,789.83
33051090 406074 21.06.2023 9.00 431.08
SK6C
 48 EA 150.00
______________________________________________________________________________________________________________
2 490003407 8901138511814 HIMALAYA BABY POWDER 100 g BTL 4 C07 3420.00 1,970.85 9.00 709.51 7,883.39
33049120 21.06.2023 9.00 709.51
SK6C
 144 EA 95.00
______________________________________________________________________________________________________________
3 490766695 8901138002428 HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET 1 CAR 3360.00 2,235.25 9.00 201.17 2,235.25
33051090 943920 21.06.2023 9.00 201.17
SK6C
 12 EA 280.00
______________________________________________________________________________________________________________
4 490782407 8901138513153 HIMALAYA BABY POWDER 200 g BTL 5 C07 3600.00 2,074.58 9.00 933.56 10,372.88
33049120 21.06.2023 9.00 933.56
SK6C
 120 EA 150.00
______________________________________________________________________________________________________________
5 490819102 8901138819668 HIMALAYA HER FAIRNES KESAR FW 100ml TUBE 1 CAR 4470.00 2,973.69 9.00 267.63 2,973.69
33041000 406097 21.06.2023 9.00 267.63
SK6C
 30 EA 149.00
______________________________________________________________________________________________________________
6 491238725 8901138824037 HIMALAYA BABY POWDER 400 g BTL 11 C07 5000.00 2,881.36 9.00 2,852.54 31,694.92
33049120 21.06.2023 9.00 2,852.54
SK6C
 220 EA 250.00
______________________________________________________________________________________________________________
7 491249578 8901138714628 HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP 1 CAR 6360.00 4,231.02 9.00 380.79 4,231.02
34011110 944069 21.06.2023 9.00 380.79
SK6C
 30 EA 212.00
______________________________________________________________________________________________________________
8 491249580 8901138827885 HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD 1 CAR 6384.00 4,246.98 9.00 382.23 4,246.98
34011110 944068 21.06.2023 9.00 382.23
SK6C
 48 EA 133.00
______________________________________________________________________________________________________________
9 491296367 8901138836306 HIMALAYA COMPL CARE TTPST 2N X150 g TUBE 3 CAR 2862.00 1,903.96 9.00 514.07 5,711.87
33061020 943929 21.06.2023 9.00 514.07
1088 SK6C
 54 EA 159.00
______________________________________________________________________________________________________________
AMENDED PURCHASE ORDER Number 9200025737
Rev : 0001 Dt.14.06.2023
 Page No: 1



______________________________________________________________________________________________________________
No Article No. EAN No Material Description Quantity UOM MRP Base Cost CGST(%) CGST(INR) Total Base
HSN/SAC Code Vendor Article No Delivery Date SGST(%) SGST(INR) Value(INR)
Vendor Item No Site CESS(%) CESS(INR) ______________________________________________________________________________________________________________
10 491321625 8901138714611 HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD 1 CAR 6360.00 4,231.02 9.00 380.79 4,231.02
34011110 944071 21.06.2023 9.00 380.79
SK6C
 30 EA 212.00
______________________________________________________________________________________________________________
11 491903304 8901138845476 HIM BABY HAIR OIL 100 ml PET 1 C07 6240.00 3,595.93 9.00 323.63 3,595.93
33059011 943744 21.06.2023 9.00 323.63
SK6C
 48 EA 130.00
______________________________________________________________________________________________________________
12 492367878 8901138848484 HIMALAYA ALE VERA FCE GEL 100ML CON 1 CAR 2040.00 1,357.12 9.00 122.14 1,357.12
33049990 21.06.2023 9.00 122.14
SK6C
 24 EA 85.00
______________________________________________________________________________________________________________
Grand Total = 32 ______________________________________________________________________________________________________________
Total Basic Value INR 83,323.90
Total CGST INR 7,499.14
Total SGST INR 7,499.14
______________________________________________________________________________________________________________
Revised Total Purchase Order Price: INR 98322.18
Original/Previous Total Purchase Order Price: INR 98322.18
Amendment to the Total Price as a result of this Revision INR 0.00 ______________________________________________________________________________________________________________
Terms of payment :
Pro-rata payment(s) shall be made within 30 days from the date of receipt of GOODS, or receipt of correct invoice & dispatch documents whichever is later.
AMENDED PURCHASE ORDER Number 9200025737
Rev : 0001 Dt.14.06.2023
 Page No: 2



______________________________________________________________________________________________________________
Note(S):
 It is essential that the seller shall mention Item No.& Item code along with corresponding Material Description and P.O. No. as mentioned above, in the Delivery challan(On-Shore Order) /
Packing List (Off-shore Order) and invoice for ease of material Inwarding and Bill Processing. It is also essential that the Seller attaches a Tag /Sticker with each item indicating item Code & PO
No. Failure to do so may be the grounds for the rejection(s) or delay in release of payment(s).
 Suppliers need to call the destination DC/Store atleast 24 hrsin advance to schedule the delivery time for goods.Vehicles without prior appointment could be subject to delay.
 GSTIN Number Details :-
 -----------------------------
GSTIN NO : 24AABCR1718E1ZV
PAN No. : AABCR1718E
As per recent amendment(s) in the Income-Tax Rules ("Rules") made vide the Income-tax (22nd Amendment) Rules, 2015, effective 1 January 2016. Rule 114B of the Rules as
substituted, mentions transactions in relation to which Permanent Account Number (PAN) is to be quoted on all documents and includes sale or purchase of goods or services of any
nature for an amount exceeding two lakh rupees per transaction (Sl. No 18 of the Table in Rule 114B).
Rule 114C (2) of the Rules as substituted reads as follows: "Anyperson, being a person raising bills referred to at Sl. No 5 or 6 or18 of rule 114B, who, in relation to a transaction
specified in the saidSl. No., has issued any document shall ensure after verification that permanent account number has been correctly furnished and the same shallbe mentioned in such
document, or as the case may be, a declarationin Form 60 has been duly furnished with complete particulars". In case PAN is applied for and / or not available, Form 60 is to be duly
filled and signed / verified and submitted with identity and address proof (KYC documents) as per the page 3 of form 60.
You are therefore requested that your invoice / bill / payment acknowledgement / debit note / credit note, etc. should mention PAN of your entity as well as our PAN.
 DEFINITIONS AND INTERPRETATION
 1.1 Definitions:
 The following terms, unless the context requires otherwise, shall have the following meanings:

 (a) ACCEPTANCE OF GOODS means (i) if acceptance criteria are set forth in this CONTRACT, the BUYER#S preliminary determination that the GOODS satisfy all such acceptance criteria,
including commissioning and performance tests, if applicable; or (ii) if no such criteria are provided, the BUYER#S preliminary determination that the GOODS comply with all requirements set
forth in this CONTRACT. ACCEPTANCE OF GOODS shall be evidenced by the issuance of an acceptance certificate by the BUYER.

 (b) AFFILIATE means, with respect to any PERSON, any other PERSON, directly or indirectly controlling, controlled by or under direct, indirect or common control with, such PERSON. For
the purposes of this definition, #control# means the possession, directly or indirectly, of the power to direct or cause the direction of the management or policies of such PERSON, whether
through the ownership of voting securities, by agreement with respect to the voting of securities, by other agreement conferring control over management or policy decisions, by virtue of the
power to control the composition of the board of directors or managers, or otherwise. The terms #controlling# and #controlled# shall have correlative meanings.

 (c) BUYER means Reliance Retail Limited and shall include its successors and assigns. Terms such as #Reliance Retail Limited#,Purchaser','Owner', or 'Customer',as may be used in any
CONTRACT DOCUMENTS shall be construed to mean BUYER.

 (d) CHANGE is defined in Section 19.1.

 (e) CHANGE NOTICE is defined in Section 19.1.

 (f) CONFIDENTIAL INFORMATION is defined in Section 12.

AMENDED PURCHASE ORDER Number 9200025737
Rev : 0001 Dt.14.06.2023
 Page No: 3



(g) CONTRACT means the totality of the agreement between the BUYER and the SELLER as expressed in the CONTRACT DOCUMENTS.

 (h) CONTRACT DOCUMENTS means the following and in the event of any conflicting provisions within the CONTRACT DOCUMENTS, the order of precedence of the documents shall be
as provided below:
 PURCHASE ORDER, including any amendments thereto;
 SPECIAL CONDITIONS and annexures thereto;
 GCP; and
 any other document (A) referred to in any of the documents referred to in clauses (i) through (iii) above, or (B) agreed by the PARTIES to constitute a part of the CONTRACT DOCUMENTS
and incorporated herein by specific reference.

 (i) DEFECT means any defect, deficiency, error, failure, flaw, omission, damage, fault, inadequacy or discrepancy in the workmanship or in the materials used in the fabrication and manufacture
of GOODS or any part or component thereof and the word #DEFECTIVE# shall be construed accordingly.

 (j) DELIVERY POINT is defined or described in the SPECIAL CONDITIONS.

 (k) DELIVERY SCHEDULE is defined or described in the SPECIAL CONDITIONS.

 (l) DELIVERY TERMS means the terms for the delivery of the GOODS, including the DELIVERY SCHEDULE, DELIVERY POINTS and locations and shipping terms, as set out in this
CONTRACT. Except as otherwise specified in this CONTRACT, terms for the delivery of the GOODS shall incorporate the INCOTERMS.

 (m)DISPUTE is defined in Section 18.

 (n) DRAWINGS and DOCUMENTS mean the design calculations, drawings, analysis patterns, specifications, construction and fabrication drawings and documents, certificates, test results,
installation, operating and maintenance manuals and any other documentation or materials prepared or provided by the SELLER under this CONTRACT (whether recorded in physical form or on
electronic storage media).

 (o) GOODS means each item to be provided to the BUYER by the SELLER, or by a SUB-SELLER on behalf of the SELLER, including raw materials, processed materials, equipment,
components, fabricated goods, finished products, spares, DRAWINGS and DOCUMENTS, data, related firmware or software and any other documentation described in this CONTRACT.

 (p) GOODS WARRANTY and GOODS WARRANTIES are defined in Section 9.

 (q) GOODS WARRANTY PERIOD is defined or described in the SPECIAL CONDITIONS. (r) GENERAL CONDITIONS OF PURCHASE or GCP means this General Conditions of
Purchase.

 (s) INCOTERMS means the most recent International Commercial Terms published by the International Chamber of Commerce, Paris, which are in effect as on the date of the PURCHASE
ORDER.

 (t) INVOICE PAYMENT DETAILS is defined in Section 5.

 (u) MAKE GOOD means to repair, correct, re-perform, replace, re-install or re-erect, as appropriate, any part, section, component or functionality of the GOODS, including all testing and
re-testing related thereto, such that the GOODS fully comply and conform to the requirements of this CONTRACT.

 (v) MALICIOUS CODE means any (i) computer virus, worm, bot or trojan or (ii) spyware, malware, malicious, destructive or corrupting code, program, or macro, or any other code, program or
macro that is hostile or damaging to information systems or components thereof.

 (w)PARTY means either the BUYER or the SELLER, as the context requires, and the PARTIES mean both the BUYER and the SELLER.

 (x) PERFORMANCE SECURITY is defined in the SPECIAL CONDITIONS.

 (y) PERSON means any individual, firm, corporation, limited liability company, voluntary association, partnership, joint venture, trust, limited organization, society, unincorporated organization,
governmental authority or other legal entity or organization.

 (z) PURCHASE ORDER means the document entitled #Purchase Order# to which the documents referenced in Section 1.1 (h) (ii) to (iv) are attached.

 (aa) SCOPE OF SUPPLY means all of the requirements of the BUYER with respect to the supply of the GOODS by the SELLER as set forth in the CONTRACT DOCUMENTS.
AMENDED PURCHASE ORDER Number 9200025737
Rev : 0001 Dt.14.06.2023
 Page No: 4



(bb) SELLER means the PERSON with whom the BUYER has entered into this CONTRACT for purchase of the GOODS, as identified on the face of the PURCHASE ORDER, and shall
include such PERSON#S successors and permitted assigns. Terms such as #Vendor#, #Supplier# or #Contractor# as may be used in any CONTRACT DOCUMENTS shall be construed to mean
SELLER.

 (cc) SITE means the BUYER#S premises at which the GOODS are to be stored, located or used as determined by the BUYER.

 (dd) SPECIAL CONDITIONS means the document entitled #SPECIAL CONDITIONS# and attached to the PURCHASE ORDER.

 (ee) SPECIFICATIONS means the description of the GOODS to be supplied under this CONTRACT, including, where appropriate, all specifications, requirements, technical standards, quality
standards, performance standards, compatibility, interoperability, instructions, DRAWINGS and DOCUMENTS and other related criteria.

 (ff)SUB-ORDER means an agreement entered into between the SELLER and a SUB-SELLER for the supply of raw materials, components, equipment, services or such other items as may be
required by the SELLER to enable the fulfilment of the SELLER#S obligations under this CONTRACT.

 (gg) SUB-SELLER means any third party from whom the SELLER sources raw materials, components, equipment, services or such other items as may be required by the SELLER to enable the
fulfilment of the SELLER#S obligations under this CONTRACT.

 (hh) SUPPORTING DOCUMENTS is defined in Section 5.

 (ii) TAX or TAXES means all taxes, levies, cess, duties, fees, charges and other assessments imposed or assessed on or payable by the SELLER in any jurisdiction in relation to this CONTRACT
or the SELLER#S performance of this CONTRACT.

 (jj) TOTAL BASIC VALUE means the amount identified as the #Total Basic Value# set forth on the face of the PURCHASE ORDER, as the PURCHASE ORDER may be amended from time
to time.

 (kk) TOTAL ORDER VALUE means the amount identified as the #Total Order Value# set forth on the face of the PURCHASE ORDER, as the PURCHASE ORDER may be amended from
time to time.

 1.2 In this CONTRACT:
 The singular shall include plural and vice versa, and words denoting natural persons shall also apply to partnerships, firms, companies, corporations, joint ventures, trusts, associations,
organizations and other entities. All references to Sections, sub-sections, clauses, paragraphs and annexures are to Sections, sub-sections, clauses, paragraphs and annexures in or to this GCP
unless otherwise specified. Reference to any statute shall include reference to applicable rules, regulations, ordinance, notification, orders or any other instrument having force of law prescribed,
issued or passed under such statute with amendments thereto and replacements thereof. Unless otherwise required by the context in which any term appears, capitalized terms used in the
CONTRACT DOCUMENTS shall have the meanings specified in this GCP, or if not defined in this GCP, as defined elsewhere in the CONTRACT DOCUMENTS. For the purposes of this
CONTRACT, the words and abbreviations that have well-known technical or trade meanings used but not defined in this GCP or elsewhere in this CONTRACT, shall be construed in accordance
with such recognized technical or trade meanings. The words #include# and #including# are to be construed without limitation. Whenever the context may require, any pronoun shall include the
corresponding masculine, feminine and neuter forms. The term #or# is not exclusive. The word #extent# in the phrase #to the extent# shall mean the degree to which a subject or other thing
extends, and such phrase shall not mean simply #if.# The words #herein,# #hereof# and #hereunder# and words of similar import when used shall refer to this CONTRACT as a whole and not to
any particular Section or sub-section of this CONTRACT.

 SUPPLY OF GOODS

 The SELLER shall complete the delivery of the GOODS in accordance with the DELIVERY TERMS. All the obligations of the SELLER to be performed on the dates as specified in this
CONTRACT, including the delivery of the GOODS in accordance with the DELIVERY SCHEDULE are essential conditions of this CONTRACT. The SELLER shall at all times comply with
all applicable laws in the SELLER#S performance of this CONTRACT. The SELLER shall obtain or procure any and all licences, permits, consents and approvals which may be required by any
governmental authority to enable the supply of the GOODS in accordance with this CONTRACT.

 PRICE

 Unless otherwise expressly stated in this CONTRACT, the prices and rates set forth in this CONTRACT for the GOODS are not subject to any escalation on any account, including due to any
increase in the cost of production, raw materials, labour, TAXES, any fluctuations in exchange rates, changes in applicable law or any other reason. Unless otherwise specified in the SPECIAL

In [19]:
extracted_data = dict()

In [7]:
import re
import pandas as pd

In [8]:
cols = ["No", "Article No.", "EAN No", "Material Description", "Quantity", "UOM", "MRP", "Base Cost","CGST(%)","CGST(INR)", "HSN/SAC Code","Vendor Article No","Delivery Date","SGST(%)","SGST(INR)","Vendor Item No","Site","CESS(%)", "CESS(INR)", "Total Base Value(INR)"]
table_df = pd.DataFrame(columns=cols)

In [9]:
def data_to_table(table_data):
    data = []
    for row in table_data:
        row_data = dict()
        for col in cols:
            row_data[col] = 0
        row_splitted = row.split()
#         if len(row_splitted) == 24:
        row_data["No"] = row_splitted[0]
        row_data["Article No."] = row_splitted[1]
        row_data["EAN No"] = row_splitted[2]
        row_data["Site"] = row_splitted[-4]
        row_data["SGST(INR)"] = row_splitted[-5]
        row_data["SGST(%)"] = row_splitted[-6]
        row_data["Delivery Date"] = row_splitted[-7]
            
            


        data.append(row_data)
        print(row_splitted[-1:-9:-1])
    df = pd.DataFrame(data)
    return df

In [10]:
table_data_pattern = re.compile(r"CESS\(INR\) (.+)Grand Total", re.DOTALL)
data_to_exclude = re.compile(r'AMENDED PURCHASE ORDER Number (.+)\r\nRev : (.+)\r\n Page No: (.+) CESS\(INR\)',re.DOTALL)
text_excluded = re.sub(data_to_exclude, "", text)
table_data_matched = table_data_pattern.search(text_excluded)
if table_data_matched:
    table_data_splitted = table_data_matched.group(1).strip().split('______________________________________________________________________________________________________________')
    table_data = [data for data in table_data_splitted if len(data)>3]
    table_df = data_to_table(table_data)
#     for i in table_data:
#         print(i)
#         print("________________________________________________")
else:
    print("no data")

['150.00', 'EA', '48', 'SK6C', '431.08', '9.00', '21.06.2023', '406074']
['95.00', 'EA', '144', 'SK6C', '709.51', '9.00', '21.06.2023', '33049120']
['280.00', 'EA', '12', 'SK6C', '201.17', '9.00', '21.06.2023', '943920']
['150.00', 'EA', '120', 'SK6C', '933.56', '9.00', '21.06.2023', '33049120']
['149.00', 'EA', '30', 'SK6C', '267.63', '9.00', '21.06.2023', '406097']
['250.00', 'EA', '220', 'SK6C', '2,852.54', '9.00', '21.06.2023', '33049120']
['212.00', 'EA', '30', 'SK6C', '380.79', '9.00', '21.06.2023', '944069']
['133.00', 'EA', '48', 'SK6C', '382.23', '9.00', '21.06.2023', '944068']
['159.00', 'EA', '54', 'SK6C', '1088', '514.07', '9.00', '21.06.2023']
['212.00', 'EA', '30', 'SK6C', '380.79', '9.00', '21.06.2023', '944071']
['130.00', 'EA', '48', 'SK6C', '323.63', '9.00', '21.06.2023', '943744']
['85.00', 'EA', '24', 'SK6C', '122.14', '9.00', '21.06.2023', '33049990']

In [11]:
table_df

,No,Article No.,EAN No,Material Description,Quantity,UOM,MRP,Base Cost,CGST(%),CGST(INR),HSN/SAC Code,Vendor Article No,Delivery Date,SGST(%),SGST(INR),Vendor Item No,Site,CESS(%),CESS(INR),Total Base Value(INR)
0,1,490003346,8901138002466,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,431.08,0,SK6C,0,0,0
1,2,490003407,8901138511814,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,709.51,0,SK6C,0,0,0
2,3,490766695,8901138002428,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,201.17,0,SK6C,0,0,0
3,4,490782407,8901138513153,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,933.56,0,SK6C,0,0,0
4,5,490819102,8901138819668,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,267.63,0,SK6C,0,0,0
5,6,491238725,8901138824037,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,"2,852.54",0,SK6C,0,0,0
6,7,491249578,8901138714628,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,380.79,0,SK6C,0,0,0
7,8,491249580,8901138827885,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,382.23,0,SK6C,0,0,0
8,9,491296367,8901138836306,0,0,0,0,0,0,0,0,0,9.00,514.07,1088,0,SK6C,0,0,0
9,10,491321625,8901138714611,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,380.79,0,SK6C,0,0,0
10,11,491903304,8901138845476,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,323.63,0,SK6C,0,0,0
11,12,492367878,8901138848484,0,0,0,0,0,0,0,0,0,21.06.2023,9.00,122.14,0,SK6C,0,0,0

In [61]:


table_data_pattern = re.compile(r"CESS\(INR\) (.+)Grand Total", re.DOTALL)
data_to_exclude = re.compile(r'AMENDED PURCHASE ORDER Number (.+)\r\nRev : (.+)\r\n Page No: (.+) CESS\(INR\)',re.DOTALL)
text_excluded = re.sub(data_to_exclude, "", text)
table_data_matched = table_data_pattern.search(text_excluded)
if table_data_matched:
    data = []
    table_data_splitted = table_data_matched.group(1).strip().split('______________________________________________________________________________________________________________')
    table_data = [data for data in table_data_splitted if len(data)>3]
    for row in table_data:
        print(row)
        row_pattern = re.compile(r"\b(\d+)\s(\d+)\s(\d+)\s(.+?(?:PET|BTL|TUBE|WRP|CBD|CON))\s(\d+)\s(\w+)\s(\d+\.\d+)\s(\d+,\d+\.\d+)\s(\d+\.\d+)\s(\d+\.\d+)\s(\d+\,\d+\.\d+)\s\n(\d+)\s(\d+)\s?(\d+\.\d+\.\d+)\s(\d+\.\d+)\s(\d+\.\d+)\s\n(\w+)\s\n\s(\d+)\s(\w+)\s(\d+)\b")

        matches = row_pattern.findall(row)

        formatted_matches = []
        for match in matches:
            elements = []
            for element in match:
                elements.append(element)
            formatted_matches.append(elements)
        for match in formatted_matches:
            print(match)
            row_dict = dict()
            row_dict["Article No."] = int(match[1])
            row_dict["HSN/SAC Code"] = int(match[11])
            
            row_dict["EAN No"] = int(match[2])
            row_dict["Vendor Article No"] = int(match[12]) if len(match[12])>2 else None
            row_dict["Material Description"] = match[3]
            row_dict["Delivery Date "] = match[13] if len(match[13]) == 10 else match[12]+match[13]
            row_dict["Site"] = match[16]
            
            row_dict["Quantity"] = [match[4],match[17]]
            row_dict["UOM"] = [match[5],match[18]]
            row_dict["MRP"] = [match[6],match[19]]
            row_dict["Base Cost"] = float(''.join(match[7].split(",")))
            row_dict["CGST(%)"] = float(match[8])
            row_dict["SGST(%)"] = float(match[14])
            
            row_dict["CGST(INR)"] = float(match[9])
            row_dict["SGST(INR)"] = float(match[15])
            row_dict["Total Base  Value(INR)"] = float(''.join(match[10].split(",")))
            data.append(row_dict)

            

            
else:
    print("no data")

1 490003346 8901138002466 HIMALAYA AD TEA TREE SHAMPOO 180ML PET 2 CRT 3600.00 2,394.91 9.00 431.08 4,789.83
33051090 406074 21.06.2023 9.00 431.08
SK6C
 48 EA 150.00

['1', '490003346', '8901138002466', 'HIMALAYA AD TEA TREE SHAMPOO 180ML PET', '2', 'CRT', '3600.00', '2,394.91', '9.00', '431.08', '4,789.83', '33051090', '406074', '21.06.2023', '9.00', '431.08', 'SK6C', '48', 'EA', '150']

2 490003407 8901138511814 HIMALAYA BABY POWDER 100 g BTL 4 C07 3420.00 1,970.85 9.00 709.51 7,883.39
33049120 21.06.2023 9.00 709.51
SK6C
 144 EA 95.00

['2', '490003407', '8901138511814', 'HIMALAYA BABY POWDER 100 g BTL', '4', 'C07', '3420.00', '1,970.85', '9.00', '709.51', '7,883.39', '33049120', '2', '1.06.2023', '9.00', '709.51', 'SK6C', '144', 'EA', '95']

3 490766695 8901138002428 HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET 1 CAR 3360.00 2,235.25 9.00 201.17 2,235.25
33051090 943920 21.06.2023 9.00 201.17
SK6C
 12 EA 280.00

['3', '490766695', '8901138002428', 'HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET', '1', 'CAR', '3360.00', '2,235.25', '9.00', '201.17', '2,235.25', '33051090', '943920', '21.06.2023', '9.00', '201.17', 'SK6C', '12', 'EA', '280']

4 490782407 8901138513153 HIMALAYA BABY POWDER 200 g BTL 5 C07 3600.00 2,074.58 9.00 933.56 10,372.88
33049120 21.06.2023 9.00 933.56
SK6C
 120 EA 150.00

['4', '490782407', '8901138513153', 'HIMALAYA BABY POWDER 200 g BTL', '5', 'C07', '3600.00', '2,074.58', '9.00', '933.56', '10,372.88', '33049120', '2', '1.06.2023', '9.00', '933.56', 'SK6C', '120', 'EA', '150']

5 490819102 8901138819668 HIMALAYA HER FAIRNES KESAR FW 100ml TUBE 1 CAR 4470.00 2,973.69 9.00 267.63 2,973.69
33041000 406097 21.06.2023 9.00 267.63
SK6C
 30 EA 149.00

['5', '490819102', '8901138819668', 'HIMALAYA HER FAIRNES KESAR FW 100ml TUBE', '1', 'CAR', '4470.00', '2,973.69', '9.00', '267.63', '2,973.69', '33041000', '406097', '21.06.2023', '9.00', '267.63', 'SK6C', '30', 'EA', '149']

6 491238725 8901138824037 HIMALAYA BABY POWDER 400 g BTL 11 C07 5000.00 2,881.36 9.00 2,852.54 31,694.92
33049120 21.06.2023 9.00 2,852.54
SK6C
 220 EA 250.00


7 491249578 8901138714628 HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP 1 CAR 6360.00 4,231.02 9.00 380.79 4,231.02
34011110 944069 21.06.2023 9.00 380.79
SK6C
 30 EA 212.00

['7', '491249578', '8901138714628', 'HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP', '1', 'CAR', '6360.00', '4,231.02', '9.00', '380.79', '4,231.02', '34011110', '944069', '21.06.2023', '9.00', '380.79', 'SK6C', '30', 'EA', '212']

8 491249580 8901138827885 HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD 1 CAR 6384.00 4,246.98 9.00 382.23 4,246.98
34011110 944068 21.06.2023 9.00 382.23
SK6C
 48 EA 133.00

['8', '491249580', '8901138827885', 'HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD', '1', 'CAR', '6384.00', '4,246.98', '9.00', '382.23', '4,246.98', '34011110', '944068', '21.06.2023', '9.00', '382.23', 'SK6C', '48', 'EA', '133']

9 491296367 8901138836306 HIMALAYA COMPL CARE TTPST 2N X150 g TUBE 3 CAR 2862.00 1,903.96 9.00 514.07 5,711.87
33061020 943929 21.06.2023 9.00 514.07
1088 SK6C
 54 EA 159.00


10 491321625 8901138714611 HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD 1 CAR 6360.00 4,231.02 9.00 380.79 4,231.02
34011110 944071 21.06.2023 9.00 380.79
SK6C
 30 EA 212.00

['10', '491321625', '8901138714611', 'HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD', '1', 'CAR', '6360.00', '4,231.02', '9.00', '380.79', '4,231.02', '34011110', '944071', '21.06.2023', '9.00', '380.79', 'SK6C', '30', 'EA', '212']

11 491903304 8901138845476 HIM BABY HAIR OIL 100 ml PET 1 C07 6240.00 3,595.93 9.00 323.63 3,595.93
33059011 943744 21.06.2023 9.00 323.63
SK6C
 48 EA 130.00

['11', '491903304', '8901138845476', 'HIM BABY HAIR OIL 100 ml PET', '1', 'C07', '6240.00', '3,595.93', '9.00', '323.63', '3,595.93', '33059011', '943744', '21.06.2023', '9.00', '323.63', 'SK6C', '48', 'EA', '130']

12 492367878 8901138848484 HIMALAYA ALE VERA FCE GEL 100ML CON 1 CAR 2040.00 1,357.12 9.00 122.14 1,357.12
33049990 21.06.2023 9.00 122.14
SK6C
 24 EA 85.00

['12', '492367878', '8901138848484', 'HIMALAYA ALE VERA FCE GEL 100ML CON', '1', 'CAR', '2040.00', '1,357.12', '9.00', '122.14', '1,357.12', '33049990', '2', '1.06.2023', '9.00', '122.14', 'SK6C', '24', 'EA', '85']

In [62]:
table_data_df = pd.DataFrame(data)
table_data_df

,Article No.,HSN/SAC Code,EAN No,Vendor Article No,Material Description,Delivery Date,Site,Quantity,UOM,MRP,Base Cost,CGST(%),SGST(%),CGST(INR),SGST(INR),Total Base Value(INR)
0,490003346,33051090,8901138002466,406074.0,HIMALAYA AD TEA TREE SHAMPOO 180ML PET,21.06.2023,SK6C,"[2, 48]","[CRT, EA]","[3600.00, 150]",2394.91,9.0,9.0,431.08,431.08,4789.83
1,490003407,33049120,8901138511814,NaN,HIMALAYA BABY POWDER 100 g BTL,21.06.2023,SK6C,"[4, 144]","[C07, EA]","[3420.00, 95]",1970.85,9.0,9.0,709.51,709.51,7883.39
2,490766695,33051090,8901138002428,943920.0,HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET,21.06.2023,SK6C,"[1, 12]","[CAR, EA]","[3360.00, 280]",2235.25,9.0,9.0,201.17,201.17,2235.25
3,490782407,33049120,8901138513153,NaN,HIMALAYA BABY POWDER 200 g BTL,21.06.2023,SK6C,"[5, 120]","[C07, EA]","[3600.00, 150]",2074.58,9.0,9.0,933.56,933.56,10372.88
4,490819102,33041000,8901138819668,406097.0,HIMALAYA HER FAIRNES KESAR FW 100ml TUBE,21.06.2023,SK6C,"[1, 30]","[CAR, EA]","[4470.00, 149]",2973.69,9.0,9.0,267.63,267.63,2973.69
5,491249578,34011110,8901138714628,944069.0,HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP,21.06.2023,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
6,491249580,34011110,8901138827885,944068.0,HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD,21.06.2023,SK6C,"[1, 48]","[CAR, EA]","[6384.00, 133]",4246.98,9.0,9.0,382.23,382.23,4246.98
7,491321625,34011110,8901138714611,944071.0,HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD,21.06.2023,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
8,491903304,33059011,8901138845476,943744.0,HIM BABY HAIR OIL 100 ml PET,21.06.2023,SK6C,"[1, 48]","[C07, EA]","[6240.00, 130]",3595.93,9.0,9.0,323.63,323.63,3595.93
9,492367878,33049990,8901138848484,NaN,HIMALAYA ALE VERA FCE GEL 100ML CON,21.06.2023,SK6C,"[1, 24]","[CAR, EA]","[2040.00, 85]",1357.12,9.0,9.0,122.14,122.14,1357.12

In [50]:
table_data_df.dtypes

No                          int64
Article No.                 int64
HSN/SAC Code                int64
EAN No                      int64
Vendor Article No         float64
Material Description       object
Delivery Date              object
Site                       object
Quantity                   object
UOM                        object
MRP                        object
Base Cost                 float64
CGST(%)                   float64
SGST(%)                   float64
CGST(INR)                 float64
SGST(INR)                 float64
Total Base  Value(INR)    float64
dtype: object

In [20]:
gstin_no_pattern = re.compile(r"GSTIN NO : (.+)")
gst_matched = gstin_no_pattern.search(text)
extracted_data["GSTIN NO"] = gst_matched.group(1).strip() if gst_matched else "GSTIN NOT FOUND"
extracted_data

{'GSTIN NO': '24AABCR1718E1ZV'}

In [21]:
pan_no_pattern = re.compile(r"PAN No. : (.+)")
pan_no_matched = pan_no_pattern.search(text)
extracted_data["PAN NO"] = pan_no_matched.group(1).strip(' \r') if pan_no_matched else "PAN NOT FOUND"
extracted_data

{'GSTIN NO': '24AABCR1718E1ZV', 'PAN NO': 'AABCR1718E'}

In [22]:
organization_name_pattern = re.compile(r"(?:(?:.*\n){5})Telephone : (.+)")
org_details_matched = organization_name_pattern.search(text)
if org_details_matched:
    org_name_and_address = org_details_matched.group().strip().split("\n")
    org_name = org_name_and_address[0].strip(" \r") if org_name_and_address else "Organization Not Found"
    org_address = ""
    for add in org_name_and_address[1:-1]:
        org_address += add.strip() + "\n"
    org_address = org_address.strip(" \r")
else:
    org_name = "Organization Not Found"
    org_address = "Address Not Found"
    
extracted_data["NAME"] = org_name
extracted_data["ADDRESS"]= org_address

# print("Organization Name:", org_name)
# print("Address:\n"+org_address)
extracted_data

{'GSTIN NO': '24AABCR1718E1ZV',
 'PAN NO': 'AABCR1718E',
 'NAME': 'RELIANCE RETAIL LIMITED',
 'ADDRESS': 'FF101,Saffron\nPanchwati 5 Rasta,\nNear Bank of Baroda Ambawadi,\nAhmedabad , 380006 GJ , IN\n'}

In [19]:
# seller_pattern = re.compile(r"(?:(?:.*\n){8})Attention :")
# seller_text = seller_pattern.search(text)
# if seller_text:
#     order_details = seller_text.group(0)
    
#     ordered_company_code_pattern = re.compile(r"(.+?)\s*Original Order No")
#     ordered_company_pattern = re.compile(r"(.+?)\s*Revision No")
#     ordered_company_address_pattern = re.compile(r"(.+?)\s*Date")
    
#     order_no_pattern = re.compile(r"Original Order No.:(.+)")
#     revision_no_pattern = re.compile(r"Revision No. : (\d+)")
    
    
    
    

#     ordered_company_code_match = ordered_company_code_pattern.search(order_details)
#     ordered_company_match = ordered_company_pattern.search(order_details)
#     ordered_company_address_match = ordered_company_address_pattern.search(order_details)
    
    
#     order_no_match = order_no_pattern.search(order_details)
#     revision_no_match = revision_no_pattern.search(order_details)
#     delivery_date_match = re.compile(r"Date (.+)").search(order_details)
#     address_match = re.compile(r"(.*\s)Delv Add").search(order_details)

    
    

    
#     ordered_company_code = ordered_company_code_match.group().strip().split()[0] if ordered_company_code_match else "Company code not found"
#     ordered_company = " ".join(ordered_company_match.group().strip().split()[:-2]) if ordered_company_match else "Company not found"
#     ordered_company_address = [" ".join(ordered_company_address_match.group().strip().split()[:-1]),] if ordered_company_address_match else "Company address not found"
#     ordered_company_address.append(" ".join(address_match.group().strip().split()[:-2]))
    
#     order_no = order_no_match.group(1).strip() if order_no_match else "Order No not found"
#     revision_no = revision_no_match.group(1).strip() if revision_no_match else "Revision No not found"
#     delivery_date = delivery_date_match.group().strip() if delivery_date_match else "Delivery date not found"
    

#     print(ordered_company_code, end="\t\t\t" )
#     print("Order Number:", order_no)
#     print(ordered_company, end="\t")
#     print("Revision Number:", revision_no)
#     print("\n".join(ordered_company_address), end="\t\t\t")
#     print("Date:", delivery_date)
    
    


# else:
#     pass

In [23]:
org_price_pattern = re.compile(r"Original/Previous Total Purchase Order Price : (.+)")
revised_total_price_pattern = re.compile(r"Revised Total Purchase Order Price : (.+)")
delivery_date_pattern = re.compile(r"Delivery Date (.+)")

org_price_match = org_price_pattern.search(text)
revised_total_price_match = revised_total_price_pattern.search(text)
delivery_date_match = delivery_date_pattern.search(text)

org_price = org_price_match.group().split()[-1] if org_price_match else 0
revised_price = revised_total_price_match.group().split()[-1] if revised_total_price_match else 0
delivery_date = delivery_date_match.group(1).strip(" \r") if delivery_date_match else "not found"

extracted_data["ORIGINAL PRICE"] = org_price 
extracted_data["REVISED PRICE"] = revised_price
extracted_data["DELIVERY DATE"]= delivery_date
print("orginal price :", org_price)
print("Revised Price :", revised_price)
print("Delivery Date: ", delivery_date)
extracted_data

orginal price : 98,322.18
Revised Price : 98,322.18
Delivery Date:  21.06.2023

{'GSTIN NO': '24AABCR1718E1ZV',
 'PAN NO': 'AABCR1718E',
 'NAME': 'RELIANCE RETAIL LIMITED',
 'ADDRESS': 'FF101,Saffron\nPanchwati 5 Rasta,\nNear Bank of Baroda Ambawadi,\nAhmedabad , 380006 GJ , IN\n',
 'ORIGINAL PRICE': '98,322.18',
 'REVISED PRICE': '98,322.18',
 'DELIVERY DATE': '21.06.2023'}

In [21]:
import tabula 
 
tables = tabula.read_pdf("0000704860_2023_06_14_01_00_01_PM.pdf", pages="all", multiple_tables=True)
tables

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'

[  10004504\rHimalaya Wellness Company\r\r1 Ashish Estate\rN H No 8 Aslali\rTHE HIMALA\rAHMEDABAD GUJARAT\rPin Code: 382427 ven_country&\rAttention :\rTel.No.   :\rE-Mail.   : cfa.ahm.kbshah@himalayahe  \
 0  AMENDED PURCHASE ORDER - DO NOT DUPLICATE\rThi...

    Original Order No.:SK6C/9200025737\rRevision No. : 0001\rDate : 14.06.2023\rDelv Add :\rWh No 2 Uno Logistics Park\rVillage Kochariya Bavla\rRajkot Highway\r\rAHMEDABAD, Gujarat - 382220\rlthcare.comTel:/Fax:\rEmail:
 0                                                NaN                                                                                                                                                                         ]

In [24]:
from tabula import read_pdf

tables = str(read_pdf("0000704860_2023_06_14_01_00_01_PM.pdf", pages="1", multiple_tables=True))

addresses = tables.split("\n")[::3]
from_address = addresses[0].split("\\r")
to_address = addresses[1].split("\\r")
shipping_address = ""
for item in from_address:
    stripped = item.strip('[\\ ')
    if len(stripped) > 0:
        shipping_address += stripped + "\n"

shipping_address_arr = shipping_address.split("\n")
seller_code = shipping_address_arr[0]
seller_name = shipping_address_arr[1]
seller_address = "\n".join(shipping_address_arr[2:])


delivery_address = ""
for item in to_address:
    stripped = item.strip('[\\ ')
    if len(stripped) > 0:
        delivery_address += stripped + "\n"
deliver_address_arr = delivery_address.split("\n")
order_no = deliver_address_arr[0]
revision_no = deliver_address_arr[1]
ordered_date = deliver_address_arr[2]
del_address = "\n".join(deliver_address_arr[3:])
extracted_data["CODE"]= seller_code
extracted_data["NAME"] = seller_name
extracted_data["ADDRESS"] = seller_address
extracted_data["ORIGINAL ORDER NO"] = order_no
extracted_data["REVISION NO"] = revision_no
extracted_data["ORDER DATE"]= ordered_date
extracted_data["DELIVERY ADDRESS"] = del_address

print(extracted_data)

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'

{'GSTIN NO': '24AABCR1718E1ZV', 'PAN NO': 'AABCR1718E', 'NAME': 'Himalaya Wellness Company', 'ADDRESS': '1 Ashish Estate\nN H No 8 Aslali\nTHE HIMALA\nAHMEDABAD GUJARAT\nPin Code: 382427 ven_country&\nAttention :\nTel.No.   :\nE-Mail.   : cfa.ahm.kbshah@himalayahe\n', 'ORIGINAL PRICE': '98,322.18', 'REVISED PRICE': '98,322.18', 'DELIVERY DATE': '21.06.2023', 'CODE': '10004504', 'ORIGINAL ORDER NO': 'Original Order No.:SK6C/9200025737', 'REVISION NO': 'Revision No. : 0001', 'ORDER DATE': 'Date : 14.06.2023', 'DELIVERY ADDRESS': 'Delv Add :\nWh No 2 Uno Logistics Park\nVillage Kochariya Bavla\nRajkot Highway\nAHMEDABAD, Gujarat - 382220\nlthcare.comTel:/Fax:\nEmail:\n'}

In [26]:

import pandas as pd

df = pd.DataFrame([extracted_data])
df

,GSTIN NO,PAN NO,NAME,ADDRESS,ORIGINAL PRICE,REVISED PRICE,DELIVERY DATE,CODE,ORIGINAL ORDER NO,REVISION NO,ORDER DATE,DELIVERY ADDRESS
0,24AABCR1718E1ZV,AABCR1718E,Himalaya Wellness Company,1 Ashish Estate\nN H No 8 Aslali\nTHE HIMALA\n...,"98,322.18","98,322.18",21.06.2023,10004504,Original Order No.:SK6C/9200025737,Revision No. : 0001,Date : 14.06.2023,Delv Add :\nWh No 2 Uno Logistics Park\nVillag...

In [24]:
import camelot

In [54]:

from tabula import read_pdf
from tabulate import tabulate
 
#reads table from pdf file
df = read_pdf("0000704860_2023_06_14_01_00_01_PM.PDF", pages="all") #address of pdf file
print(df)

[  10004504\rHimalaya Wellness Company\r\r1 Ashish Estate\rN H No 8 Aslali\rTHE HIMALA\rAHMEDABAD GUJARAT\rPin Code: 382427 ven_country&\rAttention :\rTel.No.   :\rE-Mail.   : cfa.ahm.kbshah@himalayahe  \
0  AMENDED PURCHASE ORDER - DO NOT DUPLICATE\rThi...

   Original Order No.:SK6C/9200025737\rRevision No. : 0001\rDate : 14.06.2023\rDelv Add :\rWh No 2 Uno Logistics Park\rVillage Kochariya Bavla\rRajkot Highway\r\rAHMEDABAD, Gujarat - 382220\rlthcare.comTel:/Fax:\rEmail:
0                                                NaN                                                                                                                                                                         ]

In [63]:
import camelot

abc = camelot.read_pdf("0000704860_2023_06_14_01_00_01_PM.PDF", pages="all")

print(abc)

DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.

In [76]:
from pypdf import PdfReader
pypdf_file = PdfReader("0000704860_2023_06_14_01_00_01_PM.PDF")
pages = pypdf_file.pages[1].extract_text() + pypdf_file.pages[2].extract_text()
print(pages)

_______________________________ _______________________________ _______________________________ _________________
No Article No. EAN No Material Description Quantity   UOM MRP Base Cost CGST(%) CGST(INR) Total Base
HSN/SAC Code Vendor Article No Delivery Date  SGST(%)  SGST(INR) Value(INR)
 Vendor Item No Site   CESS(%) CESS(INR)_______________________________ _______________________________ _______________________________ _________________
1 490003346 8901138002466 HIMALAYA AD TEA TREE SHAMPOO 180ML PET           2 CRT       3600.00              2,394.91      9.00           431.08              4,789.83
33051090 406074 21.06.2023        9.00            431.08
  SK6C
        48 EA        150.00_______________________________ _______________________________ _______________________________ _________________
2 490003407 8901138511814 HIMALAYA BABY POWDER 100 g BTL           4 C07       3420.00              1,970.85      9.00           709.51              7,883.39
33049120 21.06.2023        9.00            709.51
  SK6C
       144 EA        95.00_______________________________ _______________________________ _______________________________ _________________
3 490766695 8901138002428 HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET           1 CAR       3360.00              2,235.25      9.00           201.17              2,235.25
33051090 943920 21.06.2023        9.00            201.17
  SK6C
        12 EA        280.00_______________________________ _______________________________ _______________________________ _________________
4 490782407 8901138513153 HIMALAYA BABY POWDER 200 g BTL           5 C07       3600.00              2,074.58      9.00           933.56             10,372.88
33049120 21.06.2023        9.00            933.56
  SK6C
       120 EA        150.00_______________________________ _______________________________ _______________________________ _________________
5 490819102 8901138819668 HIMALAYA HER FAIRNES KESAR FW 100ml TUBE           1 CAR       4470.00              2,973.69      9.00           267.63              2,973.69
33041000 406097 21.06.2023        9.00            267.63
  SK6C
        30 EA        149.00_______________________________ _______________________________ _______________________________ _________________
6 491238725 8901138824037 HIMALAYA BABY POWDER 400 g BTL          11 C07       5000.00              2,881.36      9.00         2,852.54             31,694.92
33049120 21.06.2023        9.00          2,852.54
  SK6C
       220 EA        250.00_______________________________ _______________________________ _______________________________ _________________
7 491249578 8901138714628 HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP           1 CAR       6360.00              4,231.02      9.00           380.79              4,231.02
34011110 944069 21.06.2023        9.00            380.79
  SK6C
        30 EA        212.00_______________________________ _______________________________ _______________________________ _________________
8 491249580 8901138827885 HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD           1 CAR       6384.00              4,246.98      9.00           382.23              4,246.98
34011110 944068 21.06.2023        9.00            382.23
  SK6C
        48 EA        133.00_______________________________ _______________________________ _______________________________ _________________
9 491296367 8901138836306 HIMALAYA COMPL CARE TTPST 2N X150 g TUBE           3 CAR       2862.00              1,903.96      9.00           514.07              5,711.87
33061020 943929 21.06.2023        9.00            514.07
 1088 SK6C
        54 EA        159.00_______________________________ _______________________________ _______________________________ _________________AMENDED PURCHASE ORDER Number 9200025737
Rev : 0001  Dt.14.06.2023      Page No: 1_______________________________ _______________________________ _______________________________ _________________
No Article No. EAN No Material Description Quantity   UOM MRP Base Cost CGST(%) CGST(INR) Total Base
HSN/SAC Code Vendor Article No Delivery Date  SGST(%)  SGST(INR) Value(INR)
 Vendor Item No Site   CESS(%) CESS(INR)_______________________________ _______________________________ _______________________________ _________________
10 491321625 8901138714611 HIMALAYA ALMOND & ROSE SOAP 125  G X4 CBD           1 CAR       6360.00              4,231.02      9.00           380.79              4,231.02
34011110 944071 21.06.2023        9.00            380.79
  SK6C
        30 EA        212.00_______________________________ _______________________________ _______________________________ _________________
11 491903304 8901138845476 HIM BABY HAIR OIL 100 ml PET           1 C07       6240.00              3,595.93      9.00           323.63              3,595.93
33059011 943744 21.06.2023        9.00            323.63
  SK6C
        48 EA        130.00_______________________________ _______________________________ _______________________________ _________________
12 492367878 8901138848484 HIMALAYA ALE VERA FCE GEL 100ML  CON           1 CAR       2040.00              1,357.12      9.00           122.14              1,357.12
33049990 21.06.2023        9.00            122.14
  SK6C
        24 EA        85.00_______________________________ _______________________________ _______________________________ _________________
Grand Total  =         32_______________________________ _______________________________ _______________________________ _________________
Total Basic Value INR        83,323.90
Total CGST INR         7,499.14
Total SGST INR         7,499.14
_______________________________ _______________________________ _______________________________ _________________
Revised Total Purchase Order Price: INR            98322.18
Original/Previous Total Purchase Order Price: INR            98322.18
Amendment to the Total Price as  a result of this Revision INR               0.00_______________________________ _______________________________ _______________________________ _________________
Terms of payment  :
Pro-rata payment(s) shall be made within 30 days from the date of receipt of GOODS, or receipt of correct invoice & dispatch documents whichever is  later.AMENDED PURCHASE ORDER Number 9200025737
Rev : 0001  Dt.14.06.2023      Page No: 2

In [69]:
from tabula import read_pdf

# Provide the path to your PDF file
pdf_path = r"C:\Users\TP_USER\Downloads\0000704860_2023_06_14_01_00_01_PM (2).pdf"

# Extract tables from the PDF
tables = read_pdf(pdf_path, pages="all")

# Print the extracted tables
for table in tables:
    print(table)

  10004504\rHimalaya Wellness Company\r\r1 Ashish Estate\rN H No 8 Aslali\rTHE HIMALA\rAHMEDABAD GUJARAT\rPin Code: 382427 ven_country&\rAttention :\rTel.No.   :\rE-Mail.   : cfa.ahm.kbshah@himalayahe  \
0  AMENDED PURCHASE ORDER - DO NOT DUPLICATE\rThi...

   Original Order No.:SK6C/9200025737\rRevision No. : 0001\rDate : 14.06.2023\rDelv Add :\rWh No 2 Uno Logistics Park\rVillage Kochariya Bavla\rRajkot Highway\r\rAHMEDABAD, Gujarat - 382220\rlthcare.comTel:/Fax:\rEmail:
0                                                NaN

In [107]:
all_pdfs = ["0000704860_2023_06_14_01_00_01_PM.pdf", "0000704860_2023_06_14_12_30_49_PM.pdf", "0000704860_2023_06_14_12_47_34_PM.pdf", "1582693520229_1_0000711842_2020_02_26_10_34_57_AM.pdf"]

In [108]:
from ironpdf import PdfDocument
from tabula import read_pdf
import ironpdf
import re
import pandas as pd

In [109]:
def extract_info(pdf):
    pdf_file = PdfDocument.FromFile(pdf)
    ironpdf.License.LicenseKey = "IRONSUITE.LAXMIPRASANNA.PEDDAGUTTA.TALENTPACE.COM.13840-9CE3F82042-HW4SM7G2WAPTPW-YB6CB2C5IZEK-JR5YG7PRGQ43-Y3GY5YXY63J7-72T3FSGQY3G5-PAPKW6LTCHEH-3GOMZY-TOQBWFPCF6WLUA-DEPLOYMENT.TRIAL-Y2KBWZ.TRIAL.EXPIRES.13.MAR.2024"
    text = pdf_file.ExtractAllText()
    extracted_data = dict()
    
    gstin_no_pattern = re.compile(r"GSTIN NO : (.+)")
    gst_matched = gstin_no_pattern.search(text)
    extracted_data["GSTIN No"] = gst_matched.group(1).strip() if gst_matched else "GSTIN NOT FOUND"
    
    pan_no_pattern = re.compile(r"PAN No. : (.+)")
    pan_no_matched = pan_no_pattern.search(text)
    extracted_data["PAN No"] = pan_no_matched.group(1).strip(' \r') if pan_no_matched else "PAN NOT FOUND"
    
    organization_name_pattern = re.compile(r"(?:(?:.*\n){5})Telephone : (.+)")
    org_details_matched = organization_name_pattern.search(text)
    if org_details_matched:
        org_name_and_address = org_details_matched.group().strip().split("\n")
        org_name = org_name_and_address[0].strip(" \r") if org_name_and_address else "Organization Not Found"
        org_address = ""
        for add in org_name_and_address[1:-1]:
            org_address += add.strip() + "\n"
        org_address = org_address.strip(" \r")
    else:
        org_name = "Organization Not Found"
        org_address = "Address Not Found"

    extracted_data["Organization Name"] = org_name
    extracted_data["Organization Address"]= org_address
    
    org_price_pattern = re.compile(r"Original/Previous Total Purchase Order Price : (.+)")
    revised_total_price_pattern = re.compile(r"Revised Total Purchase Order Price : (.+)")
    delivery_date_pattern = re.compile(r"Delivery Date (.+)")

    org_price_match = org_price_pattern.search(text)
    revised_total_price_match = revised_total_price_pattern.search(text)
    delivery_date_match = delivery_date_pattern.search(text)

    org_price = org_price_match.group().split()[-1] if org_price_match else 0
    revised_price = revised_total_price_match.group().split()[-1] if revised_total_price_match else 0
    delivery_date = delivery_date_match.group(1).strip(" \r") if delivery_date_match else "not found"

    extracted_data["Original Price(INR)"] = org_price 
    extracted_data["Revised Price(INR)"] = revised_price
    extracted_data["Delivery Date"]= delivery_date
    
    tables = str(read_pdf(pdf, pages="1", multiple_tables=True))

    addresses = tables.split("\n")[::3]
    from_address = addresses[0].split("\\r")
    to_address = addresses[1].split("\\r")
    shipping_address = ""
    for item in from_address:
        stripped = item.strip('[\\ ')
        if len(stripped) > 0:
            shipping_address += stripped + "\n"

    shipping_address_arr = shipping_address.split("\n")
    seller_code = shipping_address_arr[0]
    seller_name = shipping_address_arr[1]
    seller_address = "\n".join(shipping_address_arr[2:])


    delivery_address = ""
    for item in to_address:
        stripped = item.strip('[\\ ')
        if len(stripped) > 0:
            delivery_address += stripped + "\n"
    deliver_address_arr = delivery_address.split("\n")
    order_no = deliver_address_arr[0]
    revision_no = deliver_address_arr[1]
    ordered_date = deliver_address_arr[2]
    del_address = "\n".join(deliver_address_arr[3:])
    extracted_data["Seller Code"]= seller_code
    extracted_data["Seller Name"] = seller_name
    extracted_data["Seller Address"] = seller_address
    extracted_data["Original Order No"] = order_no.split(":")[-1]
    extracted_data["Order Revision No"] = revision_no.split(":")[-1]
    extracted_data["Order Date"]= ordered_date.split(":")[-1]
    extracted_data["Delivery Address"] =" ".join([item for item in del_address.split(":")[1:]]).strip("\n")
    
    extracted_info = pd.DataFrame([extracted_data])
    return extracted_info

In [110]:
dfs = []
for pdf in all_pdfs:
    dfs.append(extract_info(pdf))

In [111]:
dfs[0]

,GSTIN No,PAN No,Organization Name,Organization Address,Original Price(INR),Revised Price(INR),Delivery Date,Seller Code,Seller Name,Seller Address,Original Order No,Order Revision No,Order Date,Delivery Address
0,24AABCR1718E1ZV,AABCR1718E,RELIANCE RETAIL LIMITED,"FF101,Saffron\nPanchwati 5 Rasta,\nNear Bank o...","98,322.18","98,322.18",21.06.2023,10004504,Himalaya Wellness Company,1 Ashish Estate\nN H No 8 Aslali\nTHE HIMALA\n...,SK6C/9200025737,0001,14.06.2023,Wh No 2 Uno Logistics Park\nVillage Kochariya ...

In [112]:
dfs[1]

,GSTIN No,PAN No,Organization Name,Organization Address,Original Price(INR),Revised Price(INR),Delivery Date,Seller Code,Seller Name,Seller Address,Original Order No,Order Revision No,Order Date,Delivery Address
0,24AABCR1718E1ZV,AABCR1718E,RELIANCE RETAIL LIMITED,"FF101,Saffron\nPanchwati 5 Rasta,\nNear Bank o...","98,322.18","98,322.18",21.06.2023,10004504,Himalaya Wellness Company,1 Ashish Estate\nN H No 8 Aslali\nTHE HIMALA\n...,SK6C/9200025737,0001,14.06.2023,Wh No 2 Uno Logistics Park\nVillage Kochariya ...

In [113]:
dfs[2]

,GSTIN No,PAN No,Organization Name,Organization Address,Original Price(INR),Revised Price(INR),Delivery Date,Seller Code,Seller Name,Seller Address,Original Order No,Order Revision No,Order Date,Delivery Address
0,24AABCR1718E1ZV,AABCR1718E,RELIANCE RETAIL LIMITED,"FF101,Saffron\nPanchwati 5 Rasta,\nNear Bank o...","98,322.18","98,322.18",21.06.2023,10004504,Himalaya Wellness Company,1 Ashish Estate\nN H No 8 Aslali\nTHE HIMALA\n...,SK6C/9200025737,0001,14.06.2023,Wh No 2 Uno Logistics Park\nVillage Kochariya ...

In [114]:
def extract_tables(pdf):
    table_rows_data = []

    data_to_exclude = re.compile(r'AMENDED PURCHASE ORDER Number (.+)\r\nRev : (.+)\r\n Page No: (.+) CESS\(INR\)',re.DOTALL)
    text_excluded = re.sub(data_to_exclude, "", text)
    table_data_matched = re.compile(r"CESS\(INR\) (.+)Grand Total", re.DOTALL).search(text_excluded)
    if table_data_matched:

        table_data_splitted = table_data_matched.group(1).strip().split('______________________________________________________________________________________________________________')
        table_data = [data for data in table_data_splitted if len(data)>3]
        for row in table_data:
            row_pattern = re.compile(r"\b(\d+)\s(\d+)\s(\d+)\s(.+?(?:PET|BTL|TUBE|WRP|CBD|CON))\s(\d+)\s(\w+)\s(\d+\.\d+)\s(\d+,\d+\.\d+)\s(\d+\.\d+)\s(\d+\.\d+)\s(\d+\,\d+\.\d+)\s\n(\d+)\s(\d+)?\s?(\d+\.\d+\.\d+)\s(\d+\.\d+)\s(\d+\.\d+)\s\n(\w+)\s\n\s(\d+)\s(\w+)\s(\d+)\b")

            matches = row_pattern.findall(row)

            formatted_matches = []
            for match in matches:
                elements = []
                for element in match:
                    elements.append(element)
                formatted_matches.append(elements)
            for match in formatted_matches:
                row_dict = dict()
                row_dict["Article No."] = int(match[1])
                row_dict["HSN/SAC Code"] = int(match[11])

                row_dict["EAN No"] = int(match[2])
                row_dict["Vendor Article No"] = int(match[12]) if len(match[12])>2 else None
                row_dict["Material Description"] = match[3]
                row_dict["Delivery Date"] = match[13] if len(match[13]) == 10 else match[12]+match[13]
                row_dict["Site"] = match[16]

                row_dict["Quantity"] = [match[4],match[17]]
                row_dict["UOM"] = [match[5],match[18]]
                row_dict["MRP"] = [match[6],match[19]]
                row_dict["Base Cost"] = float(''.join(match[7].split(",")))
                row_dict["CGST(%)"] = float(match[8])
                row_dict["SGST(%)"] = float(match[14])

                row_dict["CGST(INR)"] = float(match[9])
                row_dict["SGST(INR)"] = float(match[15])
                row_dict["Total Base  Value(INR)"] = float(''.join(match[10].split(",")))
                table_rows_data.append(row_dict)




    else:
        print("No Data Found")


    table_data_df = pd.DataFrame(table_rows_data)
    table_data_df["Delivery Date"] = pd.to_datetime(table_data_df["Delivery Date"])
    return table_data_df

In [115]:
all_tables = []
for pdf in all_pdfs:
    all_tables.append(extract_tables(pdf))

C:\Users\TP_USER\AppData\Local\Temp\ipykernel_1752\928020265.py:53: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  table_data_df["Delivery Date"] = pd.to_datetime(table_data_df["Delivery Date"])
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_1752\928020265.py:53: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  table_data_df["Delivery Date"] = pd.to_datetime(table_data_df["Delivery Date"])
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_1752\928020265.py:53: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  table_data_df["Delivery Date"] = pd.to_datetime(table_data_df["Delivery Date"])
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_1752\928020265.py:53: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  table_data_df["Delivery Date"] = pd.to_datetime(table_data_df["Delivery Date"])

In [116]:
all_tables[0]

,Article No.,HSN/SAC Code,EAN No,Vendor Article No,Material Description,Delivery Date,Site,Quantity,UOM,MRP,Base Cost,CGST(%),SGST(%),CGST(INR),SGST(INR),Total Base Value(INR)
0,490003346,33051090,8901138002466,406074.0,HIMALAYA AD TEA TREE SHAMPOO 180ML PET,2023-06-21,SK6C,"[2, 48]","[CRT, EA]","[3600.00, 150]",2394.91,9.0,9.0,431.08,431.08,4789.83
1,490003407,33049120,8901138511814,NaN,HIMALAYA BABY POWDER 100 g BTL,2023-06-21,SK6C,"[4, 144]","[C07, EA]","[3420.00, 95]",1970.85,9.0,9.0,709.51,709.51,7883.39
2,490766695,33051090,8901138002428,943920.0,HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET,2023-06-21,SK6C,"[1, 12]","[CAR, EA]","[3360.00, 280]",2235.25,9.0,9.0,201.17,201.17,2235.25
3,490782407,33049120,8901138513153,NaN,HIMALAYA BABY POWDER 200 g BTL,2023-06-21,SK6C,"[5, 120]","[C07, EA]","[3600.00, 150]",2074.58,9.0,9.0,933.56,933.56,10372.88
4,490819102,33041000,8901138819668,406097.0,HIMALAYA HER FAIRNES KESAR FW 100ml TUBE,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[4470.00, 149]",2973.69,9.0,9.0,267.63,267.63,2973.69
5,491249578,34011110,8901138714628,944069.0,HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
6,491249580,34011110,8901138827885,944068.0,HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD,2023-06-21,SK6C,"[1, 48]","[CAR, EA]","[6384.00, 133]",4246.98,9.0,9.0,382.23,382.23,4246.98
7,491321625,34011110,8901138714611,944071.0,HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
8,491903304,33059011,8901138845476,943744.0,HIM BABY HAIR OIL 100 ml PET,2023-06-21,SK6C,"[1, 48]","[C07, EA]","[6240.00, 130]",3595.93,9.0,9.0,323.63,323.63,3595.93
9,492367878,33049990,8901138848484,NaN,HIMALAYA ALE VERA FCE GEL 100ML CON,2023-06-21,SK6C,"[1, 24]","[CAR, EA]","[2040.00, 85]",1357.12,9.0,9.0,122.14,122.14,1357.12

In [117]:
all_tables[1]

,Article No.,HSN/SAC Code,EAN No,Vendor Article No,Material Description,Delivery Date,Site,Quantity,UOM,MRP,Base Cost,CGST(%),SGST(%),CGST(INR),SGST(INR),Total Base Value(INR)
0,490003346,33051090,8901138002466,406074.0,HIMALAYA AD TEA TREE SHAMPOO 180ML PET,2023-06-21,SK6C,"[2, 48]","[CRT, EA]","[3600.00, 150]",2394.91,9.0,9.0,431.08,431.08,4789.83
1,490003407,33049120,8901138511814,NaN,HIMALAYA BABY POWDER 100 g BTL,2023-06-21,SK6C,"[4, 144]","[C07, EA]","[3420.00, 95]",1970.85,9.0,9.0,709.51,709.51,7883.39
2,490766695,33051090,8901138002428,943920.0,HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET,2023-06-21,SK6C,"[1, 12]","[CAR, EA]","[3360.00, 280]",2235.25,9.0,9.0,201.17,201.17,2235.25
3,490782407,33049120,8901138513153,NaN,HIMALAYA BABY POWDER 200 g BTL,2023-06-21,SK6C,"[5, 120]","[C07, EA]","[3600.00, 150]",2074.58,9.0,9.0,933.56,933.56,10372.88
4,490819102,33041000,8901138819668,406097.0,HIMALAYA HER FAIRNES KESAR FW 100ml TUBE,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[4470.00, 149]",2973.69,9.0,9.0,267.63,267.63,2973.69
5,491249578,34011110,8901138714628,944069.0,HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
6,491249580,34011110,8901138827885,944068.0,HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD,2023-06-21,SK6C,"[1, 48]","[CAR, EA]","[6384.00, 133]",4246.98,9.0,9.0,382.23,382.23,4246.98
7,491321625,34011110,8901138714611,944071.0,HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
8,491903304,33059011,8901138845476,943744.0,HIM BABY HAIR OIL 100 ml PET,2023-06-21,SK6C,"[1, 48]","[C07, EA]","[6240.00, 130]",3595.93,9.0,9.0,323.63,323.63,3595.93
9,492367878,33049990,8901138848484,NaN,HIMALAYA ALE VERA FCE GEL 100ML CON,2023-06-21,SK6C,"[1, 24]","[CAR, EA]","[2040.00, 85]",1357.12,9.0,9.0,122.14,122.14,1357.12

In [118]:
all_tables[2]

,Article No.,HSN/SAC Code,EAN No,Vendor Article No,Material Description,Delivery Date,Site,Quantity,UOM,MRP,Base Cost,CGST(%),SGST(%),CGST(INR),SGST(INR),Total Base Value(INR)
0,490003346,33051090,8901138002466,406074.0,HIMALAYA AD TEA TREE SHAMPOO 180ML PET,2023-06-21,SK6C,"[2, 48]","[CRT, EA]","[3600.00, 150]",2394.91,9.0,9.0,431.08,431.08,4789.83
1,490003407,33049120,8901138511814,NaN,HIMALAYA BABY POWDER 100 g BTL,2023-06-21,SK6C,"[4, 144]","[C07, EA]","[3420.00, 95]",1970.85,9.0,9.0,709.51,709.51,7883.39
2,490766695,33051090,8901138002428,943920.0,HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET,2023-06-21,SK6C,"[1, 12]","[CAR, EA]","[3360.00, 280]",2235.25,9.0,9.0,201.17,201.17,2235.25
3,490782407,33049120,8901138513153,NaN,HIMALAYA BABY POWDER 200 g BTL,2023-06-21,SK6C,"[5, 120]","[C07, EA]","[3600.00, 150]",2074.58,9.0,9.0,933.56,933.56,10372.88
4,490819102,33041000,8901138819668,406097.0,HIMALAYA HER FAIRNES KESAR FW 100ml TUBE,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[4470.00, 149]",2973.69,9.0,9.0,267.63,267.63,2973.69
5,491249578,34011110,8901138714628,944069.0,HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
6,491249580,34011110,8901138827885,944068.0,HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD,2023-06-21,SK6C,"[1, 48]","[CAR, EA]","[6384.00, 133]",4246.98,9.0,9.0,382.23,382.23,4246.98
7,491321625,34011110,8901138714611,944071.0,HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
8,491903304,33059011,8901138845476,943744.0,HIM BABY HAIR OIL 100 ml PET,2023-06-21,SK6C,"[1, 48]","[C07, EA]","[6240.00, 130]",3595.93,9.0,9.0,323.63,323.63,3595.93
9,492367878,33049990,8901138848484,NaN,HIMALAYA ALE VERA FCE GEL 100ML CON,2023-06-21,SK6C,"[1, 24]","[CAR, EA]","[2040.00, 85]",1357.12,9.0,9.0,122.14,122.14,1357.12

In [119]:
all_tables[3]

,Article No.,HSN/SAC Code,EAN No,Vendor Article No,Material Description,Delivery Date,Site,Quantity,UOM,MRP,Base Cost,CGST(%),SGST(%),CGST(INR),SGST(INR),Total Base Value(INR)
0,490003346,33051090,8901138002466,406074.0,HIMALAYA AD TEA TREE SHAMPOO 180ML PET,2023-06-21,SK6C,"[2, 48]","[CRT, EA]","[3600.00, 150]",2394.91,9.0,9.0,431.08,431.08,4789.83
1,490003407,33049120,8901138511814,NaN,HIMALAYA BABY POWDER 100 g BTL,2023-06-21,SK6C,"[4, 144]","[C07, EA]","[3420.00, 95]",1970.85,9.0,9.0,709.51,709.51,7883.39
2,490766695,33051090,8901138002428,943920.0,HMLY BHRNGRJ&BTFD ANT HRFL SMP 400ML PET,2023-06-21,SK6C,"[1, 12]","[CAR, EA]","[3360.00, 280]",2235.25,9.0,9.0,201.17,201.17,2235.25
3,490782407,33049120,8901138513153,NaN,HIMALAYA BABY POWDER 200 g BTL,2023-06-21,SK6C,"[5, 120]","[C07, EA]","[3600.00, 150]",2074.58,9.0,9.0,933.56,933.56,10372.88
4,490819102,33041000,8901138819668,406097.0,HIMALAYA HER FAIRNES KESAR FW 100ml TUBE,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[4470.00, 149]",2973.69,9.0,9.0,267.63,267.63,2973.69
5,491249578,34011110,8901138714628,944069.0,HIMALAYA NEEM&TURMRC BTH SOAP125GX4N WRP,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
6,491249580,34011110,8901138827885,944068.0,HIMALAYA NEEM & TURMERIC SOAP 75GX4N CBD,2023-06-21,SK6C,"[1, 48]","[CAR, EA]","[6384.00, 133]",4246.98,9.0,9.0,382.23,382.23,4246.98
7,491321625,34011110,8901138714611,944071.0,HIMALAYA ALMOND & ROSE SOAP 125 G X4 CBD,2023-06-21,SK6C,"[1, 30]","[CAR, EA]","[6360.00, 212]",4231.02,9.0,9.0,380.79,380.79,4231.02
8,491903304,33059011,8901138845476,943744.0,HIM BABY HAIR OIL 100 ml PET,2023-06-21,SK6C,"[1, 48]","[C07, EA]","[6240.00, 130]",3595.93,9.0,9.0,323.63,323.63,3595.93
9,492367878,33049990,8901138848484,NaN,HIMALAYA ALE VERA FCE GEL 100ML CON,2023-06-21,SK6C,"[1, 24]","[CAR, EA]","[2040.00, 85]",1357.12,9.0,9.0,122.14,122.14,1357.12